### ISSUE TITLE
申请PHONE权限组必须将该组中所有权限都在Manifest文件中列出，否则申请失败

### ISSUE THREAD

**Issue by XuQK** [yanzhenjie/AndPermission#100]
用 AndPermission 申请 PHONE 权限组，需要在 Manifest 文件中将 PHONE 权限组的
```
READ_CALL_LOG
WRITE_CALL_LOG
USE_SIP
PROCESS_OUTGOING_CALLS
```
这四个权限全部列出，不然会实际上申请成功，但执行 PermissionListener 的 onFaliure 方法。

**Comment by yanzhenjie** [comment]
你应该是申请了权限组吧，权限组需要把权限组的权限都写上。申请的权限总之都要在Manifest中列出。
