### ISSUE TITLE
LOCATION权限，没有申请成功，不显示申请界面，直接走成功，是咋回事呢？小米手机，安卓版本7.1.2

### ISSUE THREAD

**Issue by cancanw** [yanzhenjie/AndPermission#101]

**Comment by zhang110116** [comment]
#小米Appops授权状态有同意，询问，拒绝。定位默认是询问吧   在success回调中 还需使用hasPermission判断一下AppOps 是否获取，因为国产手机checkPermission系统权限和AppOps Permission操作权限 可能不一致 #71

**Comment by yanzhenjie** [comment]
@zhang110116 说的有道理的，现在更新了两个版本兼容性更加好了，结合[国产适配方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案)可以更好的适配。

**Comment by lram7** [comment]
新版本小米5x手机依然存在问题，同时申请三个权限，只要有一个权限拒绝，然后二次检查时授权拒绝的权限，再次检查时3个权限都通过，但是使用过程中，发现没有权限。** 是不是小米手机同时授权多个权限时，必须全部都同意才算通过**？。使用了定位相关的权限。测试下来，进入设置把应用权限全部关闭，然后重新授权3个权限，一切正常。

**Comment by leveychen** [comment]
问题同样出现在 AVD模拟器上  版本7.1.1  有权限申请dialog，但是没有任何确认之后没有回调，卡在了界面上。

**Comment by yanzhenjie** [comment]
下周会发布新版本，会把Ops检测加入申请时的预判，现在的方案是使用`AndPermission.hasPermission(Context, String[])`方法检查权限，如果这个方法都返回有权限，那么应该是有权限了。  
**注意**：须使用1.1.2版本，旧版的检查使用`MODE_DEFAULT`不是很严格（虽然大多数手机上没有我呢提），但应该使用`MODE_ALLOWED`，1.1.2版本修复了这个问题。  
还有问题的话请大家继续反馈， 我会持续跟进这个issue。

**Comment by SugerGirl** [comment]
同样的问题  小米手机4 android6.0  不显示申请界面，直接返回成功  麦克风权限
在1.1.2版本上使用

**Comment by yanzhenjie** [comment]
大家可以试试AndPermission2.0-alpha版本，发布已经有好些天了，对国产机做了很多优化和兼容，目前的反响不错。如果没啥问题我就要发布2.0正式版了。
