### ISSUE TITLE
点了允许,但是回调到了failed里面

### ISSUE THREAD

**Issue by OvenCroc** [yanzhenjie/AndPermission#102]
机型 华为meta8 android系统7.0 , 调了一个权限组Permission.PHONE, Permission.LOCATION,点击了允许,但是回到走了failed方法 , 后来试了一下禁止 , 依然进了failed方法

**Comment by yanzhenjie** [comment]
试试[国产手机适配方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案) ？

**Comment by yanzhenjie** [comment]
No response closed.
