### ISSUE TITLE
AndPermission.hasPermission()改进建议与小米5请求权限拒绝后设置无效建议

### ISSUE THREAD

**Issue by wangchong33333** [yanzhenjie/AndPermission#104]
手机：小米5安卓7.0
1.在小米下权限申请拒绝后再设置中设置后，检测权限已获得，但实际未获得AndPermission.hasPermission()中的checkSelfPermission是android.support.v4.content.ContextCompat包下的，使用android.support.v4.content.PermissionChecker.checkSelfPermission()可以检测到实际未获得权限，原因未知。
2.在小米下权限申请拒绝后再设置中设置后，需要再次申请权限且用户确认后才可获得，使用AndPermission的申请权限方法无效，使用系统方法有效，原因未知。

**Comment by drakeet** [comment]
赞，情况说明得挺详细的，我的“纯纯写作”也用了这个库，十分依赖它，期待如果真有问题的话能够修复。

**Comment by yanzhenjie** [comment]
问题已确认，会尽快修复。

**Comment by yanzhenjie** [comment]
已经修复并发布新版本，请更新库版本。
