### ISSUE TITLE
依赖最新版本1.1.1，界面卡死，对话框出不来

### ISSUE THREAD

**Issue by JarvanChen** [yanzhenjie/AndPermission#105]

**Comment by yanzhenjie** [comment]
已经修复了，1.1.1现在已经覆盖发布，不想升级的话可以删除`GRADLE_USER_HOME`的`.gradle/caches/modules-2/files-2.1/com.yanzhenjie/permission`后，重新sync后继续使用1.1.1。
如果比较麻烦，请直接依赖1.1.2版本。
