### ISSUE TITLE
敬问大神：代码读取traces.txt需要什么权限？

### ISSUE THREAD

**Issue by wcglws** [yanzhenjie/AndPermission#106]
Android6.0之后读取ANR的traces.txt文件会报权限问题，但没提示到底缺啥权限，Google、百度一通也没找到有用的信息，所以前来请教大神。现在怀疑是否Google把相关权限回收，就像采集单个APP耗电量的权限一样

**Comment by yanzhenjie** [comment]
这个我还真没研究过，应该不属于运行时权限的范畴吧，我能想到的就是读写SD卡的权限。

**Comment by yanzhenjie** [comment]
No response closed.
