### ISSUE TITLE
Activity退出后，再次进入，申请权限没反应

### ISSUE THREAD

**Issue by VeiZhang** [yanzhenjie/AndPermission#107]
在示例中，[AndroidManifest][AndroidManifest]设置ListenerActivity为启动的Activity入口
```
<activity
    android:name=".ListenerActivity"
    android:label="@string/title_listener_request"
    android:theme="@style/AppTheme.NoActionBar">
    <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
    </intent-filter>
</activity>
```

然后运行，①从ListenerActivity进入，②返回退出后（不销毁app），③再次从ListenerActivity进入，④申请权限；结果是没有任何反应？？

[AndroidManifest]:https://github.com/yanzhenjie/AndPermission/blob/master/sample/src/main/AndroidManifest.xml

**Comment by yanzhenjie** [comment]
我刚按照你说的修改了项目，尝试了你说的情景，也尝试了其它操作，均正常反应。
