### ISSUE TITLE
AndPermission 默认对话框的标题、按钮文字看不见

### ISSUE THREAD

**Issue by zhangls2014** [yanzhenjie/AndPermission#108]
在 RationaleListener  中使用 AndPermission 默认对话框时发现，对话框、按钮的文字颜色都是白色，导致按钮不能被发现，同时 Title 也能被发现，可能颜色也是白色，而且默认的提示文字 _您已经拒绝过我们申请权限_ 缺少一个字吧，代码：`AndPermission.rationaleDialog(activity, rationale).show();`，AndPermission 版本为 1.1.2

**Comment by yanzhenjie** [comment]
是项目全局主题的原因吧。

**Comment by zhangls2014** [comment]
是我的问题，原因是第三方库覆盖我的全局主题-_-||，打扰了
