### ISSUE TITLE
requestCode和permission方法调用

### ISSUE THREAD

**Issue by fengchuxiaodai** [yanzhenjie/AndPermission#109]
如题，这两个方法调用不是队列形式存在的吧
比如：
AndPermission.with(this)
                    .requestCode(111)
                    .permission(Manifest.permission.RECORD_AUDIO)
                    .rationale(rationaleListener)
                    .callback(permissionListener)
                    .start();
和
 AndPermission.with(this)
                    .requestCode(111)
                    .permission(Manifest.permission.RECORD_AUDIO)
                    .requestCode(222)
                    .permission(Manifest.permission.CAMERA)
                    .rationale(rationaleListener)
                    .callback(permissionListener)
                    .start();

需要判断两个权限的情况下，是不是只能在permission里面写数组，然后再回调里面用haspermission进行某个权限的判定才能确认是哪个权限没有申请到；或者是在一个回调里面，进行另外一个权限的申请才行呢？

**Comment by yanzhenjie** [comment]
如果是连续申请几个权限，说明此时你需要用户同时授权几个权限，那么一起申请就可以了；如果需要单独判断某个权限是否有，直接在回调用传入你的权限，可以不用传入回调给你的`List<String>`。

**Comment by fengchuxiaodai** [comment]
了解，跟我理解的一样，就是链式传入单个权限和请求码，callback里面回调的请求码其实只有最后一个 ，对吧，前面的请求码是拿不到的，因为我看你代码里面请求码只有一个，不是一个集合

**Comment by yanzhenjie** [comment]
和队列无关，每个request都是独立的。

**Comment by fengchuxiaodai** [comment]
嗯  知道啦
  谢啦 大佬
