### ISSUE TITLE
米UI无法正常显示

### ISSUE THREAD

**Issue by metromancn** [yanzhenjie/AndPermission#11]
首先感谢严老大的AndPermission，我们在新版本"地铁通-MetroMan"中使用了它，非常简易的解决了权限问题。
http://android.myapp.com/myapp/detail.htm?apkName=com.xinlukou.metroman

然后提一个Bug：
我们在使用小米手机测试时，android6.0.1系统，没有弹出预计的权限请求对话框，而是直接由小米弹出了整体App的权限请求框，不知道是米UI的特殊定制，还是Bug

**Comment by yanzhenjie** [comment]
好像是小米的定制吧，他们的权限申请dialog也改了貌似。还有一个是小米有一个系统有bug，他们没有按照系统权限策略走，这个改天要我会做兼容一下。

**Comment by yanzhenjie** [comment]
已经发了新版，在新版中兼容了国产手机的各种问题，如果有时间麻烦再指导一下。
