### ISSUE TITLE
一加手机打电话权限

### ISSUE THREAD

**Issue by chsmy** [yanzhenjie/AndPermission#113]
一加手机打电话权限 禁止之后就不能在申请了，总是返回权限已经有了

**Comment by yanzhenjie** [comment]
[国产手机适配方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案)有看吗？检测到实际没有权限时，提示用户去Setting中开启权限，或者dialog引导用户去授权。

**Comment by chsmy** [comment]
有的 主要是当我拒绝之后再请求的时候，第一步checkSelfPermission()就返回的已经有权限了。所以下面的方法都不会走了。这样的话就不知道用户到底有没有这个权限了。我使用原生的试了也是这样。我想是不是手机厂商的bug。

**Comment by yanzhenjie** [comment]
拒绝之后用`AndPermission.hasPermission()`判断呢？

**Comment by chsmy** [comment]
用AndPermission.hasPermission()判断是OK的  后面的还是不行
具体效果如下
![图片](https://github.com/chsmy/AndroidDailyText/blob/master/image/a.gif)

gif图片如果没显示在这https://github.com/chsmy/AndroidDailyText/blob/master/image/a.gif

没显示dialog直接显示成功
成功里的代码
```
case REQUEST_CODE_PERMISSION_PHONE: {
                    // TODO do something.
                    Toast.makeText(ListenerActivity.this, R.string.successfully, Toast.LENGTH_SHORT).show();
                    Intent intent = new Intent(Intent.ACTION_CALL);
                    Uri data = Uri.parse("tel:"+"13161083183");
                    intent.setData(data);
                    startActivity(intent);
                    break;
                }
```
显示成功了，里面有打电话的代码，也没打出去 说明还是没成功~~

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了相应的的适配。
