### ISSUE TITLE
使用Kotlin编写代码，调用AndPermission.hasPermission方法，第二个参数无法使用Permission的常量数组

### ISSUE THREAD

**Issue by TheStar4Fate** [yanzhenjie/AndPermission#114]
None of the following functions can be called with the arguments supplied.
hasPermission(Context, vararg String!) defined in com.yanzhenjie.permission.AndPermission
hasPermission(Context, (Mutable)List<String!>) defined in com.yanzhenjie.permission.AndPermission

这是IDE的提示，希望能加一个参数类型为数组的重载方法

**Comment by ushuaia** [comment]
这么把数组解开：AndPermission.hasPermission(context, *permissions)

**Comment by yanzhenjie** [comment]
大家可以升级到了2.0.0试试，已经不需要这个方法了，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了相应的的适配。
