### ISSUE TITLE
始终禁止的权限，用AndPermission.hasPermission()检测返回为true？

### ISSUE THREAD

**Issue by DongYu-W** [yanzhenjie/AndPermission#116]
OPPO R9，始终拒绝的权限，回调会执行onSuccess，并且使用AndPermission.hasPermission()检测返回为true。更疑惑的是使用AndPermission.hasAlwaysDeniedPermission()检测也返回true？？！！所以这是Bug？

**Comment by wuqiong657** [comment]
vivo 也是

**Comment by yanzhenjie** [comment]
大家可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了相应的的适配。
