### ISSUE TITLE
弹出设置dialog会触发宿主的生命周期

### ISSUE THREAD

**Issue by zongkang** [yanzhenjie/AndPermission#117]
遇到个坑爹的bug ,在使用AndPermission申请运行时权限的时候，如果用户点击了拒绝，会弹出设置的dialog，我的天 他竟然会触发宿主activity的生命周期 onPause 和 onResume ，楼主看下呗

**Comment by INSTANTCITY** [comment]
这是bug吗？？

**Comment by yanzhenjie** [comment]
这个`Dialog`不是`AndPermission`主动弹的，是开发者自己调用的。另外这么基础的常识没啥好惊讶的。
