### ISSUE TITLE
我想问一下安卓6.0以下权限判断不出来吗？？

### ISSUE THREAD

**Issue by iammasir** [yanzhenjie/AndPermission#118]
那6.0以下权限怎么判断了，好多手机也会弹出一个权限的提示框让选择同意或者拒绝。我是用异常判断的

**Comment by GrayXu** [comment]
6.0以下如果有这样的提示，怕是针对manifest里面静态申请的权限。我觉得完全可以判断当前SDK版本后，大于等于23才用这个框架。
