### ISSUE TITLE
拒绝之后仍然返回true的问题

### ISSUE THREAD

**Issue by verzqli** [yanzhenjie/AndPermission#119]
您好，严大，我暂时没有使用您的库，只是碰到了这个问题，小米和魅族（5s）手机在我拒绝了权限之后 用checkself返回给我的标志仍然是0 也就是允许，因为拒绝了之后再次申请时我需要给用户弹一个框通知用户去系统那里自己去打开权限，现在返回给我的标志都是我已经赋予了权限，所以没法判断，小米我通过appops解决了这个问题 返回来的mode来进行判断，但是魅族5s（因为我没有其他多余的魅族测试机了，我不知道只是这个机型还是魅族所有的机型）依旧坚挺，永远返回给我的是allowed 也就是有权限，不知道您的库是否已经解决了这个问题，我看了您的国产适配方案，没看到魅族的这种连appops都拯救不了的权限设置，是要直接放弃吗？谢谢了

**Comment by yanzhenjie** [comment]
AppOps都没办法判断的权限真是没办法了，可以直接执行代码试试看，可能不会崩溃，可能会弹出系统自己的权限申请框，也可能直接就是有权限的。

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了相应的的适配。
