### ISSUE TITLE
Vivo x20，适配问题

### ISSUE THREAD

**Issue by Hellozhongxin** [yanzhenjie/AndPermission#120]
在进入下一个界面前，申请相机和录音权限：
只弹出申请相机权限，进入下一个界面，在使用到录音权限时，才弹出录音权限申请。

都拒绝权限，还调用PermissionListener的onSucceed（）
在方法里面判断AndPermission.hasPermission(context, permissions)
还是返回true，然后调用了成功的代码，进入了下一个界面。期望：拒绝就不进入。

请问这该如何适配

**Comment by yanzhenjie** [comment]
似乎系统还是走了自己的权限系统，对于你的情况，目前没有好的方案。  
建议你可以在需要的时候申请，这也是Google官方推荐的做法。

**Comment by Hellozhongxin** [comment]
后来发现，接触到的所有vivo机型都是这个style，无解的样子

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了相应的的适配。
