### ISSUE TITLE
判断是否有某个权限

### ISSUE THREAD

**Issue by zhijiazheng123** [yanzhenjie/AndPermission#122]
请问有没有方法可以判断是否已经申请了某个权限？

**Comment by yanzhenjie** [comment]
1.x版本是有的，你估计没看ReadMe或者Demo。

现在你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。
