### ISSUE TITLE
Google API 25模拟器-电话权限始终返回false

### ISSUE THREAD

**Issue by tomguan** [yanzhenjie/AndPermission#123]
final Activity activity = this;

                AndPermission.with(this).requestCode(200).permission(Permission.PHONE).rationale(new RationaleListener() {
                    @Override
                    public void showRequestPermissionRationale(int requestCode, final Rationale rationale) {

                        // 此对话框可以自定义，调用rationale.resume()就可以继续申请。
                        AndPermission.rationaleDialog(activity, rationale).show(); 
                    }
                }).callback(new PermissionListener() {
                    @Override
                    public void onSucceed(int requestCode, @NonNull List<String> grantPermissions) {

                        System.out.println();
                    }

                    @Override
                    public void onFailed(int requestCode, @NonNull List<String> deniedPermissions) {

                        // 是否有不再提示并拒绝的权限。
                        if (AndPermission.hasAlwaysDeniedPermission(activity, deniedPermissions)) {
                            // 第一种：用AndPermission默认的提示语。
                            AndPermission.defaultSettingDialog(activity, 400).show(); n.defaultSettingDialog(activity, 400) 
                        }
                    }
                }).start();

--------------------------------------------------------------------
PHONE = new String[]{
                    Manifest.permission.READ_PHONE_STATE,
                    Manifest.permission.CALL_PHONE,
                    Manifest.permission.READ_CALL_LOG,
                    Manifest.permission.WRITE_CALL_LOG,
                    Manifest.permission.USE_SIP,
                    Manifest.permission.PROCESS_OUTGOING_CALLS};

我开启权限后，返回false。我跟踪了deniedPermissions， 数组是5个元素。

通过观察，我发现 只授权了 ‘Manifest.permission.CALL_PHONE‘， 别的5个没有授权。而回调了onFailed。我可以配合楼主测试

**Comment by tomguan** [comment]
nexus6 Android6.0。也是同样的问题

**Comment by yanzhenjie** [comment]
大家可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。
