### ISSUE TITLE
打包有问题

### ISSUE THREAD

**Issue by ShawnXiaFei** [yanzhenjie/AndPermission#124]
直接run，机器表现正常；
但是，不混淆，打包出来的APK，却不能弹出授权框，系统是MTK直接释放的8167 7.0系统。

**Comment by yanzhenjie** [comment]
我也不知道什么问题，请问解决了吗？

**Comment by yanzhenjie** [comment]
No responsed, close.

**Comment by ShawnXiaFei** [comment]
抱歉，平时上线不多，今天才看到消息。
这个问题没能解决，最后自己封装的方法处理的，不过还是很感谢您。
