### ISSUE TITLE
hasAlwaysDeniedPermission  判断有问题吧  授权了也会弹出去设置的提示

### ISSUE THREAD

**Issue by RiceLee** [yanzhenjie/AndPermission#125]
hasAlwaysDeniedPermission方法判断 
for (String permission : deniedPermissions) {
            boolean rationale = activity.shouldShowRequestPermissionRationale(permission);
            if (!rationale) return true;
        }
看这个方法的意思应该是是否没有授权，没有授权应该返回true的意思吧
现在这样的话授权了也会返回true  应该是  if(rationale) return true;

**Comment by yanzhenjie** [comment]
一个字：没毛病。你肯定没看这个方法的注释或者参数名，甚至ReadMe。
