### ISSUE TITLE
关于进一步优化

### ISSUE THREAD

**Issue by imaiya** [yanzhenjie/AndPermission#127]
严大你好 这里有些问题想请教下  在你的AndPermission开源项目中   我看到使用透明PermissionActivity作为中间页的巧妙方法 达到在非Activity环境中请求权限 但是Rationale和SettingDialog的处理也还是需要Activity环境的  这个你有没有想到什么方案去解决这个问题呢

**Comment by yanzhenjie** [comment]
你可以看看2.0.0版本的源码，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。
