### ISSUE TITLE
设置PermissionActivity为全屏透明

### ISSUE THREAD

**Issue by LichFaker** [yanzhenjie/AndPermission#128]
如题：实际使用时，该Activity销毁时，会有明显的带黑边动画

**Comment by yanzhenjie** [comment]
已经解决了这个问题，你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。
