### ISSUE TITLE
Fragment嵌套Fragment申请权限

### ISSUE THREAD

**Issue by Cwj1992** [yanzhenjie/AndPermission#13]
使用Fragment嵌套Fragment，进行权限申请，由于无法回调onRequestPermissionsResult()导致不能正确回调权限申请结果。这个有办法解决吗

**Comment by yanzhenjie** [comment]
这个`child fragment`所在的`parent fragment`和宿主`Activity`的`onRequestPermissionsResult()`方法都不要重写，如果重写了的话不要删除`supper.onRequestPermissionsResult()`，如果还是不行，在`parent fragment`的`onRequestPermissionsResult()`方法中手动调用这个`child fragment`的`onRequestPermissionsResult()`方法。

**Comment by Cwj1992** [comment]
前面的方法不行，后面的没试过，我现在是借助parent fragment中的onRequestPermissionsResult()来完成child fragment的权限申请，在child fragment中使用到权限的地方：getParentFragment().XXX()。下次试试你说的第二种方法。经常在掘金看到您的文章，挺实用的。
