### ISSUE TITLE
请问支持kotlin吗

### ISSUE THREAD

**Issue by MLlgy** [yanzhenjie/AndPermission#130]

**Comment by MLlgy** [comment]
我自己尝试的结果是不支持

**Comment by yanzhenjie** [comment]
好像有人在Kotlin中用了的，具体我也没用过。
你可以直接试试2.0.0，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。

**Comment by yuhaoz** [comment]
同样，测试结果是不支持kotlin。
找了一个替代库：https://github.com/afollestad/assent
