### ISSUE TITLE
Demo中 Image+Video.功能，程序奔溃了！

### ISSUE THREAD

**Issue by DevXue** [yanzhenjie/AndPermission#132]
我在Demo中用的小米Note Android 6.0，mui 8 测试了 Image+Video功能  ，首先选择录视频， 成功回来之后 然后选择拍照，回来直接就报错闪退了，   我用4.4的手机测试也是这个情况， 应该和顺序没有关系  先选择拍照，再次选择录视频回来也是报错闪退！
以下是报错日志
![te](https://user-images.githubusercontent.com/9455329/33865433-aa4f66c8-df2c-11e7-8479-f0da5f667da8.png)

**Comment by 897902334** [comment]
希望严神看看这个问题！  谢谢！

**Comment by 897902334** [comment]
抱歉。我发错了了  应该是图片选择库  我咋写到这了···  抱歉！！
