### ISSUE TITLE
vivo权限跳转

### ISSUE THREAD

**Issue by wuqiong657** [yanzhenjie/AndPermission#134]
vivo, x6sa android5.1.1，跳转到权限设置页面，不正确，只能跳转到app详情页面。

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
对于权限设置页面跳转也做了响应的适配。
