### ISSUE TITLE
vivo  x9 7.1.1 手机不适配 

### ISSUE THREAD

**Issue by ywanhzy** [yanzhenjie/AndPermission#136]
vivo  x9 7.1.1  手机根本不执行AndPermision的方法   全部走vivo自己的权限适配方法

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
