### ISSUE TITLE
红米5A手机有点问题

### ISSUE THREAD

**Issue by pozhupt** [yanzhenjie/AndPermission#138]
在红米手机上测试时，用你的框架申请定位权限，选择拒绝，然后第二次申请时弹出提示没权限框，然后点击去设置设置允许后，还是提示没权限。

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
