### ISSUE TITLE
努比亚nx549j申请权限直接弹出权限已被拒绝

### ISSUE THREAD

**Issue by vincecarterhu** [yanzhenjie/AndPermission#139]
nubia UI 4.0  android版本 6.0.1
如果设置了rationale 的回调

**Comment by vincecarterhu** [comment]
@yanzhenjie

**Comment by yanzhenjie** [comment]
你可以升级到了2.0.0试试，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。

**Comment by KentFeng** [comment]
杰哥，我在nubia 7.1.1上使用新的2.0.0的，直接崩溃，调试也不走三个回调方法。

**Comment by KentFeng** [comment]
@yanzhenjie

**Comment by yanzhenjie** [comment]
@KentFeng 单独提issue，提问按照文档要求的格式来，如果发生crash请贴出堆栈信息。
