### ISSUE TITLE
您好，魅族手机没有弹窗，而且会默认走授权成功的方法，然后到设置那里去看是没有授权的，用hasPermission也是有权限的，这个怎么解决

### ISSUE THREAD

**Issue by a383459354** [yanzhenjie/AndPermission#141]

**Comment by yihongyuelan** [comment]
如果是6.0以前的系统，直接就会判断有权限。而Android在6.0之前的权限控制，大多数都是各个ROM厂商自己定制的。
针对6.0以前的权限控制，可以参考：
https://github.com/android-cn/android-discuss/issues/174

**Comment by yanzhenjie** [comment]
大家可以升级到了2.0.0，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容（比如小米、魅族、华为、VIVO、OPPO、锤子、坚果、360、三星、HTC等），并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。

**Comment by Dordong** [comment]
@yanzhenjie 我也碰到同样的问题。
魅族手机  魅蓝note5  Flyme6.7.7.1  android版本6.0  所有权限；
场景，设置中所有权限都处于询问状态下，开启权限，没有弹窗默认调用onGranted；
设置中所有权限处于禁止状态下，调用方法，没有弹窗调用onGranted；
demo中出现，昨天下载的；自己项目中依赖com.yanzhenjie:permission:2.0.0-alpha也是同样情况

**Comment by yanzhenjie** [comment]
@Dordong 先举个例子，比如SD权限，如果回调你有应该就是有的，我会在SD卡中写入一个`ANDROID.PERMISSION`的文件（第二次检测时会删除），这样测试的还有其它权限，这里不例举。

在魅族上是有一些权限，比如定位、电话，这种不能真正的执行到相应的代码来测试，所以会有错误。不过你可以放心的执行代码，不要再纠结这个状态返回是否正确，对于这种情况，没有任何一个库可以准确返回状态，详情请参考[特殊说明](http://www.yanzhenjie.com/AndPermission/cn/explain.html)。

另外，请大家一定认真看文档，看完后还是有问题，按照[提问](http://www.yanzhenjie.com/AndPermission/cn/issue.html)中描述的格式发起issue。
