### ISSUE TITLE
锤子OD103 适配失败

### ISSUE THREAD

**Issue by biyeshengplay** [yanzhenjie/AndPermission#142]
手机型号：锤子OD103
Android版本：7.1.1

关闭相机权限，打开相机，PermissionListener走了onSucceed，在onSucceed回调里用AndPermission.hasPermission二次判断依然判断为有权限，但是实际是没有权限的。

**Comment by nelsonie** [comment]
锤子系统为了体验有修改过，申请权限的时候都会给返回成功调用onSucceed，也会告诉你有权限，只有在你用的时候才能知道是不是真有权限。而且系统弹出的是否允许APP使用权限的对话框也是在使用那步才会弹出。
猜测是因为好多APP去申请了很多不去使用的权限，还有一些APP不给权限就不让你继续使用了，所以锤子为了用户体验统一先给了允许使用，讨好了用户，坑了开发者。

**Comment by lijinbolove** [comment]
@nelsonie 说是这样说,可是作为开发者,问题还是要解决的,那么请问这个问题该怎么解决啊

**Comment by yanzhenjie** [comment]
大家可以升级到了2.0.0，2.0.0版本改动较大，主要是针对中国产手机的权限问题做了兼容，并且支持Android5.0系统中的权限申请，具体使用方法请阅读文档。
由于关注这个问题的人较多，暂不关闭，希望可以得到大家的回复。
