### ISSUE TITLE
使用PermissionChecker检查是否有权限

### ISSUE THREAD

**Issue by yihongyuelan** [yanzhenjie/AndPermission#144]
`AndPermission.hasPermission()的原理是在Android 6.0以下默认返回`true`，在6.0以上使用`AppOps`和`checkSelfPermission`检测权限全部通过则返回`true`，只有有一个没通过就返回`false`。

代码是：
            int result = context.checkPermission(permission, android.os.Process.myPid(), Process.myUid());
            if (result == PackageManager.PERMISSION_DENIED) {
                return false;
            }

            String op = AppOpsManager.permissionToOp(permission);
            if (TextUtils.isEmpty(op)) {
                return false;
            }
可以使用PermissionChecker代替：

        int result = PermissionChecker.checkPermission(context,
                    permission,
                    android.os.Process.myPid(),
                    android.os.Process.myUid(),
                    context.getPackageName());`
其实现是一样的：
    public static int checkPermission(@NonNull Context context, @NonNull String permission,
            int pid, int uid, String packageName) {
        if (context.checkPermission(permission, pid, uid) == PackageManager.PERMISSION_DENIED) {
            return PERMISSION_DENIED;
        }

        String op = AppOpsManagerCompat.permissionToOp(permission);
        if (op == null) {
            return PERMISSION_GRANTED;
        }

        if (packageName == null) {
            String[] packageNames = context.getPackageManager().getPackagesForUid(uid);
            if (packageNames == null || packageNames.length <= 0) {
                return PERMISSION_DENIED;
            }
            packageName = packageNames[0];
        }

        if (AppOpsManagerCompat.noteProxyOp(context, op, packageName)
                != AppOpsManagerCompat.MODE_ALLOWED) {
            return PERMISSION_DENIED_APP_OP;
        }

        return PERMISSION_GRANTED;
    }

**Comment by yanzhenjie** [comment]
没错。
