### ISSUE TITLE
targetSdkVersion 23 无法使用这个库 

### ISSUE THREAD

**Issue by fujingxie** [yanzhenjie/AndPermission#147]
targetSdkVersion 23 无法使用这个库 必须是25的 我不想兼容到25 请问targetSdkVersion 23想使用这个库如何使用

**Comment by yanzhenjie** [comment]
不会吧，没有这个限制啊 ，只有targetApi不能低于11这一个Api限制。你应该是本地没有25的support库，集成报错了吧，你可以使用gradle的exclude过滤掉AndPermisission的support库，或者升级你的SDK。
