### ISSUE TITLE
第一次给联系人设置权限组失败

### ISSUE THREAD

**Issue by 17710924717** [yanzhenjie/AndPermission#150]
在第一次运行demo  第一次给联系人设置权限组的时候点击始终运行的情况下  会走onDenied    其他的不会

**Comment by yanzhenjie** [comment]
麻烦看一下文档，如果还有问题，请尽量提供更详细的环境条件：  
[特别说明](http://www.yanzhenjie.com/AndPermission/cn/explain.html)

**Comment by yanzhenjie** [comment]
@17710924717 非常感谢你的反馈，后来组织了多次测试后，发现确实存在你说的问题，刚刚发布了2.0.0-rc1，修复了这个问题。
