### ISSUE TITLE
请求多个权限时，出现了崩溃问题

### ISSUE THREAD

**Issue by AlvinQiang** [yanzhenjie/AndPermission#152]
机型：小米6
Android系统的版本：7.1.1
权限：获取手机状态、定位、读写
场景：请求多权限时，假设我只允许了获取手机状态的权限，拒绝了定位和读写权限，在Rationale中监听到后，弹出dialog，在执行一次开启是使用的executor.execute(); 这时候，第一次获取的手机状态的权限又弹出来了，而且如果我拒绝了这个权限，就GG了。

**Comment by yanzhenjie** [comment]
麻烦提供一下堆栈信息。

**Comment by AlvinQiang** [comment]
额，着急赶项目，换了之前的写法，老哥可以抽空测一下或者我忙完了^_^

**Comment by yanzhenjie** [comment]
这边测试了你说的情况，没有复现，检查一下是不是你那边回调后的问题。

**Comment by yanzhenjie** [comment]
No responsed, close.
