### ISSUE TITLE
PermissionTest.java 游标越界,导致判断有误

### ISSUE THREAD

**Issue by leonzone** [yanzhenjie/AndPermission#153]
31行代码 int type = cursor.getType(0);报Index -1 requested, with a size of Xxx错误

原因是因为调用getCount方法后，cursor就游到表的末尾了，需要调用一下cursor的moveToFirst，将游标重新挪到表的首位

**Comment by joinmysunshine** [comment]
hello @leonzone  请问问题出现的概率是多少呢？

**Comment by yanzhenjie** [comment]
@leonzone 你好，请问是什么权限出现的这个问题？是必现吗？  
另外以后提issue时请按照这个格式：[提问](http://www.yanzhenjie.com/AndPermission/cn/issue.html)。

我看了一下几个cursor的源代码，没有找到调用`Curcor#getCount()`后就跑到末尾的证据，可能是因为其它原因。我这边没复现，你能否把你调试的堆栈信息提供一下。

**Comment by leonzone** [comment]
1.手机:坚果
2.Android系统的版本:5.1.1
3.是什么权限？Permission.READ_CALL_LOG
4.场景:同意了权限,可回调走了onDenied

**Comment by leonzone** [comment]
1.手机:坚果
2.Android系统的版本:5.1.1
3.是什么权限？Permission.READ_CALL_LOG
4.场景:同意了权限,可回调走了onDenied
5.错误信息为:android.database.CursorIndexOutOfBoundsException: Index -1 requested, with a size of 10
异常发生在 PermissionTest 的31行 int type = cursor.getType(0);异常被catch到了,异常为CursorIndexOutOfBoundsException.
确实和调用了getCount无关,原因是cursor初始下标为-1,而代码直接调用了getType,此时的下标为-1,所以会有越界错误.其实和手机版本没关系.我下载了源代码在
异常发生在 PermissionTest 的31行 int type = cursor.getType前加上 cursor.moveToFirst(); 运行成功

**Comment by yanzhenjie** [comment]
非常感谢指正，我重复看了这个代码数次，一直忽略掉了这个细节，现在恍然大悟。你能否就这个问题提一个PR？我想大家一起来完善这个项目，而不是我一个人在吧唧吧唧的弄，这也是你的想法和发现。:smile:

**Comment by leonzone** [comment]
好的,很感谢你的项目.
