### ISSUE TITLE
2.0版本通讯录读取权限问题

### ISSUE THREAD

**Issue by Tomcater** [yanzhenjie/AndPermission#154]
安卓模拟器Android7.1.1 通讯录读取权限;
第一次拒绝权限后第二次请求允许权限缺回调了onDenied方法?

**Comment by yanzhenjie** [comment]
我用6.0 7.0 8.0的Android模拟器按照你的描述请求了读取通讯录权限，并没有出现你描述的问题。请你再确认一下。  
另外，有些手机就算你同意，也不一定真正有权限，你可以在设置中看看，如果设置中没有就证实了我的说法，如果测试中有，你可以执行读取通讯录的代码试试，可能会报你没有权限的异常。  
最后如果以后有问题，也可以结合文档排查：[用法](http://yanzhenjie.github.io/AndPermission/cn/usage.html)

**Comment by yanzhenjie** [comment]
No responsed, close.
