### ISSUE TITLE
魅蓝M6,安卓7.0不兼容

### ISSUE THREAD

**Issue by keepgoodfeeling** [yanzhenjie/AndPermission#155]
用Demo运行,魅蓝M6,安卓7.0系统,没有任何权限提示就弹出Toast说成功了.

**Comment by yanzhenjie** [comment]
文档：
[特别说明](http://www.yanzhenjie.com/AndPermission/cn/explain.html)  
[提问](http://www.yanzhenjie.com/AndPermission/cn/issue.html)
