### ISSUE TITLE
申请权限成功的回调跳转到另一个Activity会短暂黑屏

### ISSUE THREAD

**Issue by ximencx** [yanzhenjie/AndPermission#156]
申请权限成功的回调，延迟500ms，在跳转则没问题。
系统华为mate9，Android7.0

**Comment by yanzhenjie** [comment]
文档：
* [特别说明](http://www.yanzhenjie.com/AndPermission/cn/explain.html)  
* [提问](http://www.yanzhenjie.com/AndPermission/cn/issue.html)

**Comment by ximencx** [comment]
@yanzhenjie 经过检查  和另起一个Activity的主题有关

**Comment by ximencx** [comment]
@yanzhenjie 哥们这个确实是  框架起的permissionActivity的相关bug，，接收到权限申请后，，回调里跳转Activity，这时permissionActivity的finish还没走完onstop  就会跳转黑屏。
