### ISSUE TITLE
BadTokenException

### ISSUE THREAD

**Issue by k354250377** [yanzhenjie/AndPermission#157]
#6482 android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@f1e0919 is not valid; is your activity running?
com.yanzhenjie.alertdialog.AlertDialog$Api21Dialog.void show()(SourceFile:142)

**Comment by k354250377** [comment]
这是啥意思啊 老铁

**Comment by yanzhenjie** [comment]
没有更多信息了吗？这个还真还不出来。  
如果自己不能判断，先看看文档：[http://yanzhenjie.github.io/AndPermission/cn](http://yanzhenjie.github.io/AndPermission/cn)

**Comment by k354250377** [comment]
老大 还有一个问题 就是彻底拒绝权限后 我怎样才能监听从设置返回到app啊 之前能用onActivityResult 最新版这个方法不能用了

**Comment by k354250377** [comment]
难道只能用生命周期去处理了么

**Comment by yanzhenjie** [comment]
`2.0.0-rc2`已经发布了，添加了`requestCode`的能力。
