### ISSUE TITLE
vivo x7 5.1.1： 1、日历权限点击允许，还是返回 没有权限。2、部分手机点击允许后系统中状态仍然为“询问”，导致申请权限和使用权限都会弹出权限对话框，使用者比较厌烦

### ISSUE THREAD

**Issue by lsfzlj** [yanzhenjie/AndPermission#159]

**Comment by yanzhenjie** [comment]
第一个问题，参考这个issue的回答： #160 。  
第二个问题，系统的问题还真没办法，使用者厌烦就去设置中改为同意或者完全拒绝呗。这种情况比较少见，说实话能兼容5.x的系统确实不易，我确实想不出更好的办法来解决这个问题，如果你有方案的话能否共享一下。

**Comment by yanzhenjie** [comment]
No responsed, close.
