### ISSUE TITLE
获取到camera权限后却还是收到了onDenied回调

### ISSUE THREAD

**Issue by xeexeexee** [yanzhenjie/AndPermission#160]
红米note4x android7.0和谷歌nexus5x android 8.0都有这样的问题。按正常步骤获取了Manifest.permission.CAMERA, Manifest.permission.READ_EXTERNAL_STORAGE,
                                    Manifest.permission.WRITE_EXTERNAL_STORAGE三个权限，也获取成功了。但获取成功后又收到了onDenied回调，AndPermission.hasAlwaysDeniedPermission为true
再次调用获取权限接口，直接收到onDenied回调，AndPermission.hasAlwaysDeniedPermission为true...
但6.0系统的设备就没有这样的问题。感觉可能7.0往上的系统都会收到onDenied回调，但6.0以下的就没问题
很奇怪的是另一个app用同一套代码完全没有问题，相同的手机，系统，SDK，manifest里的权限配置，targetversion等等都是相同的.....却可以成功收到onGranted回调

想问下老哥有没有啥解决办法或者思路.....十分感谢

**Comment by yanzhenjie** [comment]
是否请求授权了权限组，如果权限组中的某一个权限被拒绝，那么该请求视为请求失败。  
在同事请求多个权限，任何一个权限授权失败，该请求视为失败的。  
* [文档](http://yanzhenjie.github.io/AndPermission/cn)

**Comment by xeexeexee** [comment]
感谢老哥的回答~
但这三个权限在设置-权限管理中查看是已经打开了的
但请求时还是会得到onDenied回调
很奇怪

**Comment by yanzhenjie** [comment]
你的另一个App没问题的话，想必还是要排查一下你的代码。你可以新建个项目，专门测试一下。

**Comment by xeexeexee** [comment]
感谢老哥的回答...
抱歉是我的表述有问题，又重新跑了一遍找到了问题的原因，但还是没思路解决
按正常步骤获取权限，权限获取成功，在onGranted中调用系统相机的api
此时设置-权限里我申请的相机与存储读取权限已经获取到了
但api调用失败，获取到了onDenied回调...
奇怪...

**Comment by yanzhenjie** [comment]
你应该看看这个：[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)。仅仅说失败是无法判断错误原因的，要根据堆栈信息判断。

**Comment by xeexeexee** [comment]
看了下堆栈信息...
Uid 10629 does not have permission to uri 0 @ content://com.tianer.dooya.fileprovider/camera.photos/dooya/1517973162587.jpg

看起来好像的确是权限问题...没有权限？可是该申请的我都申请了啊...

**Comment by yanzhenjie** [comment]
你可以多贴一点堆栈信息。从这一段判断，应该不是相机权限，可能是7.0 file contentProvider的问题。

**Comment by xeexeexee** [comment]
主要是就只有这么多信息....
java.lang.SecurityException: Uid 10629 does not have permission to uri 0 @ content://com.tianer.dooya.fileprovider/camera.photos/dooya/1517973162587.jpg

的确是使用了contentProvider，我往这方向找找看吧
谢谢老哥的回答~
