### ISSUE TITLE
锤子手机 获取相机权限  点击拒绝之后  黑屏了 也没有走进拒绝的回调。

### ISSUE THREAD

**Issue by DeveloperZH** [yanzhenjie/AndPermission#161]

**Comment by yanzhenjie** [comment]
请按照模板提问，如果方便的话，麻烦提供一下堆栈信息。  
* [文档](http://yanzhenjie.github.io/AndPermission/cn/)
* [提问](http://yanzhenjie.github.io/AndPermission/cn/issue.html)

**Comment by yanzhenjie** [comment]
No responsed, close.
