### ISSUE TITLE
vivo x6plus android5.0.2拒绝权限之后走了获取权限成功的方法

### ISSUE THREAD

**Issue by tx123456** [yanzhenjie/AndPermission#168]
拒绝权限之后走了获取权限成功的方法
机型 vivo x6plus
android5.0.2

**Comment by yanzhenjie** [comment]
@tx123456 你可以看看这个说明，看了应该可以解决。因为这个项目需要兼容国产机，所以麻烦提问时按照文档要求，不然我很难帮助到你。  
[http://yanzhenjie.github.io/AndPermission](http://yanzhenjie.github.io/AndPermission)  

@zhangls2014 你单独提了issue，请直接在你的issue中继续回复即可，这样也少打扰到别人。

**Comment by yanzhenjie** [comment]
No responsed, close.
