### ISSUE TITLE
PermissionActivity感觉经常会出现内存泄露的情况

### ISSUE THREAD

**Issue by tx123456** [yanzhenjie/AndPermission#169]
![cache_2dc048b4ce982e27](https://user-images.githubusercontent.com/14331075/36071127-6544e5f6-0f44-11e8-8a30-35b7fe98a804.jpg)

**Comment by yanzhenjie** [comment]
比较新的版本都不会出现这个问题了，你这是哪个版本？  
提问时可以先看看文档，尽量提供详细的信息：  
* [http://yanzhenjie.github.io/AndPermission](http://yanzhenjie.github.io/AndPermission)

**Comment by yanzhenjie** [comment]
No responsed, close.
