### ISSUE TITLE
红米Node3  获取SD卡权限反回结果问题   

### ISSUE THREAD

**Issue by longtaoge** [yanzhenjie/AndPermission#17]
经过反复测试得出如下结论

targetSdkVersion ＜23　　时  
一般厂商应用不申请 运行时权限可以正常使用

红米Node3   
SD卡的读写权限不会提示用户拒绝或接受

Manifest.permission.WRITE_EXTERNAL_STORAGE,
Manifest.permission.READ_EXTERNAL_STORAGE

 ActivityCompat.checkSelfPermission(activity,  
                Manifest.permission.WRITE_EXTERNAL_STORAGE)  ;  
   永远等于 PackageManager.PERMISSION_GRANTED

因此会造成检测有权限却无法使用的情况

**Comment by yanzhenjie** [comment]
小米Node3是哪个版本的？如果是23以下，直接使用就好了，如果是23以上，申请成功或者判断是成功而没有权限，你可以使用AppOpsManager、AppOpsManagerCompat来再次判断。

**Comment by longtaoge** [comment]
MIUI8.1 稳定版
8.1.1.0(MHOCNDI)
版本号 MMB29M
targetSdkVersion =22 时   SD卡不可用

**Comment by yanzhenjie** [comment]
这个项目是6.0运行时权限管理。也就是说适用于api level >= 23，按照Google官方的设计，<=22时默认有权限。你可以看看这篇文章：http://blog.csdn.net/yanzhenjie1003/article/details/52503533
