### ISSUE TITLE
权限授予判断错误

### ISSUE THREAD

**Issue by zhangls2014** [yanzhenjie/AndPermission#170]
我的 XiaoMi 6 手机安装的 Mokee 7.1.2 系统，项目中使用的是 AndPermission 2.0.0-rc2 版本，在获取存储空间权限时，点击的允许按钮授予了权限，在回调 onGranted 的同时调用了 onDenied 方法，并且在 onDenied 中调用
 AndPermission.hasAlwaysDeniedPermission(context, permissions)，返回为 true

在重新安装应用后，在获取授权是点击拒绝，则回调的是 onGranted 方法

**Comment by zhangls2014** [comment]
经过测试，在 AndPermission 2.0.0-alpha 版本也存在该问题

**Comment by yanzhenjie** [comment]
你的`onGranted()`中有异常，详见文档：  
* [特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)
