### ISSUE TITLE
如何修改AndPermission自带Dialog的按钮文字颜色?

### ISSUE THREAD

**Issue by sweet2o09** [yanzhenjie/AndPermission#171]
严大神,如何修改AndPermission自带Dialog的按钮文字颜色?我没找到相应的设置方法,我用的是1.1.2版本

**Comment by yanzhenjie** [comment]
旧版本在Android5.0以下用的`Compat`库中的的`AlertDialog`，在Android5.0.及以上用的SDK默认提供的`AlertDialog`，会根据你主题自动定颜色的，不是由`AndPermission`决定的。但是旧版并没有限定你使用`AndPermission`提供的`Dialog`，只是为了一些懒得自己写`Dialog`的开发者方便，你完全可以自己写一个`Dialog`。

新版2.0中没有提供`Dialog`了，并且去掉了`Compat`库，为了直接让开发者在`Support Fragment`中可以调用`AndPermission`，只是原生的`Android SDK` + `Support Fragment`即可。如果开发者需要用`Dialog`引导用户去设置，需要自己new相应的`Dialog`。

不过说了这么多，这都是不是重点，AndPermission2.0 Api更加简单方便了，而且对国产机的兼容性也更好了，赶快试试吧。  
* [文档](http://yanzhenjie.github.io/AndPermission)
