### ISSUE TITLE
蓝牙权限明明禁止了，但是方法中，总是通过是什么原因。类似的还有位置权限;

### ISSUE THREAD

**Issue by yigepang** [yanzhenjie/AndPermission#172]
测试设备是魅族MX4,VIVOX20,都不行

**Comment by yigepang** [comment]
其他方法都可以，就是蓝牙和位置权限禁止了，在grant中的action显示通过，官方demo中调试请求蓝牙权限也是这样的效果

**Comment by yanzhenjie** [comment]
蓝牙权限不是运行时权限。对于位置权限，请看一下文档说明：[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)，另外提问时请按照文档中的要求提供下环境信息，因为这个特别不好排查。

**Comment by yanzhenjie** [comment]
No responsed, close.
