### ISSUE TITLE
华为8.0系统申请权限  禁止和允许都走 onDenied方法

### ISSUE THREAD

**Issue by WhiteCjy** [yanzhenjie/AndPermission#173]
华为荣耀V10
安卓8.0系统
申请Permission.WRITE_EXTERNAL_STORAGE,Permission.CALL_PHONE2个权限，并且只出现第一个申请文件权限弹窗，禁止和允许都走申请失败方法。

**Comment by yanzhenjie** [comment]
1. 关于`CALL_PHONE`权限不弹窗的可能性：1. 有权限了，2. 没有权限，但是系统不弹窗。  
2. 关于`WRITE_EXTERNAL_STORAGE`权限都回调失败的方法可能性：1. 系统同意的假的同意，这一点去系统的权限设置中查看一下，2. 回调了`onGrated()`，但是`onGrated()`发生异常，会默认为没有权限回调到`onDenied()`。

因为我这边没有这个机器，所以还要麻烦你配合文档验证下是否存在上面几种可能性，如果确定是AndPermission的问题，麻烦再回复一下，我会找机器适配。
* [特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)

**Comment by WhiteCjy** [comment]
查看应用权限了 文件权限允许了是有的，还是回调onDenied()方法，电话权限还是没有，系统不弹窗

**Comment by yanzhenjie** [comment]
调用`onGrated()`发生异常，会默认为没有权限回调到`onDenied()`，AndPermission内部写了一个文件到SD卡，如果写不成功也会调用没权限。不弹窗是在上述文档有说到，你配合文档直接写出完整的代码测试。

**Comment by yanzhenjie** [comment]
No responsed, close.
