### ISSUE TITLE
AS3.0.1 ,gradle直接添加依赖，报错Unable to merge dex

### ISSUE THREAD

**Issue by sjindong** [yanzhenjie/AndPermission#175]
在gradle中 直接添加 了 依赖 implementation 'com.yanzhenjie:permission:2.0.0-rc2'， 就报下面的错误，去掉就好的

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForXX'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by yanzhenjie** [comment]
可能是因为引入了重复的库，这个库为了让`support-fragment`直接通过`with(this)`调用，所以加了`support-fragment`库，你把这个库过滤掉试试。具体可以搜索：*gradle排除依赖*。

如果不行，你可以通过`gradle [module-name]:dependencies --configuration implementation`查看哪些包出现了重复依赖，然后把有冲突的依赖过滤掉就可以了。
