### ISSUE TITLE
gradle 添加依赖 引入的 jar包，和当前的源码 并不一样

### ISSUE THREAD

**Issue by sjindong** [yanzhenjie/AndPermission#176]
加入 implementation 'com.yanzhenjie:permission:2.0.0-rc2'后 

，查看libs 下面的jar包， jar包源码，和 当前github上面源码 不一样

**Comment by yanzhenjie** [comment]
通过`jar`文件查看到的代码是as或者eclipse反编译class文件呈现出来，肯定和源代码是不一样的。`source jar`应该是一样的，你可以在`.gradle`文件中的`cache`下找到`jar`和`source jar`做验证。
