### ISSUE TITLE
连续调用权限问题

### ISSUE THREAD

**Issue by StephenYoungq** [yanzhenjie/AndPermission#181]
请求第一个权限以后, 回调了onGranted方法,在第一个权限的onGranted方法中继续请求第二个权限,这时第二个权限的回调不会执行,目前解决方法是在第一个方法的onGranted回调中延迟250毫秒左右再请求第二个权限

**Comment by wangyeming** [comment]
亲测，nexus 6p android 7.0 有该问题，同样250ms延迟请求第二组权限即可
