### ISSUE TITLE
拒绝权限不再提醒后后进入系统设置中立即返回

### ISSUE THREAD

**Issue by phypy** [yanzhenjie/AndPermission#183]
看了下源代码，里边多了个 FLAG_ACTIVITY_NEW_TASK，这个 flag 会导致 startActivityForResult 立即返回。

**Comment by yanzhenjie** [comment]
确实如此，能否提一个PR到dev分支。

**Comment by phypy** [comment]
已提交。

**Comment by SoStrongMan** [comment]
我也是遇到这个情况了，希望老大尽快改进
