### ISSUE TITLE
请问，AndPermission.with(this) 调用 申请权限 dialog，能不能在application 里面初始化？

### ISSUE THREAD

**Issue by MichaelZhang179** [yanzhenjie/AndPermission#184]
1 什么品牌的手机？ Google 原生模拟器
2 Android系统的版本是多少？7.1.0
3 是什么权限？   location 

好像不能吧？ dialog 必须依托在 activity ／fragment 上？ 不知道我理解的对不对，但是我们的工程代码
location 权限在 application 里面调用的，请问有什么方法吗？

**Comment by yanzhenjie** [comment]
不能，你可以在每次调用定位之前申请权限。但是你这个业务跟AndPermission关系不大，AndPermission传出来的那个`context`就是你传进去的那个`context`。
