### ISSUE TITLE
努比亚nx563j申请权限没弹出权限申请框，导致没有权限读取短信，代码如下

### ISSUE THREAD

**Issue by KentFeng** [yanzhenjie/AndPermission#186]
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            Request request;
            switch (index) {
                case 0:
                    request = AndPermission.with(mFragment);
                    break;
                case 1:
                    request = AndPermission.with(mActivity);
                    break;
                default:
                    request = AndPermission.with(VocApp.getInstance());
                    break;
            }
            request.permission(permissions)
//                    .callback(permissionListener)
                    .rationale(new Rationale() {
                        @Override
                        public void showRationale(Context context, List<String> permissions, final RequestExecutor
                                executor) {
                            // 拒绝授权
                            firstDenyDialog = DialogFactory.createTwoButtonDialog(VocApp.getInstance(), UIUtil
                                    .getString(R.string.ask_allow_permission), UIUtil.getString(R
                                    .string.ensure), UIUtil.getString(R.string.cancel), firstDenyTip, new View
                                    .OnClickListener() {
                                @Override
                                public void onClick(View v) {
                                    executor.execute();
                                    firstDenyDialog.dismiss();

                                }
                            }, new View.OnClickListener() {
                                @Override
                                public void onClick(View v) {
                                    executor.cancel();
                                    firstDenyDialog.dismiss();
                                }
                            });
                        }
                    })
                    .onGranted(new Action() {
                        @Override
                        public void onAction(List<String> permissions) {
                            // 同意授权
//                            getContractInfo();
                            if (grantInter != null) {
                                grantInter.onAgree();
                            }
                        }
                    })
                    .onDenied(new Action() {
                        @Override
                        public void onAction(List<String> permissions) {
                            if (AndPermission.hasAlwaysDeniedPermission(VocApp.getInstance(), permissions)) {
                                // 这些权限被用户总是拒绝。
                                final SettingService settingService = AndPermission.permissionSetting(VocApp
                                        .getInstance());
                                alwaysDenyDialog = DialogFactory.createTwoButtonDialog(VocApp.getInstance(), "",
                                        UIUtil.getString(R.string.dialog_live_cover_right),
                                        UIUtil.getString(R.string.cancel), alwaysDenyTip, new View
                                                .OnClickListener() {
                                            @Override
                                            public void onClick(View v) {
                                                settingService.execute();
                                                alwaysDenyDialog.dismiss();
                                            }
                                        }, new View.OnClickListener() {
                                            @Override
                                            public void onClick(View v) {
                                                settingService.cancel();
                                                alwaysDenyDialog.dismiss();
                                            }
                                        });
                            }
                        }
                    })
                    .start();`
targetSdkVersion也设为了23，报权限拒绝错误
 java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/inbox from pid=17492, uid=10385 requires android.permission.READ_SMS, or grantUriPermission()

**Comment by KentFeng** [comment]
唉，是我代码的问题。但是新问题是：初次打开app，会先走rationale回调，确定之后，再弹设置权限的对话框，这样对吗

**Comment by yanzhenjie** [comment]
麻烦先看一下文档：[http:yanzhenjie.github.io/AndPermission](http:yanzhenjie.github.io/AndPermission)
