### ISSUE TITLE
华为p8 Android5.0.2 emui 3.1 获取联系人权限，无论禁止还是允许都会回调权限获取成功

### ISSUE THREAD

**Issue by itwen** [yanzhenjie/AndPermission#187]

**Comment by yanzhenjie** [comment]
在5.x平台，对于**获取联系人**权限，内部检查已经有权限时，会尝试获取一条联系人，如果不报错就认为获取成功，你可以直接执行获取联系人的代码了。

有一个例外就是，当用户手机中联系人列表是空，就算没权限有的手机也不会报错，当然你获取时也不会报错，所以你可以放心获取。

另外，内部对`onGranted()`加了`try catch`，如果报错了会回调到`onDenied()`，这是为了兼容某些权限（例如电话）不能直接执行有权限时的代码而让开发者直接执行，报错即认为没有权限。当然需要开发者保证自己的代码不报除了没权限意外的其它异常。

**Comment by yanzhenjie** [comment]
No responsed, close.
