### ISSUE TITLE
OPPO A57(6.0.1) 不弹出权限请求 dialog，并且会直接调用 onGranted 的代码

### ISSUE THREAD

**Issue by phypy** [yanzhenjie/AndPermission#189]
发现情况不止是2.0，我测试了下 andpermission 1.0 的版本，发现也是这样的情况
感觉oppo的权限管理系统像是一坨那啥 ...
 我继续调试下看看问题在哪...

**Comment by phypy** [comment]
测试另一台OPPO R9S（6.0.1） 也这样

**Comment by yanzhenjie** [comment]
这个文档有有提到，有些权限时不会弹出无法触发，建议你看一下文档，另外提问时按照文档要求来提，不然我这边不好排查问题。

**Comment by yanzhenjie** [comment]
:grin: 你没说时什么权限，我只能你没看文档啦。  
好几个权限应该都会出现，比如电话、短信，当我检测到有权限时，我不能真正的打一个电话或者发一条短信来验证有没有权限。比如短信和联系人，有的手机申请时不会弹出，但是真正读写短信或者联系人时它就会弹出申请框，我们在这里`try catch`一下就可以判断是否有权限了。

所以对于申请后并检测到有权限时，没法真正执行代码验证的权限，都是直接返回了结果，一般`onDenied()`不会有问题，所以在`onGranted()`中怕是误通知了结果，就`try catch`了一下，你可以直接执行你的代码了。

另外比如定位权限，有的手机上执行了就能检测是否有权限，但是魅族上就算没权限也不会报错。实际场景中，申请权限时默认通过了，返回给开发者，开发者直接执行代码，弹出深情况，同意后代码继续执行，不同意代码不执行，或者报错重新回归到`onDeined()`中，都不会出现App崩溃或者异常情况。例如上述不报错的情况下，用户拒绝了权限没报错，App也没获取到定位信息（一般第三方SDK返回超时或者失败），他也知道应用不能继续运行了，所以我觉得应该时合理的。

**Comment by phypy** [comment]
明白了，谢谢大大解读 ~

**Comment by yanzhenjie** [comment]
不用客气，也不是我一个人总结出来的。是群里很多小伙伴一起测试出来的，我只是把大家的思路用一个项目总结表达出来。根据上述情况你测试一下，应该还有会其它情况，目前遇到的所有国产机按照这个思路执行时全部兼容到了的，如果有其它情况，我们再来完善。

**Comment by phypy** [comment]
ok。
