### ISSUE TITLE
6.0一下获取通讯录权限有问题

### ISSUE THREAD

**Issue by renzhe20092584** [yanzhenjie/AndPermission#190]
什么品牌的手机？
  vivo
Android系统的版本是多少？
  5.1.1
是什么权限？
  获得通讯录权限 android.permission.READ_CONTACTS
大概描述你问题出现的场景。
  手动在设置里禁止了获取通讯录权限，运行demo是还是提示成功执行onGranted，但实际上是获得不到通讯录的

猜测
  6.0以下手机好像都有这个问题，魅族 6.0.0 测试也有这个问题

**Comment by yanzhenjie** [comment]
实际执行获取代码时，获取有没有报错或者获取到是null？

**Comment by renzhe20092584** [comment]
public void displayPhone(){
        ContentResolver resolver = this.getContentResolver();

        // 获取手机联系人
        Cursor phoneCursor = resolver.query(Phone.CONTENT_URI, null, null,
                null, null);

        if (phoneCursor != null) {
            if (phoneCursor.getCount() == 0) {
                phoneCursor.close();
               //如果禁止的执行这里
                return ;
            }
        }

@yanzhenjie

**Comment by renzhe20092584** [comment]
public void displayPhone(){
    ContentResolver resolver = this.getContentResolver();

    // 获取手机联系人
    Cursor phoneCursor = resolver.query(Phone.CONTENT_URI, null, null,
            null, null);

    if (phoneCursor != null) {
        if (phoneCursor.getCount() == 0) {
            phoneCursor.close();

            //禁止和手机联系人是空都会执行这里

            return ;
        }

    }
}
@yanzhenjie

**Comment by yanzhenjie** [comment]
这个就有点无奈了，我测试时也是这样子。因为通过检测的Api获取到也是有权限，所以就返回有权限了，目前我这边也没有好办法了，如果你们有检测的办法告之我一下，我加到源码中。

**Comment by renzhe20092584** [comment]
嗯好的 我们在研究研究，正常来说 6.0 的手机不会出现这个问题，但我们用魅族 6.0 的手机也有同样的问题

**Comment by yanzhenjie** [comment]
你可以看一下前面几个issue，我在内部检测的流程和设计原理。你如果拿到时0可以提示用户：没有获取到联系人或者没有获取联系人的权限，请您检查。类似这样的话，总归不会让App崩溃就行，绕过这个限制。

**Comment by yangghost** [comment]
华为6.0以下的获取通讯录的也是一样的.只能通过拿到0去判断提示用户.不能确定到底是没有权限还是有权限但是通讯录里面没人.不过总归APP不会崩溃就OK了.

**Comment by yanzhenjie** [comment]
这个问题确实没有太好的办法，根据我们上述的总结，AndPermission目前能保证App不会崩溃，App可以按照正常流程跑。大家可以再提供一些好的办法，这个issue就暂时不关闭了。
