### ISSUE TITLE
360手机跳转的不是权限设置界面

### ISSUE THREAD

**Issue by renzhe20092584** [yanzhenjie/AndPermission#191]
什么品牌的手机？
 奇虎360
Android系统的版本是多少？
 5.1
是什么权限？
  设置权限界面
大概描述你问题出现的场景。
  跳转到的是应用详细信息界面，360手机权限设置是通过软件的，不能跳转到对应的权限设置界面，vivo手机同样是通过手机管理软件设置权限可以跳转过去，360的不行

**Comment by yanzhenjie** [comment]
这个可以解决，但是需要你告诉一些详细信息，还需要你在我改完之后做一些必要的测试，因为我这边没有这款手机。因为细节和调试起来挺繁琐，用github交流的话效率很低，所以麻烦你加一下我的QQ，我们详细聊一下：757699476。

**Comment by yanzhenjie** [comment]
No responsed, close.
