### ISSUE TITLE
nexus 9  select grant or delay always enter the onDenied 

### ISSUE THREAD

**Issue by xiangyuan** [yanzhenjie/AndPermission#193]
.onDenied(new Action() {
					@Override
					public void onAction(@NonNull final List<String> permissions) {
						isPermissionSuccess = false;
                        List<String> permissionNames = transformText(getApplicationContext(), permissions);
                        String message = AppActivity.this.getString(R.string.message_permission_rationale, TextUtils.join("\n", permissionNames));
						if (AndPermission.hasAlwaysDeniedPermission(AppActivity.this, permissions)) {

**Comment by yanzhenjie** [comment]
Have you checked the documentation? Some permissions are like this.

**Comment by yanzhenjie** [comment]
No responsed, close.
