### ISSUE TITLE
锤子手机 Android7.1.1系统运行权限默认都提示通过（不提示开关权限提示框）

### ISSUE THREAD

**Issue by hackzhang** [yanzhenjie/AndPermission#194]

**Comment by ListenerGao** [comment]
我的测试机坚果pro2 型号：OD103，系统版本：7.1.1，请求权限也是这种问题，不会弹框，直接走的时onGranted回调，但在设置页查看权限，权限是未授予的。

**Comment by yanzhenjie** [comment]
在有些国产机上，申请权限时系统返回的总是有权限，对于通讯录、读写SD卡等权限，AndPermission的策略是拿到有权限的结果后，再执行一下读取一条通讯录或者向SD卡写入一个文件来验证是否真的有权限。但是对于拨打电话此类权限，AndPermission不能真的去拨打一个电话，因此直接回调了`onGranted()`，开发者可以在`onGranted()`中直接拨打电话，来配合AndPermission申请权限，如果有就自然拨打出去了，如果没有权限，上述手机会弹出授权对话框或者抛出异常，如果抛出异常，AndPermission会重新回调到`onDenied()`方法，开发者即可认为是没有权限。

提问时请先阅读文档：   
* [特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)
* [提问](http://yanzhenjie.github.io/AndPermission/cn/issue.html)

**Comment by wsty** [comment]
vivo x9s也有该问题，demo所有权限申请都回调onGranted()，没有弹框
断点发现代码没有执行 **拿到有权限的结果后，再执行一下读取一条通讯录或者向SD卡写入一个文件来验证是否真的有权限** ，也没有在**start方法**找到相关代码

config.gradle中version为**2.0.0-rc4**

**Comment by yeming1001** [comment]
Vivo X20A 也是该问题，不管是询问还是禁止了，所有权限申请都走onGranted()提示授权成功。
库版本：2.0.0-rc4

**Comment by yanzhenjie** [comment]
@wsty @Reallym404 发布了2.0.0-rc6版本，对这个问题尝试进行了修复，你们用新版本看看。

**Comment by bingzhao0719** [comment]
请问一下锤子手机 Android7.1.1 的有人成功适配了吗？在设置里关掉权限，检测的时候还是通过的问题，魅族MX6也有这个问题

**Comment by clunyes** [comment]
如果是相机拍摄权限怎么办

**Comment by relish-wang** [comment]
> 在有些国产机上，申请权限时系统返回的总是有权限，对于通讯录、读写SD卡等权限，AndPermission的策略是拿到有权限的结果后，再执行一下读取一条通讯录或者向SD卡写入一个文件来验证是否真的有权限。但是对于拨打电话此类权限，AndPermission不能真的去拨打一个电话，因此直接回调了`onGranted()`，开发者可以在`onGranted()`中直接拨打电话，来配合AndPermission申请权限，如果有就自然拨打出去了，如果没有权限，上述手机会弹出授权对话框或者抛出异常，如果抛出异常，AndPermission会重新回调到`onDenied()`方法，开发者即可认为是没有权限。
> 
> 提问时请先阅读文档：
> 
> * [特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)
> * [提问](http://yanzhenjie.github.io/AndPermission/cn/issue.html)

文档地址失效了
