### ISSUE TITLE
8.0权限问题很严重，急急急！！！

### ISSUE THREAD

**Issue by chenenqiang12345** [yanzhenjie/AndPermission#195]
权限申请成功，但始终 无法正常回调，并且会出现ANR！！！问题很严重，急需处理！！！

**Comment by yanzhenjie** [comment]
根据你提供的信息我也无法判断问题和提供任何帮助于你，麻烦你看一下文档，然后再提问。

**Comment by yanzhenjie** [comment]
No responsed, close.
