### ISSUE TITLE
申请没在manifest中注册的权限时,能否直接抛异常

### ISSUE THREAD

**Issue by LambdaV5** [yanzhenjie/AndPermission#196]

**Comment by LambdaV5** [comment]
如果在oncreate方法中申请权限,manifest中注册过的已经全部同意,下一次打开时因为有未在manifest中注册的权限,导致onresume执行两次,进而导致activity切换动画异常

**Comment by yanzhenjie** [comment]
这...我也没太好的办法，只能劳烦你注册一下了。
