### ISSUE TITLE
判断总是拒绝情况针对360手机系统有问题

### ISSUE THREAD

**Issue by tupobi** [yanzhenjie/AndPermission#197]
首先，如果只是申请权限，暂时没有真正用到权限功能的情况下（如读联系人），不论真机还是模拟器都一直走deny方法。
其次，真正使用该权限后，360系统手机连续弹出两三次申请权限，这可能是360系统问题，但是并没有点不再提醒，这样的话也会进入has always deny的判断分支。模拟器上完全OK，但是模拟器没有出现连续弹出请求权限对话框的情况。是不是这个判断仅仅是大于两次拒绝就成立了？
模拟器是API26，360手机基带版本Android7.1.1

**Comment by yanzhenjie** [comment]
1. 一直走`denied()`时你的操作是什么。2. 走deny还会调用有权限的代码吗？如果是`granted()`后调用了权限代码，在360手机上应该也只会走一次申请权限，你可以再看看文档对国产机这一块的特殊说明。

**Comment by yanzhenjie** [comment]
No responsed, close.
