### ISSUE TITLE
回调问题

### ISSUE THREAD

**Issue by Hao-Kid** [yanzhenjie/AndPermission#2]
获取相机权限
用的是注解回调
点击不在提醒并且拒绝,
多次点击后,
会调用成功的方法

**Comment by yanzhenjie** [comment]
理论上应该不存在，我建议你试试listener的方式测试下。
你的代码可以截图发出来一下麽？最好能附上测试打印的log，谢谢。

**Comment by yanzhenjie** [comment]
今天发布了新版，兼容了国产机，新版功能更加强大，兼容性很好，可以看看ReadMe，谢谢指导。
