### ISSUE TITLE
Android  8.0"android.permission.READ_LOGS"权限直接拒绝

### ISSUE THREAD

**Issue by gemgao** [yanzhenjie/AndPermission#200]
今天加入了bugly的sdk，需要申请"android.permission.READ_LOGS"这权限，然后用的华为v9Android8.0系统，权限直接返回是拒绝的

**Comment by yanzhenjie** [comment]
返回是拒绝的就是拒绝的吧，从你的描述中看，似乎没什么不对啊。

**Comment by gemgao** [comment]
可是让我选择的框都没弹出来，，我都没选，直接走拒绝

**Comment by yanzhenjie** [comment]
刚才一次说嘛。没弹可能是你没用AndPermission之前申请过，就已经拒绝过了，你试试App完全重装申请，如果还是直接拒绝的，那就是系统行为，如果你必须要这个权限，你可以提示用户去设置中打开。

**Comment by gemgao** [comment]
额，我是重新把app安装第一次申请的，有可能是系统直接拒绝了，，谢谢你了

**Comment by yanzhenjie** [comment]
你也可以用AndroidSDK的Api申请看看，AndroidSDK的Api如果也不弹，那应该确定是系统行为了。

**Comment by gemgao** [comment]
额额，我试一下，结果出来我我在发这里

**Comment by gemgao** [comment]
测试完毕，，调用系统的也是直接拒绝，不是框架的问题，可能是系统不允许获取这个权限
