### ISSUE TITLE
使用SettingService的函数execute(int requestCode)  去设置权限后返回程序 无法接到回调？

### ISSUE THREAD

**Issue by xjhh** [yanzhenjie/AndPermission#201]
我的是小米6  Android 8.0   在用户拒绝权限后  使用对话框提示用户去设置开启  使用SettingService的函数execute(int requestCode)  去设置权限后返回程序 在onActivityResult中接收不到回调

**Comment by yanzhenjie** [comment]
你是使用的哪个版本，2.0.0-rc2版本有这个问题，是因为加了`NEW_TASK`这个flag，在2.0.0-rc3版本修复了这个问题。如果是最新版还有这个问题，是因为部分手机不回调，这是手机行为决定的。

**Comment by xjhh** [comment]
刚刚试了下2.0.0-rc3  还是不回调    还有个问题  我想在用户拒绝开启权限后  第二次进入程序时  弹出权限申请框并且还有不再提醒的复选框  该怎样实现呢   我的代码是这样的
AndPermission.with(this)
                .permission(permissions)
                .rationale(new Rationale() {
                    @Override
                    public void showRationale(Context context, List<String> permissions, RequestExecutor executor) {
                        permissionflag = false;
                        showPermissionDialog();
                    }
                }).onGranted(new Action() {
                    @Override
                    public void onAction(List<String> permissions) {
                        permissionflag = true;
                    }
                }).onDenied(new Action() {
                    @Override
                    public void onAction(List<String> permissions) {
                        permissionflag = false;
                        showPermissionDialog();
                    }
                }).start();`

**Comment by yanzhenjie** [comment]
在原生模拟器没有任何问题的。但是在国产机，各个厂家的权限策略都不同，有的没有不再提示选框。上面说的那个问题也是因为这个原因。

**Comment by xjhh** [comment]
好的   谢谢了

**Comment by NeVaDaAAA** [comment]
我这边也接收不到回调
版本：2.0.0-rc3
机型：一加3（A3000）
系统：Android 8.0

**Comment by yanzhenjie** [comment]
AndPermission2.0版本中，在启动`SettingActivity`添加了`NEW_TASK`的`flag`，导致无法在`onActivityResult()`中接受回调，在rc3中已经修复了这个问题，还有部分手机收不到回调可能因厂商而异。

另外刚刚发布了2.0.0-rc4，大家可以试用。

**Comment by ruan7k** [comment]
ContextSource 下面的startActivityForResult 是不是写错了 传入的 requestcdoe 没有使用 还是走的 startActivity 方法
