### ISSUE TITLE
关于跳转到系统设置的授权界面后，用户还是未授权就直接返回App的问题

### ISSUE THREAD

**Issue by imyyq-star** [yanzhenjie/AndPermission#204]
手机：Nexus 6p
系统：8.0
权限：读写sd卡

问题：
我在Launcher界面去请求权限，用户拒绝了，并去到了系统设置中的授权界面，可能用户来到这个界面后又不想授权了，于是点击返回键回到了App，此时App停留在Launcher，请问这种情况AndPermission有处理的建议吗？

**Comment by yanzhenjie** [comment]
开启设置界面时不是有一个带code的吗，你可以在`onActivityResult()`中接受。

**Comment by yanzhenjie** [comment]
No responsed, close.

**Comment by imyyq-star** [comment]
![image](https://user-images.githubusercontent.com/11580876/38669281-879c6e04-3e78-11e8-8abb-9ac081829be8.png)

2.0.0-rc4，有代码错误。

**Comment by imyyq-star** [comment]
导致SettingService的execute(int requestCode);无法正确响应Activity的onActivityResult

**Comment by yanzhenjie** [comment]
启动Setting必须使用`Activity`、`ActivityContext`或者`Fragment`，不能使用`ApplicationContext`。需要接受`result`必须使用`Activity`或者`Fragment`。另外请不要在已关闭的issue下继续提问，可以发布一些有帮助的方案，这或许对其他人有用。
