### ISSUE TITLE
权限库在Android8.0系统上的问题

### ISSUE THREAD

**Issue by YangShaoXiong** [yanzhenjie/AndPermission#207]
在8.0系统以下都正常，但是在8.0上出现了以下问题：
当权限对话框弹了出来，我也一一允许授权了，也走了onGranted()的成功回到方法，但是在最后又会自动弹出
![](http://ww1.sinaimg.cn/mw690/bcb60a8dly1fpegq3rfj8j20el0bu76i.jpg)
这个对话框，这个对话框按理应该是我拒绝权限时走了onDenied()方法才会出现的提示。但是现在，在我完全通过所有权限的授权时出现了，我确定直走了onGranted()的方法回调。我的请求方法见下图
![](http://ww1.sinaimg.cn/mw690/bcb60a8dgy1fpegtqxvutj20ws0df75d.jpg)
麻烦作者有时间看下这个问题。提前谢谢了。祝工作愉快。

**Comment by yanzhenjie** [comment]
请参考[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)。
