### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wenchaosong** [yanzhenjie/AndPermission#209]
java.lang.RuntimeException:Unable to start activity ComponentInfo{com.bb.wallet/com.yanzhenjie.permission.PermissionActivity}: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
-- 
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2872)
3 ......
4 Caused by:
5 android.view.WindowManager$BadTokenException:Unable to add window -- token null is not for an application
6 android.view.ViewRootImpl.setView(ViewRootImpl.java:816)
7 android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:361)
8 android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
9 android.app.Dialog.show(Dialog.java:328)
10 android.app.AlertDialog.show(AlertDialog.java:1245)
11 com.yanzhenjie.a.a$d.a(AlertDialog.java:142)
12 com.yanzhenjie.a.a$a.c(AlertDialog.java:602)
13 com.yanzhenjie.permission.k.a(RationaleDialog.java:94)
14 com.bb.lib.component.main.c$11.a(WelcomeActivity.java:198)
15 com.yanzhenjie.permission.d.a(DefaultRequest.java:141)
16 com.yanzhenjie.permission.PermissionActivity.onCreate(PermissionActivity.java:65)
17 android.app.Activity.performCreate(Activity.java:6765)
18 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)

调用代码

AndPermission.with(getApplicationContext())
                .requestCode(1)
                .permission(Manifest.permission.ACCESS_COARSE_LOCATION,
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.READ_EXTERNAL_STORAGE)
                .rationale(new RationaleListener() {
                    @Override
                    public void showRequestPermissionRationale(int requestCode, Rationale rationale) {
                        AndPermission.rationaleDialog(getApplicationContext(), rationale).show();
                    }
                })
                .callback(listener)
                .start();

andpermission 版本 1.1.0

**Comment by yanzhenjie** [comment]
不能使用`getApplicationContext()`，这个不是AndPermission的问题哦。

**Comment by wenchaosong** [comment]
不对吧，我用的是之前  1.1.0 的版本，当时好像就是说这么用的
