### ISSUE TITLE
魅族MX6和oppo R8207测试失败

### ISSUE THREAD

**Issue by xiaolongwuhpu** [yanzhenjie/AndPermission#21]
1.魅族MX6  andorid6.0版本,测试失败,直接下载严神demo,在我的手机上无法弹出对话框,而是直接弹出toast,说权限申请成功,但是其实没有成功,我去设置中心查看权限,(允许,询问,拒绝),显示的是---询问.
2.oppo R8207 android4.4.4 前两种点击效果和魅族MX6一样,只弹toast说成功,但是实际上并没有成功,    选择第三种listener方式时发现永远都是权限申请失败的弹框.
希望大神可以跟踪一下,或者加我qq我提供机器测试:1179917630

**Comment by yanzhenjie** [comment]
Android系统是多少，这个权限管理指的是6.0的运行时权限。And有的国产手机有这个bug，没有权限，判断的时候提示我们有权限。

**Comment by xiaolongwuhpu** [comment]
魅族是6.0的, oppo是4.4.4的

**Comment by yanzhenjie** [comment]
http://blog.csdn.net/yanzhenjie1003/article/details/52503533这是我博客讲6.0运行时权限的，你用原生的代码检查下，是否拥有这个权限，如果原生代码检查出来也是有，那就没办法了，是手机bug。

**Comment by Liuyaowu** [comment]
没错，在红米Note4手机上也是这样的，设置定位权限时询问，但是点击的时候提示获取权限成功，看起来应该是手机系统的问题，因为我同样的把日历设置成询问就会弹出系统的提示框出来，定位却不会，而且我测试过高德地图关于权限的那个示例Demo，也是这样的，DT

**Comment by xiaolongwuhpu** [comment]
@Liuyaowu  是啊,我也在找有没有好的方案,如果有好的方案了麻烦通知一下,谢谢

**Comment by yanzhenjie** [comment]
Uncontrollable factors, close.
