### ISSUE TITLE
导入项目，包会冲突，应该是V7或者其他包引用问题，如果lib里能不引用这些包就最好了。

### ISSUE THREAD

**Issue by xiaofengandroid** [yanzhenjie/AndPermission#213]
Error:Execution failed for task 
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by yanzhenjie** [comment]
只引入了`fragment`，没有`compat`和其它`support`包，如果你不需要可以过滤掉。
