### ISSUE TITLE
多线程多处发起无回调错误

### ISSUE THREAD

**Issue by cuiweijie** [yanzhenjie/AndPermission#217]
1.不支持多线程
public class AndPermission {

     // 此处单例，导致不支持多线程
    private static final RequestFactory FACTORY;

    static {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            FACTORY = new MRequestFactory();
        } else {
            FACTORY = new LRequestFactory();
        }
    }
}
2.多线程发起被覆盖
public final class PermissionActivity extends Activity {

     // 此处静态导致发起多次导致首次发起的回调接口被覆盖，建议此处改为队列模式
    private static PermissionListener sPermissionListener;

    public static void requestPermission(Context context, String[] permissions, PermissionListener permissionListener) {
        sPermissionListener = permissionListener;
        ......
    }

}

**Comment by yanzhenjie** [comment]
不支持并发调用，只能主线程申请，同时只能发起一个权限请求。
