### ISSUE TITLE
授权成功与否都走.onDenied（）方法？！

### ISSUE THREAD

**Issue by Cazaea** [yanzhenjie/AndPermission#219]
## 测试硬件信息

1. 华为P10 4G+64G，全网通，Android 8.0
2. 魅族Pro7 Plus 6G+64G，全网通，Android 7.0

## 测试环境

1. 应用Debug版本，Release版本
2. 模板应用，从首页点击按钮，携带Url参数，通过路由跳转到集合了腾讯TBS的本地WebActivity.

### 第一次，每项权限的申请，都禁止（走了.onDenied（）方法，权限总被拒绝，弹框提示）

![default](https://user-images.githubusercontent.com/16607724/38069017-c147c9d8-3346-11e8-861f-3315f70a2b5c.gif)

### 第二次，每项权限的申请，都允许（依然走了.onDenied（）方法，同样在权限总被拒绝，弹框提示）

![default](https://user-images.githubusercontent.com/16607724/38069030-d3f6ad74-3346-11e8-8757-32813b782fa5.gif)

### 第三次，每项权限申请都允许的情况下，进入应用权限设置，开通了所有权限，并且信任应用（依然走了.onDenied（）方法，同样在权限总被拒绝，弹框提示）

![default](https://user-images.githubusercontent.com/16607724/38069084-19499c4c-3347-11e8-9324-b87c07309fc4.gif)

## 下面，是我的代码逻辑

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // 权限申请
        permissionRequest(this);
    }

    /**
     * 是否允许开始授权
     */
    private Rationale mRationale = new Rationale() {
        @Override
        public void showRationale(Context context, List<String> permissions, final RequestExecutor executor) {
            // 默认用户允许授权
            executor.execute();
        }
    };

    /**
     * 权限申请
     */
    private void permissionRequest(final Context context) {

        // 权限提示弹框
        final SweetAlertDialog dialog = new SweetAlertDialog(context, SweetAlertDialog.NORMAL_TYPE)
                .setConfirmText("前往")
                .setCancelText("取消")
                .setTitleText("没有权限")
                .setContentText("需要您授予权限才能继续操作。");

        // 权限集合
        String[] permissions = new String[]{
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.ACCESS_FINE_LOCATION,
                Manifest.permission.CALL_PHONE,
                Manifest.permission.READ_LOGS,
                Manifest.permission.READ_PHONE_STATE,
                Manifest.permission.SET_DEBUG_APP,
                Manifest.permission.SYSTEM_ALERT_WINDOW,
                Manifest.permission.WRITE_APN_SETTINGS
        };

        // 动态申请权限
        AndPermission
                .with(this)
                .permission(permissions)
                .rationale(mRationale)
                .onGranted(new Action() {
                    @Override
                    public void onAction(List<String> permissions) {
                        // 当所有权限都拿到时，开始处理
                        if (dialog != null && dialog.isShowing()) {
                            dialog.dismiss();
                        }
                        Toast.makeText(WebActivity.this, "授权成功！", Toast.LENGTH_SHORT).show();

                    }
                })
                .onDenied(new Action() {
                    @Override
                    public void onAction(List<String> permissions) {
                        // 这些权限被用户总是拒绝。
                        if (AndPermission.hasAlwaysDeniedPermission(context, permissions)) {
                            // 这里使用一个Dialog展示没有这些权限应用程序无法继续运行，询问用户是否去设置中授权。
                            final SettingService settingService = AndPermission.permissionSetting(WebActivity.this);

                            dialog
                                    .setConfirmClickListener(new SweetAlertDialog.OnSweetClickListener() {
                                        @Override
                                        public void onClick(SweetAlertDialog sweetAlertDialog) {
                                            // 如果用户同意去设置：
                                            settingService.execute();
                                        }
                                    })
                                    .setCancelClickListener(new SweetAlertDialog.OnSweetClickListener() {
                                        @Override
                                        public void onClick(SweetAlertDialog sweetAlertDialog) {
                                            // 如果用户不同意去设置：
                                            settingService.cancel();
                                            sweetAlertDialog.cancel();
                                        }
                                    })
                                    .show();

                        }
                    }
                })
                .start();

    }

**Comment by yanzhenjie** [comment]
你在`onDeined()`和`onGranted()`中分别打印一下拒绝的和同意的权限看看，可能有某一个权限是获取不到的，当然不排除AndPermission是有问题的。还有在`onGranted()`中如果报错了也会回调到`onDenied()`中。
你的这个情况我会找机器继续测试排查。

**Comment by Cazaea** [comment]
#### 硬件信息

- 华为P10 4G+64G，全网通，Android 8.0

#### 无法获取到权限
       // 怀疑是异常报错走的onDeined()方法，毕竟有些权限您并未做处理
       Manifest.permission.READ_LOGS,
       Manifest.permission.READ_PHONE_STATE,
       Manifest.permission.SET_DEBUG_APP,
       Manifest.permission.SYSTEM_ALERT_WINDOW,
       Manifest.permission.WRITE_APN_SETTINGS

#### 我在[使用文档里](http://www.yanzhenjie.com/AndPermission/cn/explain.html)也看到了权限特殊说明：
“_一部分权限（例如发送短信、打电话、接听/挂断电话*等），AndPermission不能执行权限相关代码来判断或者强制申请。_”但是，我的应用又真真实实的拿到了打电话权限。

#### 上边的权限
通过 [**#218** ](https://github.com/yanzhenjie/AndPermission/issues/218)我知道您还没做 _SYSTEM_ALERT_WINDOW_ 处理，其他的，也是不支持吗？

或者您有当前依赖 _2.0.0-rc4_ 具体不支持适配的权限列表吗？

**Comment by yanzhenjie** [comment]
只支持运行时权限的申请。`SYSTEM_ALERT_WINDOW`和Android8.0安装权限后面打算加上。其它权限全部会回调`onGranted()`。
