### ISSUE TITLE
小米、华为、Oppo、魅族、Moto，以及Nexus、三星有什么区别？

### ISSUE THREAD

**Issue by fvaryu** [yanzhenjie/AndPermission#22]
我想知道这几种机型有什么区别呢 小米、华为、Oppo、魅族、Moto，以及Nexus、三星
厂商还修改了权限的实现？

**Comment by JYcainiao** [comment]
主要就是定制化的rom   有些厂商更改了较为底层的东西   然后就是屏幕密度和分辨率   适配要做好   其他的都大差不差  都是在android原生基础上  做的个性化

**Comment by bnjdhsjsw** [comment]
区别就是中华民族的不同民族
