### ISSUE TITLE
如果去设置里面开启了权限在哪里回调啊??

### ISSUE THREAD

**Issue by lxhtiamo** [yanzhenjie/AndPermission#221]
如果用户拒绝之后,提示去设置里面开启权限,,然后用户在设置里面开启了权限,回调在哪里???

**Comment by yanzhenjie** [comment]
如果你是with `Activity`或者`Fragment`，就在它们对应的`onActivityResult()`回调。

**Comment by ruan7k** [comment]
ContextSource 下面的startActivityForResult 是不是写错了  传入的 requestcdoe  没有使用 还是走的 startActivity 方法
