### ISSUE TITLE
小米4 android6.0.1系统 点击某些权限的拒绝或允许均闪退

### ISSUE THREAD

**Issue by UserWang** [yanzhenjie/AndPermission#223]
小米4 android6.0.1系统的手机跑sample，点击联系人、位置、电话、短信，弹出权限提示框，不管选择允许还是拒绝，页面都被关闭，其他权限如相机、日历、麦克风、存储等正常。
没有错误log。

**Comment by sanky-zhang** [comment]
我也有同样问题,跪求解决方法

**Comment by sanky-zhang** [comment]
@yanzhenjie

**Comment by sanky-zhang** [comment]
而且没有完全获取到权限  还是在询问的状态

**Comment by hhxi888** [comment]
小米4机子，系统Android 6.0.1  PermissionActivity中 requestPermissions(permissions, 1);执行之后没有任何反应，Activity中的requestPermissions方法根本没有执行到，请及时解决一下

**Comment by yanzhenjie** [comment]
题主的问题需要log。
@hhxi888 你这个描述，估计是调试了源码或者修改了源码吧，如果你没有改源码，那么肯定赶回调用`requestPermissions()`方法，至少会有回调`onRequestPermissionsResult`。

**Comment by hhxi888** [comment]
我调试了源码，真的没有log，onRequestPermissionsResult也没有执行到

**Comment by hhxi888** [comment]
04-27 16:07:25.820 12214-12214/com.cmri.universalapp E/TraceUtil: {Thread:main}trace: RelativeandFriend_AddFriend_Scan
04-27 16:07:25.831 12214-12214/com.cmri.universalapp I/Timeline: Timeline: Activity_launch_request time:1245231
04-27 16:07:25.848 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.cmri.universalapp.family.friend.view.AddFriendActivity onPaused <<<
04-27 16:07:25.883 12214-12214/com.cmri.universalapp I/AppCompatDelegate: The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
04-27 16:07:25.885 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity onCreated <<<
04-27 16:07:25.890 12214-12395/com.cmri.universalapp W/TraceIndexManager: [getNextEventIndex] | event index:|24
04-27 16:07:25.890 12214-12395/com.cmri.universalapp W/TraceBodyCreator: [addEventToBody]:{"7":"15","6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160725816","16":"RelativeandFriend_AddFriend_Scan","50":"unknown","17":"unknown","18":1,"62":"24"}
04-27 16:07:25.890 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [updateSumCount] current sum count:36
04-27 16:07:25.945 12214-12395/com.cmri.universalapp W/TraceBodyCache: [appendToBody] new add :{"7":"15","6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160725816","16":"RelativeandFriend_AddFriend_Scan","50":"unknown","17":"unknown","18":1,"62":"24"}
04-27 16:07:25.945 12214-12395/com.cmri.universalapp W/TraceBodyCache: [loadBody] start
04-27 16:07:25.946 12214-12395/com.cmri.universalapp W/TraceBodyCache: [loadBody] body: {"15":[{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160535545","16":"HostLocation","50":"0.0*0.0*GCJ-02","17":"unknown","18":1,"62":"16"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160537505","16":"LifeTab","50":"unknown","17":"unknown","18":1,"62":"17"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160538249","16":"HJQ_Xiaoxi_LoginStart","50":"2018-04-27 16:05:38","17":"","18":1,"62":"18"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160541472","16":"HJQ_Xiaoxi_LoginFinish","50":"2018-04-27 16:05:41","17":"200","18":1,"62":"19"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160546704","16":"VoipTab","50":"unknown","17":"unknown","18":1,"62":"20"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606593","16":"Voip_Plus","50":"unknown","17":"unknown","18":1,"62":"21"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606610","16":"UpperRightAddDevice","50":"unknown","17":"unknown","18":1,"62":"22"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606611","16":"Plus_icon","50":"unknown","17":"unknown","18":1,"62":"23"}]}
04-27 16:07:25.947 12214-12395/com.cmri.universalapp W/TraceBodyCache: [appendToBody] result body:{"15":[{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160535545","16":"HostLocation","50":"0.0*0.0*GCJ-02","17":"unknown","18":1,"62":"16"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160537505","16":"LifeTab","50":"unknown","17":"unknown","18":1,"62":"17"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160538249","16":"HJQ_Xiaoxi_LoginStart","50":"2018-04-27 16:05:38","17":"","18":1,"62":"18"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160541472","16":"HJQ_Xiaoxi_LoginFinish","50":"2018-04-27 16:05:41","17":"200","18":1,"62":"19"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160546704","16":"VoipTab","50":"unknown","17":"unknown","18":1,"62":"20"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606593","16":"Voip_Plus","50":"unknown","17":"unknown","18":1,"62":"21"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606610","16":"UpperRightAddDevice","50":"unknown","17":"unknown","18":1,"62":"22"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160606611","16":"Plus_icon","50":"unknown","17":"unknown","18":1,"62":"23"},{"6":"20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25","9":"20180427160725816","16":"RelativeandFriend_AddFriend_Scan","50":"unknown","17":"unknown","18":1,"62":"24"}]}
04-27 16:07:25.947 12214-12395/com.cmri.universalapp W/TraceBodyCache: [saveBody] start
04-27 16:07:25.952 12214-12395/com.cmri.universalapp W/TraceBodyCache: [saveBody] save body success
04-27 16:07:25.965 12214-12395/com.cmri.universalapp W/TraceIndexManager: [getNextActivityIndex]| activity index:|9
04-27 16:07:25.966 12214-12395/com.cmri.universalapp W/TraceManager: [updateAppStatusOnPause] cur activity:[com.cmri.universalapp.family.friend.view.AddFriendActivity,76672,20180427160609175,9]
04-27 16:07:25.966 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] start [com.cmri.universalapp.family.friend.view.AddFriendActivity,76672,20180427160609175,9]
04-27 16:07:25.966 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] not uploading trace, append to statement file
04-27 16:07:25.966 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached activities:[com.cmri.universalapp.login.activity.SplashActivity,5121,20180427160531237,7];[com.cmri.universalapp.SmartMainActivity,28540,20180427160540239,8]
04-27 16:07:25.966 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached duration:33661
04-27 16:07:26.037 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [updateSumCount] current sum count:37
04-27 16:07:26.038 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}onCreateAnimator : --------------------------
04-27 16:07:26.039 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}onCreateAnimator: transit: 0  enter: true  nextAnim: 0
04-27 16:07:26.039 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}onCreateAnimator : nextAnim : 0
04-27 16:07:26.039 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}onCreateAnimator : scanPreview == null ? true
04-27 16:07:26.051 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityStarted --> ScanAndQrCodeActivity
04-27 16:07:26.052 12214-12214/com.cmri.universalapp W/TraceApplication: application[session] is foreground.
04-27 16:07:26.052 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityResumed --> ScanAndQrCodeActivity
04-27 16:07:26.053 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}isBackground importance = 100
04-27 16:07:26.053 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}tryShowUI continue. currentActivity = com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity@7f13781
04-27 16:07:26.053 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity onResumed <<<
04-27 16:07:26.055 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}ScanFragment{95494b0 #0 id=0x6f10068a scan} _> onResume: ------------------------------------
04-27 16:07:26.058 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] end [com.cmri.universalapp.family.friend.view.AddFriendActivity,76672,20180427160609175,9]
04-27 16:07:26.058 12214-12395/com.cmri.universalapp W/TracePauseRunnable: runpause time:1524816445847
04-27 16:07:26.059 12214-12395/com.cmri.universalapp W/TraceSessionManager: [isSessionTimeout] session not expired, old session.
04-27 16:07:26.059 12214-12395/com.cmri.universalapp W/TraceSessionManager: old session
04-27 16:07:26.059 12214-12395/com.cmri.universalapp W/TraceSessionManager: session id:20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25
04-27 16:07:26.109 12214-12214/com.cmri.universalapp I/Timeline: Timeline: Activity_launch_request time:1245508
04-27 16:07:26.124 12214-12214/com.cmri.universalapp D/ScanFragment: {Thread:main}onPause: ------------------------------------
04-27 16:07:26.124 12214-12214/com.cmri.universalapp W/InactivityTimer: PowerStatusReceiver was never registered?
04-27 16:07:26.124 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity onPaused <<<
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceIndexManager: [getNextActivityIndex]| activity index:|10
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceManager: [updateAppStatusOnPause] cur activity:[com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity,72,20180427160726052,10]
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] start [com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity,72,20180427160726052,10]
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] not uploading trace, append to statement file
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached activities:[com.cmri.universalapp.login.activity.SplashActivity,5121,20180427160531237,7];[com.cmri.universalapp.SmartMainActivity,28540,20180427160540239,8];[com.cmri.universalapp.family.friend.view.AddFriendActivity,76672,20180427160609175,9]
04-27 16:07:26.134 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached duration:110333
04-27 16:07:26.151 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [updateSumCount] current sum count:38
04-27 16:07:26.162 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] end [com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity,72,20180427160726052,10]
04-27 16:07:26.162 12214-12395/com.cmri.universalapp W/TracePauseRunnable: runpause time:1524816446124
04-27 16:07:26.167 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onCreated <<<
04-27 16:07:26.171 12214-12214/com.cmri.universalapp I/Timeline: Timeline: Activity_launch_request time:1245571
04-27 16:07:26.181 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityStarted --> PermissionActivity
04-27 16:07:26.181 12214-12214/com.cmri.universalapp W/TraceApplication: application[session] is foreground.
04-27 16:07:26.182 12214-12395/com.cmri.universalapp W/TraceSessionManager: [isSessionTimeout] session not expired, old session.
04-27 16:07:26.182 12214-12395/com.cmri.universalapp W/TraceSessionManager: old session
04-27 16:07:26.182 12214-12395/com.cmri.universalapp W/TraceSessionManager: session id:20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25
04-27 16:07:26.182 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityResumed --> PermissionActivity
04-27 16:07:26.183 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}isBackground importance = 100
04-27 16:07:26.183 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}tryShowUI continue. currentActivity = com.yanzhenjie.permission.PermissionActivity@48f65a6
04-27 16:07:26.183 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onResumed <<<
04-27 16:07:26.226 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onPaused <<<
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceIndexManager: [getNextActivityIndex]| activity index:|11
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceManager: [updateAppStatusOnPause] cur activity:[com.yanzhenjie.permission.PermissionActivity,45,20180427160726181,11]
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] start [com.yanzhenjie.permission.PermissionActivity,45,20180427160726181,11]
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] not uploading trace, append to statement file
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached activities:[com.cmri.universalapp.login.activity.SplashActivity,5121,20180427160531237,7];[com.cmri.universalapp.SmartMainActivity,28540,20180427160540239,8];[com.cmri.universalapp.family.friend.view.AddFriendActivity,76672,20180427160609175,9];[com.cmri.universalapp.family.friend.view.ScanAndQrCodeActivity,72,20180427160726052,10]
04-27 16:07:26.257 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus]cached duration:110405
04-27 16:07:26.274 12214-12214/com.cmri.universalapp W/TraceApplication: application[session] is foreground.
04-27 16:07:26.274 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityResumed --> PermissionActivity
04-27 16:07:26.282 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}isBackground importance = 100
04-27 16:07:26.282 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}tryShowUI continue. currentActivity = com.yanzhenjie.permission.PermissionActivity@48f65a6
04-27 16:07:26.282 12214-12214/com.cmri.universalapp D/CrashReport: >>> com.yanzhenjie.permission.PermissionActivity onResumed <<<
04-27 16:07:26.285 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [updateSumCount] current sum count:39
04-27 16:07:26.289 12214-12214/com.cmri.universalapp D/PushHandler: {Thread:main}onActivityStopped --> AddFriendActivity
04-27 16:07:26.298 12214-12395/com.cmri.universalapp W/TraceAppStatusCache: [appendToAppStatus] end [com.yanzhenjie.permission.PermissionActivity,45,20180427160726181,11]
04-27 16:07:26.298 12214-12395/com.cmri.universalapp W/TracePauseRunnable: runpause time:1524816446226
04-27 16:07:26.299 12214-12395/com.cmri.universalapp W/TraceSessionManager: [isSessionTimeout] session not expired, old session.
04-27 16:07:26.299 12214-12395/com.cmri.universalapp W/TraceSessionManager: old session
04-27 16:07:26.299 12214-12395/com.cmri.universalapp W/TraceSessionManager: session id:20180427160531438_02:00:00:00:00:00_14677915459507539AA11E10150E4B25

**Comment by hhxi888** [comment]
这是执行的时候输入 log

**Comment by yanzhenjie** [comment]
看一下这里的逻辑：
```java
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        invasionStatusBar(this);

        Intent intent = getIntent();
        String[] permissions = intent.getStringArrayExtra(KEY_INPUT_PERMISSIONS);

        if (permissions != null && sPermissionListener != null) {
            requestPermissions(permissions, 1);
        } else {
            sPermissionListener = null;
            finish();
        }
    }
```

这个Activity只能内部启动，如果是调用了AndPermission启动的话，你断点看一下这个地方哪个对象为空。

> 因为权限这个太蛋疼了，我没有那么多手机测试，很多地方都是大家一起帮忙测试出的场景才完善起来的。

**Comment by hhxi888** [comment]
还遇到一个问题，oppoR11和R15两个机子，把相机权限关掉之后，在进入应用提示有权限提示，仍然选择禁用，到应用具体调用相机的页面却没有提示，相机调用正常，这也是一个问题。

**Comment by yanzhenjie** [comment]
你可以先看看中文文档的特殊说明。

**Comment by yanzhenjie** [comment]
这个issue对应AndPermisison版本太低，请大家使用新版本，这个issue先关闭了。
