### ISSUE TITLE
VIVO手机权限问题及其思考

### ISSUE THREAD

**Issue by niezhangyu** [yanzhenjie/AndPermission#226]
您好，在VIVO X20上申请权限出现问题。我要申请的读取联系人权限，当我拒绝权限后第二次操作，VIVO系统还是会执行onGranted，而这个onGranted其实是虚假的，我并不会真正的取回来联系人的电话号码。我读您的源码发现，您一般采用的StandardChecker模式调用的是AppOpsManager获取权限的方法，但这种方法在vivo是不行的，默认就是true。而StrictChecker模式只有StandardChecker返回false才进行。于是，我修改了您的代码，直接用StrictChecker模式，可是依然失败。在StrictChecker模式中，您使用cursor是否为空或者是否抛异常来判断是否拥有权限，但在VIVO手机上这两者都不会发生。所以我直接采用了判断cursor.getCount()是否为0来判断我是否获得权限。最终，用这个我拿到了是否真正拥有vivo的权限。但是，这么搞我个人觉得还是有很大隐患的，比如用户联系表就是为空等情况。说的很啰嗦，不知道各位有没有更好的办法来解决手机系统直接在你申请权限拒绝后第二次操作的时候返回虚假的true？

**Comment by cervy** [comment]
好奇vivo获取权限时返回真实的 true

**Comment by niezhangyu** [comment]
@yanzhenjie 您指的什么？看过

**Comment by niezhangyu** [comment]
@cervy 谢谢回复 您没有问题吗？好像我描述有误，我这里直接就可以进联系人列表了  然后在联系人列表里弹框申请权限    如果这个时候拒绝了 我下次还是可以进联系人列表 而没有任何提示 如果debug的话 这个时候走的还是onGranted

**Comment by yanzhenjie** [comment]
你的描述我认真看了，一些关于源码的描述并不完全正确。
关于利用`cursor`判断是否有权限这个目前只能做到非空和能读这个维度，因此还需要开发者真正的执行**权限相关代码**来辅助整个流程，这一点在文档中有提到。你结合文档再调试确认一下是否可以最大兼容度上走完整个流程。

**Comment by niezhangyu** [comment]
@yanzhenjie 嗯，的确，对源码的理解应该是我只是大略走了下源码的流程吧。问题是在我拒绝权限后，第二次直接就执行onGranted方法了，因为这个时候cursor不为空也不会异常，AppOpsManager也没起作用。以至于我无法判断用户是否拒绝了权限。所以我去判断了cursor.getCount

**Comment by yanzhenjie** [comment]
走到`onGranted()`的时候你可以直接读取通讯录了，如果发生异常则回到`onDenied()`了，说明没有权限；如果没有发生异常，分两种情况，1是读取到联系人了，2是读到的`cursor`为null或者`count`为0，此时界面上就提示用户没有联系人或者无权限。
如果用户真的没联系人或者拒绝过国权，那么他心里应该是有数的。

**Comment by niezhangyu** [comment]
@yanzhenjie 您说的没错，只是更多的从产品角度解决吧，那看来只能这样了。VIVO我这边确实是当您拒绝了权限后下一次还是可以走onGranted的，这个有点神烦。谢谢，那我就先当count为0的时候提示用户吧。

**Comment by yanzhenjie** [comment]
不客气的，这个获取不到准确状态也是没办法。
