### ISSUE TITLE
nubia Z9 max android5.1.1申请WRITE_EXTERNAL_STORAGE 一直onDenied

### ISSUE THREAD

**Issue by liangAndroid** [yanzhenjie/AndPermission#227]

**Comment by yanzhenjie** [comment]
你的问题描述不够详尽，也许你本身就没权限。另外你是否结合文档说明调试过。[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)

**Comment by liang203tian** [comment]
手机设置和手机管家中应用权限都是允许的 手机存储空间足够 sdcard存储提示没有插入
代码执行时 StorageWriteTest.test()  中 file.delete() return false  且 adb shell进入sdcard中 rm 提示rm: ANDROID.PERMISSION.TEST: Permission denied

**Comment by liang203tian** [comment]
并且在系统app文件管理中找到该文件并删除提示成功，但刷新后还是存在。

**Comment by yanzhenjie** [comment]
这样看来是这个手机无法删除文件。AndPermission测试不能删除，所以判断没有可写权限。

**Comment by liang203tian** [comment]
可以兼容这种情况吗？

**Comment by yanzhenjie** [comment]
你是否有兼容方案，我觉得无法判断。
