### ISSUE TITLE
vivo神机onGranted()和onDenied()都走

### ISSUE THREAD

**Issue by luochengsc** [yanzhenjie/AndPermission#230]
![qq 20180412200028](https://user-images.githubusercontent.com/38318618/38676120-9cb48e20-3e8c-11e8-90d0-68b5dab33e6a.jpg)
@yanzhenjie 就这货，权限已经给了，每次都还是要把两个方法都走一遍，先走onGranted()再走onDenied()

**Comment by yanzhenjie** [comment]
你的`onGranted()`代码有异常。

**Comment by yongli991581716** [comment]
vivo x9拒绝权限后  却走了onGranted()回调，求解

**Comment by yanzhenjie** [comment]
@yongli991581716 你可以先看一下文档。

**Comment by yanzhenjie** [comment]
@yongli991581716 目前想到的所有建议都写到文档中了，建议认真看一下文档[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)。

**Comment by luochengsc** [comment]
@yanzhenjie 确认过，onGranted()里面代码是没问题的，在其他机型真机测试，也没出现问题

**Comment by luochengsc** [comment]
@yongli991581716 一部分设备上使用SDK的Api判断是否有权限时总是返回true，因此需要执行权限相关代码根据是否抛出异常来判断是否真正有权限。

**Comment by Xanthuim** [comment]
实话说吧，有些手机厂商把权限改的一塌糊涂，根本不是按照谷歌权限一套走的，不管你怎么封装都是徒劳。所有有的手机就放弃，没必要折腾。

**Comment by yanzhenjie** [comment]
@luochengsc 你可以看一下源码，不可能两个方法都回调。
