### ISSUE TITLE
大神，调用AndPermission.hasAlwaysDeniedPermission()方法会使宿主Activity走OnPause与OnResume方法，这是正常的吗？

### ISSUE THREAD

**Issue by TianXuanL** [yanzhenjie/AndPermission#232]
if (AndPermission.hasAlwaysDeniedPermission(MainActivity.this, permissions)) {
//                            mSetting.showSetting(permissions);
                        }
把弹调转去设置的dialog去掉，也会走OnPause与OnResume方法

**Comment by yanzhenjie** [comment]
就是个普通判断，不会导致你的宿主`Activity`走`onPause()`和`onResume()`。

**Comment by TianXuanL** [comment]
我就在你给的demo中测了，只要调用AndPermission.hasAlwaysDeniedPermission(MainActivity.this, permissions)这是方法就会走onPause()和onResume()方法的，不知道原因是什么

**Comment by yanzhenjie** [comment]
你用的是哪个版本？

**Comment by TianXuanL** [comment]
就是最新的2.0.0-rc4版本
![default](https://user-images.githubusercontent.com/38403108/39568393-b06dad20-4ef4-11e8-80e0-6edd1be59724.png)

**Comment by JeremyLeeL** [comment]
如果在activity 的 onResume中做权限申请，然后用户选择拒绝并不再提醒，那么恭喜你，onResume将被无限调用

**Comment by zgxzgxzg** [comment]
@JeremyLeeL 碉堡了

**Comment by taoyuanxiaoqi** [comment]
确实存在这种问题，苦恼中
