### ISSUE TITLE
国际化语言的怎么修改

### ISSUE THREAD

**Issue by kakaaka** [yanzhenjie/AndPermission#235]
当用户拒绝了权限申请后
 public void showRequestPermissionRationale(int requestCode, Rationale rationale)
                    {                  	
                        AndPermission.rationaleDialog(mActivity, rationale).show();
                    }
提示的都是英文 比如： Permission denied
you have rejected us for anthorization, would you .....
还有:  Permission apply failure
we need some permissions are you refuse or system error, would you please go to Settings page,,,,

我们项目需要本地化，而且显示英文语法有些问题，咨询下如何能够让这些提示也国际化，适应不同的语言？谢谢
我对安卓这一块没用过哈，问题有点小白

**Comment by yanzhenjie** [comment]
看这些提示你似乎用的旧版本默认的提示语，这些你都可以自定义的在旧版本中。
新版中，同样的也没有限制提示语，只有一个地方，当权限被拒绝时想把拒绝的权限转换为相应的文本时，如果使用了AndPermission提供的方法，返回的文本是根据系统语言变化的。如果你想定死使用某个语言就使用自己的方法就行。

**Comment by yanzhenjie** [comment]
No response, close.
