### ISSUE TITLE
关于“Request”接口实现类中常量，是否改为临时创建会比较省内存？

### ISSUE THREAD

**Issue by zj565061763** [yanzhenjie/AndPermission#236]
大佬，你好，学习了你的源码，看到Request的时候有一些疑问，请教一下
“LRequest”和"MRequest"常量，是否改为需要的时候创建会比较省内存？这个权限请求好像一般不会非常频繁的触发

**Comment by yanzhenjie** [comment]
该类被加载到才会申请内存，无伤大雅哦！
