### ISSUE TITLE
增加一个RequestExecutor对像的返回

### ISSUE THREAD

**Issue by landerson85** [yanzhenjie/AndPermission#241]
不知道是机型还是什么问题，系统提示第一次权限申请的时候是没有“不再提示"，所以isShowRationalePermission的原因，所以rationale设置的监听是没办法调回的，这个就会引起一次问题：前端调用没有对像执行RequestExecutor.execute，所以建议对外扩展一个API出来以适应这个操作

**Comment by yanzhenjie** [comment]
是的，有的手机是不支持这个功能。
另外前端应该是调你的功能，这个是你这边申请完权限再往下走的吧，你说的这个情况我不太明白，目前我觉得是没有影响的。

**Comment by yanzhenjie** [comment]
No response, close.
