### ISSUE TITLE
ContextSource中函数调用错误导致onActivityResult函数不回调

### ISSUE THREAD

**Issue by fishwjy** [yanzhenjie/AndPermission#245]
机型：应该与机型无关
库版本：com.yanzhenjie:permission:2.0.0-rc4

文件：com.yanzhenjie.permission.source.ContextSource.java
public void startActivityForResult(Intent intent, int requestCode)函数中没有调用startActivityForResult将requestCode传进去。导致在APP中的Activity的回调函数接收不到返回。

另外，请教一下，这里修复之后，在APP的Activity回调函数中，想再次判断一下当前APP有没有我想要的哪个权限应该用什么函数呢？（因为有可能用户进到设置页面什么也没做就退回来了）
原来的版本有AndPermission.hasPermission(this, PERMISSION_LOCATION)，现在的没有了。谢谢🙏

![image](https://user-images.githubusercontent.com/10110651/39292140-d6edb72a-4967-11e8-9899-5b839dd71c51.png)

**Comment by fishwjy** [comment]
这里应该是笔误写漏了

**Comment by yanzhenjie** [comment]
如果使用`Context`的话是无法`startActivityForResult`的，新版会在里面加个判断是`Activity`的。如果需要你可以使用`Activity`和`Fragment`来请求权限。
后面判断权限这个我可以加一个，但是不准确的。

**Comment by fishwjy** [comment]
哦，明白了，需要使用public static SettingService permissionSetting(@NonNull Activity activity)或者fragment的版本来创建SettingService，亲测已经调用成功

关于判断权限这个，如果不准确的话，我现在是直接在onActivityResult里面再调用一下正常的请求权限流程，这样应该没啥问题吧？

**Comment by yanzhenjie** [comment]
这样的话如果用户在Setting中没有同意权限，还可能再次弹窗呢。我加一个吧，刚要发布就看到你这个issue了。

**Comment by fishwjy** [comment]
运气不错，多谢 😀
