### ISSUE TITLE
Dialog jar包没有啊

### ISSUE THREAD

**Issue by charles88** [yanzhenjie/AndPermission#25]
AndPermission.defaultSettingDialog(this,  PERMISSION_READ_PHONE_TYPE).show();

**Comment by yanzhenjie** [comment]
Dialog是使用的这个库，你可以引用这个库：
```
https://github.com/yanzhenjie/CompatAlertDialog
```
建议不要使用jar包，直接使用as gradle依赖，下个版本也不会提供jar包了。
