### ISSUE TITLE
WRITE_SETTINGS权限问题?

### ISSUE THREAD

**Issue by fcscr126608** [yanzhenjie/AndPermission#250]
你好，项目中需要使用亮度调整，所以需要WRITE_SETTINGS权限，但是Permission类中没有该权限，请问如何解决？

**Comment by yanzhenjie** [comment]
该权限不是运行时权限，不需要动态请求授权，只需要在`manifest.xml`中声明即可使用。
如果声明后调用功能时，某些设备报错了的话，你可以把设备品牌、Android系统版本和异常信息贴出来一下，我看看是否可以在AndPermission中做适配。
