### ISSUE TITLE
申请权限完成之后onGranted 之后又走了onDenied回掉，这是什么原因，我在应用信息里看了是又权限的

### ISSUE THREAD

**Issue by tx123456** [yanzhenjie/AndPermission#251]
这是申请权限的代码

AndPermission.with(getContext()).permission(Permission.ACCESS_COARSE_LOCATION, Permission.ACCESS_FINE_LOCATION)
                .rationale(new Rationale() {
                    @Override
                    public void showRationale(Context context, List<String> list, final RequestExecutor requestExecutor) {
                        new QMUIDialog.MessageDialogBuilder(getContext()).setTitle("提示")
                                .setMessage("检测到您未开启地理位置权限，是否现在开启")
                                .addAction("取消", new QMUIDialogAction.ActionListener() {
                                    @Override
                                    public void onClick(QMUIDialog dialog, int index) {
                                        dialog.dismiss();
                                        requestExecutor.cancel();

                                    }
                                }).addAction("确定", new QMUIDialogAction.ActionListener() {
                            @Override
                            public void onClick(QMUIDialog dialog, int index) {
                                dialog.dismiss();
                                requestExecutor.execute();
                            }
                        }).create().show();
                    }
                })
                .onGranted(new Action() {
                    @Override
                    public void onAction(List<String> list) {
                        LogUtils.i("申请权限成功");
                        mPresenter.initLocation();
                        startActivity();
                    }
                }).onDenied(new Action() {
            @Override
            public void onAction(List<String> list) {
                LogUtils.i("申请权限失败");
                if (AndPermission.hasAlwaysDeniedPermission(getContext(), list)) {
                    LogUtils.i("申请权限总是拒绝");
                    // 这些权限被用户总是拒绝。
                    DialogUtils.openSetting((Activity) getContext(),true);
                }else {
                    getPermissions();
                }
            }
        **}).start();**

这里是日志

04-29 00:20:03.237 26219-26219/com.lnh.sports I/SplashActivity:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.lnh.sports.modules.login.activity.SplashActivity$2.onAction(SplashActivity.java:107)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 申请权限成功
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
04-29 00:20:03.238 26219-26219/com.lnh.sports I/SplashActivity:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.lnh.sports.modules.login.activity.SplashActivity$1.onAction(SplashActivity.java:114)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 申请权限失败
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
04-29 00:20:03.239 26219-26219/com.lnh.sports I/SplashActivity:  
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ main, com.lnh.sports.modules.login.activity.SplashActivity$1.onAction(SplashActivity.java:116)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ 申请权限总是拒绝
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

这是手机的权限截图
![screenshot_2018-04-28-23-33-44-934_com miui secur](https://user-images.githubusercontent.com/14331075/39398690-edc6125c-4b43-11e8-8505-d3714e274b2d.png)

手机型号 小米note3

**Comment by yanzhenjie** [comment]
rc6已经发布，打印了异常信息。
