### ISSUE TITLE
权限单一太多，但系统权限又要细分的，所以请求时失败

### ISSUE THREAD

**Issue by landerson85** [yanzhenjie/AndPermission#252]
我在测试机红米NOTE5 上面测试发现个现象:
我申请一个PHONE的权限，但是andPermission的这个PHONE是包括了多个权限的，但是系统又针对这些权限能单独处理的，所以在申请时权限时，用户是同意了，但是项目还是返回了失败，因为有部份权限并没有得到允许或者说系统好像没有这个权限分类，个人建议是还是把一些权限再细分出去吧

**Comment by yanzhenjie** [comment]
是分开的。

**Comment by landerson85** [comment]
用户已经点了允许phone这个权限组的了，但还是返回错误，错误的权限列表如上图！但实际上系统提示的权限列表里并没有这些！
![1524988434 1](https://user-images.githubusercontent.com/2057410/39404425-87bb83ac-4bc5-11e8-830e-817119dffea2.jpg)

**Comment by yanzhenjie** [comment]
你好，文档中有提示需要什么权限就申请什么权限，详见[特殊说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)。  

你应该是调用了AndPermission申请权限组，如果你仅需要其中某一个权限，那么你申请某一个权限即可，AndPermission也仅仅会申请这一个权限。  

另当申请权限组时用户同意了权限但是回调了`onDenied()`，那么说明这个权限组中有权限需要用户手动去Setting中开启，这个流程也是没有问题的，目前这一现象只发现在中国大陆产品牌手机中。

**Comment by landerson85** [comment]
这一块我做了一些优化了：
中国的手机，因为有一些权限是在系统层就合并了（验证:就是我单独申请一个取读取通话记录，系统压根就不会提示权限申请），所以我现在做的做法是：还是按组的来申请，这时因为有一些权限系统是有的，这时再判断返回申请失败的权限与这个组的权限记录对比一下，如果少了，就证明用户给允许了，反之就是拒绝了

**Comment by yanzhenjie** [comment]
你好，你描述的这一点似乎和AndPermission没有关系，也没有表现最开始说的问题。
另外关于系统不显示权限申请的Dialog这一点，在文档中有讲到使用AndPermission时的做法。
