### ISSUE TITLE
target版本 22,Android系统8.0.0权限判断问题

### ISSUE THREAD

**Issue by xiuxiuing** [yanzhenjie/AndPermission#254]
target 22的APP，系统会默认授予Manifest中的权限，但是用户可以手动关闭权限，手动关闭权限后，判断权限错误。
public final boolean isShowRationalePermission(String permission) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return false;

        PackageManager packageManager = getContext().getPackageManager();
        Class<?> pkManagerClass = packageManager.getClass();
        try {
            Method method = pkManagerClass.getMethod("shouldShowRequestPermissionRationale", String.class);
            if (!method.isAccessible()) method.setAccessible(true);
            return (boolean) method.invoke(packageManager, permission);
        } catch (Exception ignored) {
            return false;
        }
    }

这个判断缺少了target版本的判断，如果target版本为22，系统版本大于23，是不会触发动态请求权限的，所以方法shouldShowRequestPermissionRationale 一直返回false，导致权限判断错误。

**Comment by yanzhenjie** [comment]
不会触发请求权限，这里返回false是没问题的呀。你的意思是？

**Comment by xiuxiuing** [comment]
这个MRequest的判断方法
public void start() {
        List<String> deniedList = getDeniedPermissions(CHECKER, mSource, mPermissions);
        mDeniedPermissions = deniedList.toArray(new String[deniedList.size()]);
        if (mDeniedPermissions.length > 0) {
            List<String> rationaleList = getRationalePermissions(mSource, mDeniedPermissions);
            if (rationaleList.size() > 0 && mRationaleListener != null) {
                mRationaleListener.showRationale(mSource.getContext(), rationaleList, this);
            } else {
                execute();
            }
        } else {
            callbackSucceed();
        }
    }

返回false之后，走了execute()请求权限的逻辑，但是target 22不会触发动态请求权限。
就目前的现象来说：我是Android8.0.0的系统，APPtarget 22，启动APP之后，我手动到应用设置关闭所有权限，但是判断结果是 成功。

**Comment by yanzhenjie** [comment]
按照规范来说，target22的话是认为有权限的呀。
因为部分国产机反正的状态是错的，就算有权限AndPermission也会执行实际代码检测是否真正的有权限，你可以按照文档中的[特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)往下走。

**Comment by xiuxiuing** [comment]
问题是这个onRequestPermissionsResult 返回的permissions是个空的
    @Override
    public void onRequestPermissionsResult(@NonNull final String[] permissions) {
        HANDLER.postDelayed(new Runnable() {
            @Override
            public void run() {
                List<String> deniedList = getDeniedPermissions(DOUBLE_CHECKER, mSource, permissions);
                if (deniedList.isEmpty()) {
                    callbackSucceed();
                } else {
                    callbackFailed(deniedList);
                }
            }
        }, 250);
    }
就导致了DoubleChecker的这两种检测方式没有走进来，
    private static List<String> getDeniedPermissions(PermissionChecker checker, @NonNull Source source, @NonNull String... permissions) {
        List<String> deniedList = new ArrayList<>(1);
        for (String permission : permissions) {
            if (!checker.hasPermission(source.getContext(), permission)) {
                deniedList.add(permission);
            }
        }
        return deniedList;  // deniedList 长度为0
    }

 List<String> deniedList = getDeniedPermissions(DOUBLE_CHECKER, mSource, permissions);
                if (deniedList.isEmpty()) {
                    callbackSucceed();  //回调成功了
                } else {
                    callbackFailed(deniedList);
                }

**Comment by yanzhenjie** [comment]
这个问题已经有人提出了，现在已经修复并发布在dev分支了，你可以切换到dev分支使用新版本。另外因为文档还未更新，所以暂时没有合并到master分支。

**Comment by xiuxiuing** [comment]
好的，谢谢，麻烦了

**Comment by yanzhenjie** [comment]
:smile: 已经更新了文档，并且代码也到master分支了。
