### ISSUE TITLE
小米 MI PAD 2 5.1 MIUI9.5 位置权限申请 查看权限已经允许情况下， 一直走拒绝的回调

### ISSUE THREAD

**Issue by PeanutZhang** [yanzhenjie/AndPermission#255]

**Comment by renjinlong** [comment]
我也有这个问题，怎么解决的  我的是vivox9   用的rc-11的版本

**Comment by yanzhenjie** [comment]
最近发生MIUI9.4.x版本，系统设置中的开关无效，你把App卸载，重新打开申请权限，点击同意看看是否能拿到权限。

**Comment by gyymz1993** [comment]
我也有这个问题，怎么解决的 我的是vivox9

**Comment by ayuhani** [comment]
@yanzhenjie 第一次申请授权，点击同意，还是走onDenied回调，此时设置里面已经开启了权限。
MI5 MIUI 9.6.1.0 Android 8.0.0

**Comment by LXLYHM** [comment]
我也有这个问题，请问怎么解决的？谢谢

**Comment by zjkgsqj** [comment]
mix miui10.2 android 8.0 点不再询问拒绝后，跳转系统的设置界面开启权限，再回到应用还是走Denied回调

**Comment by zjkgsqj** [comment]
> mix miui10.2 android 8.0 点不再询问拒绝后，跳转系统的设置界面开启权限，再回到应用还是走Denied回调

把开发者选项里的miui优化关闭就正常了
