### ISSUE TITLE
跳转设置页面时提示from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

### ISSUE THREAD

**Issue by zxyaust** [yanzhenjie/AndPermission#256]
SettingService settingService = AndPermission.permissionSetting(mContext);

    // 如果用户同意去设置：
    settingService.execute();

    // 如果用户不同意去设置：
    settingService.cancel();
这应该是个小问题,不过希望修正一下,谢谢

**Comment by zxyaust** [comment]
不好意思,应该是缓存问题,开始时每次都是这个问题,后续再没出现过,辛苦

**Comment by yanzhenjie** [comment]
是的已经修复了，发在dev分支下了，因为新版的文档还没写完，所以还未合并到master分支，你可以切换到dev分支下使用新版本。
