### ISSUE TITLE
master分支，demo，MeiZu M3 申请 - 读联系人（READ_CONTACTS）成功，但是其实是禁止了权限的

### ISSUE THREAD

**Issue by zgxzgxzg** [yanzhenjie/AndPermission#257]
问题浮现步骤：
（1）点击联系人，选取Read_Contacts，弹出对话框， 然后拒绝，居然tips成功
（2）再次，点击联系人，选取Read_Contacts，直接tips成功；
其实已经拒绝了，不应该成功的；（我看设置页面里面的权限也是禁止的）

![image](https://user-images.githubusercontent.com/13228580/39693148-a04c18a4-5215-11e8-876c-a7dd55c928b0.png)

**Comment by yanzhenjie** [comment]
这个文档有有提到，有些权限时不会弹出无法触发，建议你看一下文档，另外提问时按照文档要求来提，不然我这边不好排查问题。

好几个权限应该都会出现，比如电话、短信，当我检测到有权限时，我不能真正的打一个电话或者发一条短信来验证有没有权限。比如短信和联系人，有的手机申请时不会弹出，但是真正读写短信或者联系人时它就会弹出申请框，我们在这里`try catch`一下就可以判断是否有权限了。

所以对于申请后并检测到有权限时，没法真正执行代码验证的权限，都是直接返回了结果，一般`onDenied()`不会有问题，所以在`onGranted()`中怕是误通知了结果，就`try catch`了一下，你可以直接执行你的代码了。

另外比如定位权限，有的手机上执行了就能检测是否有权限，但是魅族上就算没权限也不会报错。实际场景中，申请权限时默认通过了，返回给开发者，开发者直接执行代码，弹出深情况，同意后代码继续执行，不同意代码不执行，或者报错重新回归到`onDeined()`中，都不会出现App崩溃或者异常情况。例如上述不报错的情况下，用户拒绝了权限没报错，App也没获取到定位信息（一般第三方SDK返回超时或者失败），他也知道应用不能继续运行了，所以我觉得应该时合理的。

**Comment by zgxzgxzg** [comment]
文档指的是这个 - http://www.yanzhenjie.com/AndPermission/cn/explain.html  对吗

**Comment by yanzhenjie** [comment]
没错，如果严格按照文档的逻辑走下来还有问题，AndPermission也没有其它更好的办法了。同时如果你有更好的办法也可以提供一下，我会加到源码里面 。

**Comment by zgxzgxzg** [comment]
好的，谢谢，这个问题我先关闭，打搅您了
