### ISSUE TITLE
onGranted()中的异常当做onDenied()处理

### ISSUE THREAD

**Issue by ofexe** [yanzhenjie/AndPermission#259]
当权限获取成功时，如果onGranted()中的代码有异常的话，现在的版本是当做权限获取失败来处理的，这种处理方式不太好。
如果有异常，应当抛出异常，让用户自己处理，希望能修改一下这一点。

**Comment by yanzhenjie** [comment]
你可以自己`try catch`，另外如果排除权限，你不应该保证你的代码不会异常麽。:yum:

**Comment by ofexe** [comment]
我已经自己try catch了。
我觉得你既然catch到了异常，理应继续把它抛出，这样可以强制开发者try-catch，减小debug的时间。否则对于新手的话，他们可能会纠结于权限的问题，以为是权限没有获取成功。
这里只是提出一个优化的意见，望采纳~

**Comment by yanzhenjie** [comment]
文档中已经明确写了。

有意见是很好的，不过这个设计应该不会改，而且涉及到很多使用者，你可以fork后自己修改源码，开源也就这点好。:smile:
