### ISSUE TITLE
老大 不管权限是否拿到只走 onSucceed 怎么办..... 

### ISSUE THREAD

**Issue by k354250377** [yanzhenjie/AndPermission#26]
什么情况下会这样啊... 不管有没有拿到权限都不会走rationale,直接走成功回调了

**Comment by k354250377** [comment]
定位到 问题了 不走onRequestPermissionsResult 里面的 AndPermission.onRequestPermissionsResult方法 这是什么原因啊

**Comment by yanzhenjie** [comment]
在首页有说明：
> 以下说明只针对部分国产手机：部分人反馈，申请时没有弹窗直接回调了拥有权限，而在系统的Setting中看到是没有这个权限的。这种情况，请直接调用相应功能，如果能正常调用，说明App是拥有权限的，所以是系统Setting的问题。如果申请时允许了权限，但是回调了失败，说明是系统发放权限失败，系统返回了失败，也是系统bug，AndPermission提供了一个在onFailed时提示用户去Setting设置的dialog，点击确定即可跳转Setting，后文有介绍，demo中也有例子。

**Comment by k354250377** [comment]
我现在的问题是 不管有没有权限都会走到 getCalendarYes 里面....无论拿到拿不到也不走defaultSettingDialog  不跳setting啊....

**Comment by yanzhenjie** [comment]
上面已经描述做法了，你可以根据上述描述进行测试。
