### ISSUE TITLE
魅族X5上授权，测试读文件崩溃

### ISSUE THREAD

**Issue by JakieTang** [yanzhenjie/AndPermission#261]
![image](https://user-images.githubusercontent.com/5336313/39924880-202fa8a8-555c-11e8-819c-70d17d1feb47.png)

**Comment by JakieTang** [comment]
SDK版本是  2.0.0-rc4

**Comment by yanzhenjie** [comment]
这个test的地方已经`try-catch`了，这个错误也不是权限造成的崩溃，似乎看起来是文件内容引起的底层崩溃，`try-catch`都抓不到。

**Comment by yanzhenjie** [comment]
No response, close.
