### ISSUE TITLE
vivo x20 请求权限直接走的onGranted（）

### ISSUE THREAD

**Issue by xinyangmaojian** [yanzhenjie/AndPermission#262]
手机型号：vivo x20
android版本：7.1.1
vivo rom : funtouch os 3.2
情况说明：
请求了读取通讯录的权限，即使通过设置-应用管理去禁止掉此权限，但是在调用我们的方法进行授权时，依然走的是onGranted（）。
我看特殊说明上讲如果无法获取真实权限状态时会抛出异常走onDenied（）,但是在此版本上还是直接走的onGranted（）。
请问我是哪里操作的有问题吗，目前未自己实现代码，直接是先运行的andPermission的demo

**Comment by yanzhenjie** [comment]
你直接在`onGranted()`中读取通讯录即可。

**Comment by xinyangmaojian** [comment]
好的   谢谢
