### ISSUE TITLE
申请打电话权限问题

### ISSUE THREAD

**Issue by qiaoscong** [yanzhenjie/AndPermission#264]
运行您的Demo,为了获取Permission.CALL_PHONE权限，在设置里面已经禁止拨打电话了，但是获取Permission.CALL_PHONE权限的时候，返回的是成功了，导致权限获取不到

**Comment by yanzhenjie** [comment]
你好，请先看一下文档，如果还有问题的话，麻烦再回复一下。
* [特别说明](http://yanzhenjie.github.io/AndPermission/cn/explain.html)
* [提问](http://yanzhenjie.github.io/AndPermission/cn/issue.html)

**Comment by yanzhenjie** [comment]
No response, close.
