### ISSUE TITLE
小米 mix miui9.8.5.3   android8.0 一直回调失败

### ISSUE THREAD

**Issue by wk37** [yanzhenjie/AndPermission#265]
操作流程：联系人权限组，第一次申请---拒绝---回调失败，第二次申请---不再提醒并拒绝---回调失败，第三次申请---去设置手动打开---返回界面检测--仍无权限

**Comment by yanzhenjie** [comment]
MIUI9.8.x在设置中打开也获取不到权限，AndPermission获取到的实际状态可能是正确的，你可以直接调用获取联系人的代码试试看。这种情况没办法了，只有在申请的时候点同意，如果勾了不再提醒，除了清除数据和重装后再次申请外，永远也获取不到权限了。

**Comment by yanzhenjie** [comment]
No response, close.
