### ISSUE TITLE
想知道您这个跟easypermissions对比一下，在适配国产手机上是不是更胜一筹

### ISSUE THREAD

**Issue by d19890415** [yanzhenjie/AndPermission#266]
尤其是对于miui9.8.x 等你无能为力的国产系统上，是不是easypermissions一样会出现问题。

是不是有的国产手机使用easypermissions问题比会你的AndPermission更多

https://github.com/googlesamples/easypermissions

多谢楼主指点

**Comment by yanzhenjie** [comment]
你好，EasyPermissions非常非常优秀，具体细节自己参考文档做测评哦，谢谢！
