### ISSUE TITLE
提个建议，关于8.0系统安装apk时权限异常问题

### ISSUE THREAD

**Issue by xfort** [yanzhenjie/AndPermission#272]
实测在 构建apk时 若`targetSdkVersion<26` ，在8.0及以上系统里（实测小米手机，Pixel），使用`AndPermission.with(this).install()`  会总是回调 `onDenied()`，不管是否已有权限。
若 `targetSdkVersion>=26` 则一切正常。
建议把 这些前提条件 写在文档里

**Comment by yanzhenjie** [comment]
在测试中发现，当targetSdkVersion<26时，不论设置中允许安装开关是否打开，内部判断总会返回`false`，但是如果开关关闭时安装时系统还是会提示用户去打开开关。

**解决方案**：使用2.0.0-rc6及以下版本时请注意，如果开发者的应用的targetSdkVersion<26，安装apk时使用AndPermission的分享私有文件功能即可安装，当targetSdkVersion>26请使用AndPermission的安装apk功能来安装。

会尽快发布一个版本来修复这个问题，谢谢反馈。
