### ISSUE TITLE
8.0悬浮窗权限有吗？

### ISSUE THREAD

**Issue by yuliangC** [yanzhenjie/AndPermission#273]
android.permission.ACTION_MANAGE_OVERLAY_PERMISSION 这个权限貌似还没有适配吧

**Comment by yanzhenjie** [comment]
有，在2.0.0-rc6版本，昨天刚发布，在首页有说明。

**Comment by yanzhenjie** [comment]
之前只看了标题，问题描述粗略的看了一下。刚才回顾时发现描述中的一个小问题，现予以纠正（怕误导后面来的同学），这个权限应该是：
```
android.permission.SYSTEM_ALERT_WINDOW
```

并没有题主描述中说的权限和此常量，题主表述的有可能是`Settings`类中的：
```java
android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION
```
此常量是用来打开设置该权限页面的一个`Action`。
