### ISSUE TITLE
rc6第一次拒绝权限后，再次调用不会弹出授权框

### ISSUE THREAD

**Issue by 378063465** [yanzhenjie/AndPermission#275]
tarageSdkVersion 23 在360手机上测试发现第一次拒绝权限后，再次打开不会弹出授权框，一直执行onDenied，有些手机只提醒一次。

**Comment by yanzhenjie** [comment]
是什么权限？Android系统版本是多少？
根据现有的信息，不排除库的问题，之外我怀疑是360手机本身就是拒绝一次就自动**不再提示**了，这种手机目前也很常见。
有些手机只提醒一次，这个不明白说的是什么。

**Comment by 378063465** [comment]
相机和文件读写权限，7.1，有些机型第一次拒绝之后在次执行这段代码 什么都没有，什么消息都没有，授权框没有，允许拒绝方法都不执行

**Comment by 378063465** [comment]
抱歉说错了，都是执行失败的方法

**Comment by yanzhenjie** [comment]
嗯这个是设备的问题，很多手机有这样的情况，但是这个不影响使用。你可以执行SDK自带的申请方法看看是否弹出授权Dialog。

**Comment by 378063465** [comment]
问题是这样的，我再描述一遍，360手机安装之后使用rc6如果权限没有打开一次授权框也不会提示，直接执行失败方法，如果权限是自己手动打开就会执行成功方法。其他部分机型第一次拒绝之后，以后打开都不会有授权框，直接执行授权失败

**Comment by 378063465** [comment]
好的，我改用rc5就不存在这个问题

**Comment by yanzhenjie** [comment]
明白，这种情况很多人反馈过。在中文文档中我写了一篇特别说明，你可以先阅读一下然后结合文档再测试看看。比如读写SD卡这个权限，在使用系统Api请求后，360没有弹出授权Dialog，直接回调了AndPermission失败，AndPermisison此时会执行一下读写SD卡，如果正常执行则回调你的`onGrant()`，如果发生异常则回调你的`onDenied()`，这样就可以确保权限状态是正确的。
另外有的手机在使用系统Api请求授权时不会弹出授权Dialog，但是在真正执行读写SD卡时会弹出，因此这也是AndPermission这么做的原因。
你可以按照我说的再跑一边，看看在几个机型上是否可以顺利完成的你的业务，权限这个是做不到100%完美的，只能最大限度的按照正常流程完成业务。
