### ISSUE TITLE
手机型号华为荣耀V9、 android8.0系统

### ISSUE THREAD

**Issue by itchenqigitup** [yanzhenjie/AndPermission#279]
我的代码和权限申请如下：
我用的是implementation 'com.yanzhenjie:permission:2.0.0-rc8'这个版本
我分明点击了“始终允许”定位权限，但是代码居然走了 onDenied,授权失败。让我感到很奇怪。这种情况反复出现
AndPermission.with(this)//
                .runtime()//
                .permission(Permission.ACCESS_FINE_LOCATION,//
                        Permission.ACCESS_COARSE_LOCATION)//
                .rationale(new RuntimeRationale())//
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> permissions) {
                        //toast(R.string.successfully);
                    }
                })
                .onDenied(new Action<List<String>>() {
                    @Override
                    public void onAction(@NonNull List<String> permissions) {
                        LogUtils.d("itchen---在点击了禁止按钮，禁用了定位权限");
                    }
                })
                .start();

**Comment by yanzhenjie** [comment]
你用的是哪个版本？如果不是最新版本，请升级到最新版本试试。

**Comment by itchenqigitup** [comment]
我用的是这个版本implementation 'com.yanzhenjie:permission:2.0.0-rc8'

**Comment by itchenqigitup** [comment]
然后我降低到com.yanzhenjie:permission:2.0.0-rc5这个版本就是好的，正常的走，允许和禁止逻辑

**Comment by yanzhenjie** [comment]
你试试这段代码，分别测试一下Permission.ACCESS_FINE_LOCATION和Permission.ACCESS_COARSE_LOCATION的result都是几。
```java
AppOpsManager appOpsManager = (AppOpsManager) context.getSystemService(Context.APP_OPS_SERVICE);
String op = AppOpsManager.permissionToOp(Permission.ACCESS_FINE_LOCATION);
int result = appOpsManager.checkOpNoThrow(op, android.os.Process.myUid(), getPackageName());
```

**Comment by itchenqigitup** [comment]
大神，我试了，如下：
Permission.ACCESS_FINE_LOCATION的result 是 0
Permission.ACCESS_COARSE_LOCATION的result 是 0

**Comment by yanzhenjie** [comment]
麻烦再帮忙确定两个问题：
1. 只申请`Permission.ACCESS_COARSE_LOCATION`权限看是否可以通过。
2. 第一个问题如果通过，再看GPS开关是否打开，没有打开的话把开关打开申请看是否通过。
如果第一个测试不通过，可能这个机器没有Network这个provider，如果第一个通过，第二个GPS是打开的，但是权限申请不过，那么这个机器可能没有提供GPS这个provider。
如果两个测试都过了，那么就是AndPermisison的问题。

**Comment by itchenqigitup** [comment]
上述测试 ，就是我用的'com.yanzhenjie:permission:2.0.0-rc8'的内容测试的。

**Comment by yanzhenjie** [comment]
非常感谢反馈，我尝试修复了这个问题，你试试rc9版本。

**Comment by itchenqigitup** [comment]
好的，稍等，我集成到项目中再试一试

**Comment by itchenqigitup** [comment]
### 使用com.yanzhenjie:permission:2.0.0-rc9的反馈 ###
1. 我关闭了GPS，同时申请ACCESS_FINE_LOCATION和ACCESS_COARSE_LOCATION两个权限，点击权限弹窗“始终允许”，仍然走onDenied授权失败了--->结果：失败，不正常
2. 我打开GPS，同时申请ACCESS_FINE_LOCATION和ACCESS_COARSE_LOCATION两个权限，点击权限弹窗“始终允许”，
则，走正常的逻辑。

难道跟GPS的开关有这么大的关系？

**Comment by whb7762300** [comment]
@yanzhenjie rc9版本,只申请Permission.ACCESS_COARSE_LOCATION权限,在关闭GPS的情况下,允许定位权限还是回调的ondenied接口

**Comment by tangfunan2017** [comment]
@yanzhenjie rc9依赖添加失败呢```@yanzhenjie rc9依赖添加失败呢```Error:Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.yanzhenjie:permission:2.0.0-rc9.
<a href="openFile:D:/MyProject/AndroidAPP/app/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app@release/compileClasspath&#39;: Could not resolve com.yanzhenjie:permission:2.0.0-rc9.">Show Details</a>```

**Comment by yanzhenjie** [comment]
收到，谢谢反馈，我正在看。

**Comment by yanzhenjie** [comment]
@whb7762300 你手机可能不支持COARSE。

**Comment by whb7762300** [comment]
@yanzhenjie 我的手机是魅蓝note6(flyme7系统),前两天在QQ上和你反馈过这个问题...

**Comment by whb7762300** [comment]
![gps](https://user-images.githubusercontent.com/19603046/41011946-e5c5bc3c-6971-11e8-8512-ad32fe0066c8.jpg)
![gps](https://user-images.githubusercontent.com/19603046/41011952-ed62997e-6971-11e8-8e48-7b6b473a7431.jpg)
我用我的魅蓝note6手机和同事的华为荣耀V9手机测试都是一样的结果,开了GPS的情况下回调正常,不开启GPS的情况下,回调都是ondenied @yanzhenjie

**Comment by yanzhenjie** [comment]
@whb7762300 从你的调试记录看，GPS开关关闭的情况下，network这个provider也不能用对吧？

**Comment by whb7762300** [comment]
![gps](https://user-images.githubusercontent.com/19603046/41012037-594727cc-6972-11e8-8114-d58ff8ae544c.jpg)
![gps](https://user-images.githubusercontent.com/19603046/41012045-6342054e-6972-11e8-9601-2e002e19de73.jpg)
我用我的魅蓝note6手机和同事的华为荣耀V9手机测试都是一样的结果,开了GPS的情况下回调正常,不开启GPS的情况下,回调都是ondenied @yanzhenjie

**Comment by whb7762300** [comment]
@yanzhenjie 嗯,是的,GPS开关关闭的情况下 networkprovider这个好像没有...

**Comment by yanzhenjie** [comment]
@whb7762300 非常感谢提供测试数据用用例结果，刚刚 @itchenqigitup 同学通过QQ找我反馈了，我通过他的手机测试结果和你的一样，我会马上发布新版本，再次感谢两位的贡献。

**Comment by yanzhenjie** [comment]
@whb7762300 @itchenqigitup 你们好，rc10已经发布，可以更新使用了，如果有问题欢迎继续反馈。

**Comment by whb7762300** [comment]
@yanzhenjie 好的，感谢大大

**Comment by zhoukai0203** [comment]
AppOpsManager 引用的context 存在内存泄漏，看能否处理下 @yanzhenjie

**Comment by yanzhenjie** [comment]
@zhoukai0203 请不要在已关闭的issue中提问，你可以评论这个issue。
