### ISSUE TITLE
小米5 8.0系统，权限请求问题。

### ISSUE THREAD

**Issue by DaiFalin** [yanzhenjie/AndPermission#286]
经测试作者的demo，发现在小米的8.0系统以上，下列代码：
new AlertDialog.Builder(context)
                .setCancelable(false)
                .setTitle(R.string.title_dialog)
                .setMessage(message)
                .setPositiveButton(R.string.setting, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        setPermission();
                    }
                })
                .setNegativeButton(R.string.cancel, new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                    }
                })
                .show();
在跳转APP权限设置界面，手动允许了权限后，返回还是会进入onDenied()方法，但是权限设置里是允许了的。

**Comment by yanzhenjie** [comment]
你好，最近一些开发者反馈，小米MUI9.8.x系统，只有在第一次申请权限时同意才能获取到权限。
描述如下：
1. 一旦拒绝权限，在设置中打开开关无法真正授权，打开开关后执行代码时会发生无权限的崩溃。  
2. 一旦统一权限，在设置中关闭开关无法撤销授权，关闭开关后执行代码时不会发生无权限的崩溃。
3. MUI9.8.x部分手机存在1，不存在2。

你可以测试一下你的手机是否有这种情况，如果有则没有其它办法了。如果没有，请告知使用的AndPermission的版本和出问题的权限是哪些，尽量提供一些能帮助完善项目的信息，谢谢。

**Comment by hacket** [comment]
@yanzhenjie 我测试是开发者选项中关掉MIUI优化，就会出现你权限设置开关无效，开启MIUI优化正常

**Comment by yanzhenjie** [comment]
手机问题。
