### ISSUE TITLE
oppo  x7  授权异常问题

### ISSUE THREAD

**Issue by renjinlong** [yanzhenjie/AndPermission#289]
获取摄像头权限   点击了拒绝  但是依然走了successful 方法

**Comment by yanzhenjie** [comment]
你好，先看一下文档，如果还有问题再回复一下，没有问题的话再关闭这个issue。

**Comment by renjinlong** [comment]
你好   我刚才测试了一下  oppo的机器5.0的系统会出现我刚才说的问题，但是6.0就不会出现了，文档我看了只有使用方法，或者我没对位置？

**Comment by yanzhenjie** [comment]
有个特殊说明，因为国产机嘛。

有同学反馈过，5.0的没权限时运行可能不会保存，看到的是黑屏。AndPermission在6.0以下检测时是直接执行代码看是否报错，报错说明没有权限。

**Comment by renjinlong** [comment]
你好   现在又遇到一个oppo vivo 的问题 在授权权限的时候   如果用户把（不再提醒）的对勾去掉   然后一直在弹出同一个授权弹框，如果把不再提醒）的对勾勾上就正常了。

**Comment by yanzhenjie** [comment]
新问题请单独提issue，旧的issue如果已经没问题了，你应该回复结果并关闭它，否则会给其它开发者和项目维护者带来不必要的麻烦。
