### ISSUE TITLE
OPPO R9S请求权限之后 弹窗倒计时,没有点击任何地方之后 会进行下一步

### ISSUE THREAD

**Issue by androidmoyan** [yanzhenjie/AndPermission#295]
当请求权限时,会弹出一个dialog 一个是允许一个是禁止,禁止会倒计时, 这个时候不操作任何按钮, 我的下一步操作是 在权限请求成功之后 进行的, 但是这个时候 倒计时进行2S后自动进入

**Comment by yanzhenjie** [comment]
如果非AndPermission提到的特殊权限，那就说明是有权限的，如果是特殊权限，请配合文档。

**Comment by androidmoyan** [comment]
请求的是单纯的定位权限, 如果说是有权限的,那就不应该弹出请求权限的对话框的

**Comment by yanzhenjie** [comment]
你好，你先看一下文档。对于国产机，准确状态如果能那么容易检测到，你就不会找到这个库了。

**Comment by snnairow** [comment]
oppo R9S 当你的权限是询问的时候，回调的是onGrand方法，所以进行了下一步，这个dialog可能是高德等地图在动态请求的时候申请的
