### ISSUE TITLE
oppoR9sk 寄oppoA57 禁用定位权限还走onGrant()方法

### ISSUE THREAD

**Issue by dutay** [yanzhenjie/AndPermission#297]

**Comment by snnairow** [comment]
我也遇到了

**Comment by snnairow** [comment]
继续debug，发现context.checkPermission(permission, android.os.Process.myPid(), android.os.Process.myUid());这个方法返回的result不是PackageManager.PERMISSION_DENIED

**Comment by yanzhenjie** [comment]
国产机请配合中文文档使用。
