### ISSUE TITLE
小米5s 拍照权限异常问题

### ISSUE THREAD

**Issue by coolBreezes** [yanzhenjie/AndPermission#299]
楼主，是这样，
测试机型：小米5s，MUI9.5   android7.0
jar版本：com.yanzhenjie:permission:2.0.0-rc11
问题复现：1.先将拍照权限设置为拒绝并不再提醒，此时点击菜单键，长按历史记录里的app，对应弹出的是系统自带的权限管理页面，此时手动打开拍照权限；

![qq_pic_merged_1530064817346](https://user-images.githubusercontent.com/8476068/41948847-4e2f9510-79f1-11e8-9d17-579215d1050d.jpg)

2.回到app，此时checkSelfPermission返回 0，但实际上并未获取到拍照权限
3.打开应用管理，打开小米的权限管理，此时显示的拍照权限是拒绝的状态
![qq_pic_merged_1530064788228](https://user-images.githubusercontent.com/8476068/41948846-4df7a01a-79f1-11e8-8799-b3558b7069e0.jpg)
（也就是两个权限状态此时是不一致的）

**Comment by yanzhenjie** [comment]
@coolBreezes 你好，根据你的描述我没看出来和AndPermission有什么关系。
