### ISSUE TITLE
targetApi < 23, 在手机权限管理中关闭应用权限，就真的拿不到权限了

### ISSUE THREAD

**Issue by noiary** [yanzhenjie/AndPermission#3]
targetApi < 23, 在手机权限管理中关闭应用权限，就真的拿不到权限了

**Comment by yanzhenjie** [comment]
Of course, 不然怎么叫6.0运行时权限呢，这篇文章应该讲的蛮清楚了：[好，我去瞅瞅](http://blog.csdn.net/yanzhenjie1003/article/details/52503533).

**Comment by thisfeng** [comment]
targetApi < 23, 并不是拿不到权限，只不过是以 以前的那种方式进行权限的获取吧！感谢作者的分享
