### ISSUE TITLE
小米6和三星盖世7  每次调用判断权限后程序的点击事件都有延迟

### ISSUE THREAD

**Issue by xjhh** [yanzhenjie/AndPermission#302]
我使用的版本是 rc11   在小米6和三星盖世7测试的时候  发现 rc11版本    在程序每次调用判断权限后 程序的点击事件  会有200到400ms 的延迟   如果我把版本降到 rc3的话  没有这个问题  是为什么呢

**Comment by yanzhenjie** [comment]
不一定是每次，内部启动了一个Activity来做辅助，为了防止开发者连续调用也做250ms的延迟，加起来就有200-400了，2.0正式版我会尽量缩短，但是暂时没有办法完全避免。

**Comment by xjhh** [comment]
好的

**Comment by yanzhenjie** [comment]
目前的回调延时有100ms，刚才做了测试，不能把这个延时去掉。如果延时对你影响特别大，你可以考虑自行修改源码。
