### ISSUE TITLE
同一时间，多处请求同一权限，如果当前正在请求，是否可以过滤其他的相同权限请求呢

### ISSUE THREAD

**Issue by coolBreezes** [yanzhenjie/AndPermission#303]
群主，您好，
多处同时请求同一权限，如果当前正在请求，是否可以过滤其他的相同权限请求呢

**Comment by yanzhenjie** [comment]
同时只能发起一个请求，同时发起多个请求可能会发生未知异常。也就是说必须等一个请求结束了才能发起另一个请求。
