### ISSUE TITLE
onGranted()方法发生异常的怪异现象

### ISSUE THREAD

**Issue by LLQQHH** [yanzhenjie/AndPermission#304]
之前文档里面有说：如果onGranted()和onDenied()方法都被调用了，说明开发者的onGranted()方法发生了异常。
但是，发生异常后，在onDenied里面调用hasAlwaysDeniedPermission，返回的是true。
不应该返回false吗？因为我给与权限了，只是onGranted我发生了异常。

**Comment by yanzhenjie** [comment]
要看一下发生的异常是不是无权限产生的异常，如果是就可能出现你说的情况。一部分国产机的`hasAlwaysDeniedPermission()`状态是错误的，你可以调用sdk原生接口测试AndPermission返回的这个状态是否是正确的。

**Comment by LLQQHH** [comment]
异常跟权限无关的，直接测试
直接在成功回调后onGranted()，写入下面代码，让他抛异常
int i=0
int j=5/i;
，走onDenied方法，在onDenied里面调用hasAlwaysDeniedPermission，返回的是true。，已经用原生接口测试AndPermission返回的这个状态是错误的，
型号：红米4x,版本 android7.1.2.  MIUI版本：9.5.3.0稳定版

**Comment by yanzhenjie** [comment]
`hasAlwaysDeniedPermission()`方法传入的须是被拒绝的权限。

**Comment by yanzhenjie** [comment]
No responsed, closed.
