### ISSUE TITLE
小米权限管理设置为允许但是仍无法正常使用权限

### ISSUE THREAD

**Issue by coolBreezes** [yanzhenjie/AndPermission#306]
群主，您好，
jar包中，小米手机，当用户拒绝并设置不再提醒，jar包中的处理是
判断若当前为小米手机，则跳转到小米的权限管理设置中心去修改权限，

但是当前 MIUI 9.6版本，在权限管理中心手动修改权限为允许，回到app实际上是没有效果的，
要手机打开 开发者模式-》MIUI优化，则权限管理中心的设置才有效，
但是一般用户都不会去开启这个功能，所以当前跳转到系统自带的权限管理会好些

**Comment by AresCool** [comment]
请问小米或者红米适配的怎样了 , 我现在红米5也遇到这样的问题,,,,真是好坑啊,

**Comment by Ximano** [comment]
确实存在这样的问题，现在红米的用户还是挺多的。所以我现在都是很慎重的选择权限申请的框架，不行的话就用自己最原始的方法，不引导用户开启，避免出现问题。

**Comment by yanzhenjie** [comment]
很早之前我就发现这个问题了，但是没有发现需要开启MIUI优化才能准确获取状态。
根据大家的回复，我做了测试，发现只有在开启MIUI优化的状态下，再修改权限的状态后，再次获取权限状态才能准确获取，否则就算跳转到默认setting页面，修改权限也不能准确获取到权限状态。
我再测试一下，找一个比较好的方案，如果你们有好方案也提供一下。
