### ISSUE TITLE
在小米的安卓6.0上存在问题

### ISSUE THREAD

**Issue by shlockfan** [yanzhenjie/AndPermission#31]
和其它的权限申请库一样，我在小米6.0和一加7.1上测试了此库和easyPermission和RxPermission，在小米的6.0设备上三个库均无法获取定位权限(ACCESS_FINE_LOCATION)，一加7.1的设备没有问题，建议修改一下README，以免对其他人产生误解。

**Comment by 506967734** [comment]
我也遇到这样问题，ACCESS_FINE_LOCATION权限是没有开启，但是返回却显示开启

**Comment by yanzhenjie** [comment]
众所周知是小米系统的bug，这种外部的库是无法修复的，如果你允许了权限，并且回调了你成功，但是实际执行代码的时候崩溃了，那么获取到权限后应该做以下判断（你也可以使用下面的提到的`SettingDialog`）：
```java
String permission = Manifest.permission.ACCESS_FINE_LOCATION;
String op = AppOpsManagerCompat.permissionToOp(permission);
int result = AppOpsManagerCompat.noteProxyOp(context, op, context.getPackageName());
if(result == AppOpsManagerCompat.MODE_ALLOWED) {
    // TODO 有权限。
} else {
    // TODO 没有权限。
}
```

还有一部分手机，用户允许了权限，也实际获取到了权限，但是缺回调了失败，在Setting中查看这个权限也是没有被允许的，这个回调是由底层回调的，那么在回调的失败的方法中使用[AndPermission](https://github.com/yanzhenjie/AndPermission)的这个提示`SettingDialog`，用户点击后可以去`Setting`中手动授权：
```java
// 第一种：用默认的提示语。
AndPermission.defaultSettingDialog(this, REQUEST_CODE_SETTING).show();

// 第二种：用自定义的提示语。
// AndPermission.defaultSettingDialog(this, REQUEST_CODE_SETTING)
//     .setTitle("权限申请失败")
//     .setMessage("我们需要的一些权限被您拒绝或者系统错误...")
//     .setPositiveButton("好，去设置")
//     .show();

// 第三种：自定义dialog样式。
// SettingService settingService = AndPermission.defineSettingDialog(this, REQUEST_CODE_SETTING);
// 你的dialog点击了确定调用：
// settingService.execute();
// 你的dialog点击了取消调用：
// settingService.cancel();
```

**Comment by shlockfan** [comment]
加了 AppOpsManagerCompat.noteProxyOp 的判断，在6.0上没问题了，但是在4.1.1的系统上默认允许定位，返回的却是result != AppOpsManagerCompat.MODE_ALLOWED,没有权限。可能还要区分Build.VERSION

**Comment by yanzhenjie** [comment]
是我之前考虑不周，我已经修改了判断条件，请再次查看上放答案。
AppOpsManagerCompat.MODE_IGNORED有三个值：
```java
AppOpsManagerCompat.MODE_IGNORED // 忽略，不同意。
AppOpsManagerCompat.MODE_DEFAULT // 默认，没有改动，6.0一下默认是有，以上就说不定了。
AppOpsManagerCompat.MODE_ALLOWED // 有权限。
```
因此我们判定等于忽略并且系统版本是6.0及以上，那么就是没有权限，否则就是有权限：
```
result == AppOpsManagerCompat.MODE_IGNORED 
  && Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
```
完整答案见我上一个Reply。

**Comment by luziming** [comment]
在Fragment中申请联系人以及位置相关权限时AndPermission.hasAlwaysDeniedPermission判断总是为true
手机是oppo R9s
