### ISSUE TITLE
金立手机申请摄像头权限 会弹出多次请求页面

### ISSUE THREAD

**Issue by wushange** [yanzhenjie/AndPermission#310]
金立手机申请摄像头权限 会弹出两次请求页面

**Comment by yanzhenjie** [comment]
内置会有多次判断权限，如果没有权限就会申请权限，申请完权限，还会执行一次开启摄像头的测试来判断是否真正的有权限，因此理论上最多会弹出一次。但是有些手机，在没有权限切调用摄像头时也会弹出，有些手机在判断权限时也会弹出，这个没有办法，只能等以后国产机的权限策略和Android官方的策略统一了。
