### ISSUE TITLE
ContextSource修改bug：保持Intent的flag，没有在最新版里

### ISSUE THREAD

**Issue by qhy2013** [yanzhenjie/AndPermission#311]
ContextSource修改bug：保持Intent的flag，没有在最新版里
安装APK的相关类，也没有了
最新版：com.yanzhenjie:permission:2.0.0-rc2
旧版本：com.yanzhenjie:permission:2.0.0-rc11, ContextSource是旧代码

**Comment by yanzhenjie** [comment]
rc11才是最新版。

**Comment by qhy2013** [comment]
com.yanzhenjie:permission:2.0.0-rc11
这个版本，引入代码，还是 
`/**
 * <p>Context Wrapper.</p>
 * Created by Yan Zhenjie on 2017/5/1.
 */
public class ContextSource extends Source {

    private Context mContext;

    public ContextSource(Context context) {
        this.mContext = context;
    }

    @Override
    public Context getContext() {
        return mContext;
    }

    @Override
    public void startActivity(Intent intent) {
        if (mContext instanceof Activity) {
            mContext.startActivity(intent);
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            mContext.startActivity(intent);
        }
    }

    @Override
    public void startActivityForResult(Intent intent, int requestCode) {
        if (mContext instanceof Activity) {
            Activity activity = (Activity) mContext;
            activity.startActivityForResult(intent, requestCode);
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            mContext.startActivity(intent);
        }
    }

    @Override
    public boolean isShowRationalePermission(String permission) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) return false;

        if (mContext instanceof Activity) {
            Activity activity = (Activity) mContext;
            return activity.shouldShowRequestPermissionRationale(permission);
        }

        PackageManager packageManager = mContext.getPackageManager();
        Class<?> pkManagerClass = packageManager.getClass();
        try {
            Method method = pkManagerClass.getMethod("shouldShowRequestPermissionRationale", String.class);
            if (!method.isAccessible()) method.setAccessible(true);
            return (boolean) method.invoke(packageManager, permission);
        } catch (Exception ignored) {
            return false;
        }
    }
}`

**Comment by yanzhenjie** [comment]
addFlag这个还没发布新版本。
