### ISSUE TITLE
java.lang.IllegalStateException: The permission com.android.voicemail.permission.ADD_VOICEMAIL is not registered in manifest.xml

### ISSUE THREAD

**Issue by RmondJone** [yanzhenjie/AndPermission#312]
红米5P和华为手机，申请Permission.Group.PHONE都会报这个错误。而实际上我已经在mainfast.xml里加过了这些权限。

**Comment by yanzhenjie** [comment]
经测试，无法复现题主描述的问题。
如果你不需要这个权限，就别申请了，可能是系统不允许申请。如果非要这个权限，再认真检查一下你的manifest.xml文件。

**Comment by a1v1s** [comment]
我在华为手机上也遇到了这个问题
