### ISSUE TITLE
疑似 onRequestPermissionsResult 没有被回调

### ISSUE THREAD

**Issue by aheadlcx** [yanzhenjie/AndPermission#316]
OPPO R9S 机型，偶尔出现 ，PermissionActivity 在栈顶，但是没有弹出权限申请框。 & 返回键被屏蔽了。  返回键屏蔽，这个有必要么?

**Comment by yanzhenjie** [comment]
如果`onRequestPermissionsResult`没有被回调，我觉得这是手机的bug。

不论是手机bug，还是框架问题没有回调，就算不屏蔽返回键，你们也会提另一个bug，所以我觉得这个问题和屏蔽不屏蔽返回键没有关系。

我测试了一下，目前框架是每次都会回调的。你们可以确定一下是否是手机没回调，或者是框架没回调，如果是框架问题还好办，如果是手机问题那也没办法了。

**Comment by aheadlcx** [comment]
不屏蔽返回键，会提另一个 bug ，是指什么 bug ？我这边是跑 monkey 出现这个情况的，人工点击，也是每次都会回调。

**Comment by yanzhenjie** [comment]
@aheadlcx monkey的话，可能是瞬间点击申请授权多次，这样就会出现不回调的情况，我正在想解决办法。

**Comment by yanzhenjie** [comment]
@aheadlcx 我看了一下系统的申请Api，不允许同时进行多个授权请求，但是允许一个授权请求中请求多个权限。

**Comment by yanzhenjie** [comment]
The new version now uses queues and won't have this problem.

**Comment by aheadlcx** [comment]
Thanks @yanzhenjie
