### ISSUE TITLE
好像是内存泄露

### ISSUE THREAD

**Issue by wanglei360** [yanzhenjie/AndPermission#318]
在使用leakcanary-android:1.5.4的时候，leakcanary用的不是很好，您这边依赖的是“implementation 'com.yanzhenjie:permission:2.0.0-rc11' ”您有时间的话自己看下吧，谢谢，[我做的截图](https://github.com/wanglei360/SoAndJarDemo/blob/master/%E6%97%A0%E7%94%A8%E5%9B%BE%E7%89%87/WechatIMG155.jpeg?raw=true)

**Comment by yanzhenjie** [comment]
这个内存泄漏我也没办法，不是框架造成的。
