### ISSUE TITLE
大大大 bug

### ISSUE THREAD

**Issue by Blizzard-liu** [yanzhenjie/AndPermission#319]
魅族5.1 还会申请打电话权限 点击拒绝 回调onGranted

**Comment by Blizzard-liu** [comment]
然后都是直接回调onGranted  电话也打不了
E/Instrumentation: User denied to start activity with intent: Intent { act=android.intent.action.CALL dat=tel:xxx-xxx-xxxx }

**Comment by yanzhenjie** [comment]
看文档。
