### ISSUE TITLE
在Fragment中申请联系人以及位置相关权限时AndPermission.hasAlwaysDeniedPermission判断总是为true

### ISSUE THREAD

**Issue by luziming** [yanzhenjie/AndPermission#32]
如果没有在AndroidManifest中配置就会跳出弹窗,要求去Setting中去设置,但是设置之后回来还是弹出窗口让去设置。。如果在AndroidManifest配置过了，那就如题，一直为true。不走其他逻辑，是手机问题还是我用法有问题？
手机是oppo R9s

**Comment by yanzhenjie** [comment]
问题有一个地方可能没有描述清楚，我怀疑你调用错方法了。

如果是的fragment和activity继承的是support下的fragment和AppCompatActivity，那么是不用做判断的，直接调用`AndPermission...`就好了，如果你继承的是Fragment或者Activity的话，调用`AndPermission...`之前做一个是否有权限的判断：
```java
if(AndPermission.hasPermission(...)) {
    ...
}
```
题主所述`AndPermission.hasAlwaysDeniedPermission(...)`是在请求失败后调用，目的是判断用户拒绝了权限并且勾选了**不再提示**，此时可以利用弹一个dialog提示用户去Setting中手动赋权。

另外还有很多手机有bug，不论拒绝或者同意，都会回调失败，并且判断结果都是true，所以上面提供的这个Dialog的目的也是为了兼容这种情况。

**Comment by luziming** [comment]
额 ，sorry 那个是我写错了  刚开始我是写的AndPermission.hasPermission(...)，后来又把这句去掉直接申请，都是走的申请成功的回调，但是在Setting中还是没有打开的，而且功能也是不能正常使用的


```
// 申请权限。
                    AndPermission.with(this)
                            .requestCode(100)
                            .permission(Manifest.permission.WRITE_CONTACTS)
                            .rationale(new RationaleListener() {
                                @Override
                                public void showRequestPermissionRationale(int requestCode, Rationale rationale) {
                                    // 这里使用自定义对话框，如果不想自定义，用AndPermission默认对话框：
                                    Log.e("PhoneChargeFragment", "获取联系人: 申请权限对话框");
                                    AndPermission.rationaleDialog(mActivity, rationale).show();
                                }
                            })
                            .send();
```
```

**Comment by luziming** [comment]
我用其他机器测了一下  好像只是这款机器不行 oppo R9s

**Comment by yanzhenjie** [comment]
这个是系统造成的bug，部分小米手机也存在，请参考：#31
