### ISSUE TITLE
ANR异常问题

### ISSUE THREAD

**Issue by zhoukai0203** [yanzhenjie/AndPermission#322]
![qq 20180725161903](https://user-images.githubusercontent.com/5763030/43188434-a7e4913c-9026-11e8-8ebb-c37f8d46a2a0.png)
![qq 20180725161917](https://user-images.githubusercontent.com/5763030/43188493-d2df46de-9026-11e8-97d0-3f38a7d624ba.png)
bugly的anr异常上报的

**Comment by newlai913** [comment]
你们这个问题解决了没
