### ISSUE TITLE
vivo Y85A第一次申请权限，直接走了 rationale 回调

### ISSUE THREAD

**Issue by burgessjp** [yanzhenjie/AndPermission#324]
手机系统版本：8.1.0
库版本：2.0.0-rc11

**Comment by burgessjp** [comment]
这是实际存在得一个问题，为什么直接标记为 `invalid` ?

**Comment by yanzhenjie** [comment]
走rationale有以下两种可能：
1. 该应用之前就申请过该权限并被拒绝了
2. 部分国产机rationale的状态错误

**Comment by burgessjp** [comment]
我这边确认是第一次请求就出现这个，不是拒绝过一次出现的。运行你的demo也是一样的。
如果有需要什么信息的可以我很乐意提供。

**Comment by yanzhenjie** [comment]
那就是国产机的rationale的状态错误，这个没办法；因为大多数手机是正常的，有的国产机永远不会走rationale。

**Comment by zhouxq** [comment]
的确有这样 的问题 ；demo也会有这样的问题 ；在模拟器上 也会复现

**Comment by yanzhenjie** [comment]
@zhouxq 是什么模拟器？在AndroidSDK自带模拟器上未出现过。

**Comment by zhouxq** [comment]
网易mumu模拟器 ，andriod 7.0 设置的是 Oneplus 手机 。作者 @yanzhenjie   可以来测试一下

**Comment by yanzhenjie** [comment]
这个问题是由手机本身造成的，其实我思考了很多方案，各种手机情况很多，非常不好兼容，因此没有做任何兼容处理。建议是没掉用就没掉用，不要太关心这个，处理好成功和失败的场景还是可以很完善的做完流程。

**Comment by ImportEffort** [comment]
我也遇到了这种情况，由于在 rationale 也有弹窗导致 弹窗两次出现问题
