### ISSUE TITLE
android4.4.2版本

### ISSUE THREAD

**Issue by wuh876** [yanzhenjie/AndPermission#327]
提示找不到fileprovider
![tim 20180809102058](https://user-images.githubusercontent.com/17919150/43874390-38aa68fc-9bbe-11e8-8ecc-4d65148bd7ca.png)

**Comment by Tianmu19** [comment]
同样遇到问题。华为4.4.2
Unable to get provider com.yanzhenjie.permission.FileProvider:

**Comment by wuh876** [comment]
你在application中加上这个，我试了这样可以了
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(base);
    }

**Comment by yanzhenjie** [comment]
一般是由于方法数超过65535了。
