### ISSUE TITLE
Unable to get provider com.yanzhenjie.permission.FileProvider:

### ISSUE THREAD

**Issue by Tianmu19** [yanzhenjie/AndPermission#328]
华为4.4.2
Unable to get provider com.yanzhenjie.permission.FileProvider:

**Comment by Tianmu19** [comment]
在application中加上这个，我试了这样可以了
@override
protected void attachBaseContext(Context base) {
super.attachBaseContext(base);
MultiDex.install(base);
}

**Comment by yanzhenjie** [comment]
#327
