### ISSUE TITLE
Target 25,华为i7 5.0 oppo R9s 6.0.1 权限检查不弹框，使用时系统提示权限申请 

### ISSUE THREAD

**Issue by cuijianzhi** [yanzhenjie/AndPermission#33]
如题

**Comment by yanzhenjie** [comment]
不弹窗是检测到有权限不弹还是调用了方法不弹，我有点迷糊，看不太懂，请再描述详细一点。
另外，这个issue可能帮助到你：#32

**Comment by cuijianzhi** [comment]
因为5.0小于M嘛，权限检查直接返回true，使用的时候系统弹出了权限申请对话框.

**Comment by yanzhenjie** [comment]
Android 6.0运行时权限，运行时系统版本需要等于高于6.0。系统弹出的是国产手机自己搞的。

**Comment by cuijianzhi** [comment]
该库主要是针对最小版本为23（6.0M）及以上，可以这么理解么？

**Comment by cuijianzhi** [comment]
该库主要是针对原生系统（含M以下）及M（含国产系统）的工具库是么？
