### ISSUE TITLE
【测试发现的两个问题】锤子坚果 pro 和 华为荣耀畅玩4C

### ISSUE THREAD

**Issue by AlanKeene** [yanzhenjie/AndPermission#332]
注：使用的 AndPermission 的版本为 `2.0.0-rc11`
1. 华为荣耀畅玩4C
型号：HUAWEI CHM-TL001
系统版本：Android 5.1.1
API level : 22
问题描述：录音权限申请时，选择拒绝，但还是回调了 onGranted 方法。

2.  锤子坚果 pro：
型号：Smartisan OD 103
系统版本：Android 7.1.1
API level : 25
问题描述： 进入权限设置中手动将录音权限设置为："使用时确认”后，再进入申请权限时会弹出权限申请提示对话框，但 点击 “允许” 后，权限状态不生效，进入权限设置查看权限状态仍为：“使用时确认”。没有变成“允许状态”。点击 “拒绝”亦同样，权限状态没有改变。需要去权限设置中手动设置方可正常。

**Comment by yanzhenjie** [comment]
第一个问题回复：
Api level 23以下，申请权限时是使用了启动录音来触发权限申请框，完毕时如果报错则认为没有权限，如果没报错则认为有权限。你的反馈中我猜测可能是两个问题，1是没有权限，但是该手机并没有报错，这个是真的没办法，2是虽然点了拒绝，可能是有权限的，你可以直接录音试试。
第二个问题回复：
该手机在权限框点击允许和拒绝均没有用，因此可以判断是手机本身的原因，须在设置中开启权限。

**Comment by AlanKeene** [comment]
第一个问题：确实没有捕获到报错日志
2. 像这种情况，想问一下你们一般是怎么处理这种兼容性问题的呢？

**Comment by yanzhenjie** [comment]
第一个问题，你看看文档，有个特别说明，认真看完就明白了。
第二个问题，没有好方法可以拿到准确的状态，还是按照文档那样写，不会让你崩溃掉。

一定要认真看完文档。
