### ISSUE TITLE
分享视频到微信提示 无法导入

### ISSUE THREAD

**Issue by coolBreezes** [yanzhenjie/AndPermission#337]
群主，您好，
使用系统自带的Intent.ACTION_SEND 分享文件，适配android7.0，FileProvider后分享到微信，提示“导入失败”，适配FileProvider之前功能是正常的，并且只有微信有这个问题，其他通过qq、钉钉分享都是正常的，

另外我想请教下，不需要再manifest中设置Provider么
` <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>`

感谢群主

**Comment by yanzhenjie** [comment]
应该是没问题的，这边测试了安装apk，分享照片到系统自带的一些应用都可以，微信倒是没测试。是不是微信的问题就不知道了，或者可能是缓存引起的，你换一台手机或者卸载微信重装后再试试。

另外不需要注册上述Provider。

**Comment by yanzhenjie** [comment]
那应该是微信的问题吧？

**Comment by coolBreezes** [comment]
这个还不清楚，群主，你有时间可以试下，看看是不是MIUI机型适配的问题

**Comment by mazhenlei** [comment]
我也遇到同样的问题 我怀疑是不是视频太大导致的
