### ISSUE TITLE
android 8.1.0 上申请多个权限只弹出后一个权限授权提示框

### ISSUE THREAD

**Issue by clarkshu1016** [yanzhenjie/AndPermission#339]
申请了2个权限，一个是  READ_PHONE_STATE，一个是ACCESS_COARSE_LOCATION，但是只弹出第二个地理位置授权提示框,在7.1.0测试正常。
手机Nexus5x ，版本号:8.1.0 
 yanzhenjiePermission = 'com.yanzhenjie:permission:2.0.0-rc12'

AndPermission.with(AdListActivity.this)
                .runtime()
                .permission(Permission.READ_PHONE_STATE)
                .permission(Permission.ACCESS_COARSE_LOCATION)
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                    }
                }).onDenied(new Action<List<String>>() {
            @Override
            public void onAction(List<String> data) {
            }
        }).start();

**Comment by yanzhenjie** [comment]
前一个权限可能是已经有了。

**Comment by vanshu** [comment]
反复测过了，nexus5x 7.1.2 ，8.1.0 ，和小米mi4  7.1.0 都是只弹出一个提示框，即地理位置获取提示框，并没有弹出 获取手机信息权限提示框，我移除了.permission(Permission.ACCESS_COARSE_LOCATION)
地理位置权限后，就会弹出获取手机信息提示框，不知道什么原因不能共存。
另外在manifest 也已经添加ACCESS_COARSE_LOCATION和READ_PHONE_STATE
