### ISSUE TITLE
不支持多进程授权

### ISSUE THREAD

**Issue by lizhiwei92** [yanzhenjie/AndPermission#340]
PermissionActivity默认注册在主进程，需要再另外的进程中请求权限时，将收不到授权结果，忘改进，谢谢。

**Comment by doyee** [comment]
Yes，这个问题我也遇到了，

> PermissionActivity默认注册在主进程，需要再另外的进程中请求权限时，将收不到授权结果，忘改进，谢谢。

等待改进

**Comment by jspz1111** [comment]
这个问题主要原因是AndPermission框架设计是使用一个无视图的PermissionActivity做为权限处理的组件，而Activity是侵入式的，有自己的进程，解决办法需要参考RxPermission设计，摈弃使用Activity，而使用一个无视图的Fragment作为媒介。（Glide的生命周期管理同样用了这个小技巧）

**Comment by zhangzheng567** [comment]
请问一下，这个还改进吗？
