### ISSUE TITLE
ViVO X9S 7.1.0 定位权限拒绝后，没有第二次提示

### ISSUE THREAD

**Issue by MyWdq** [yanzhenjie/AndPermission#341]
1.首页启动定位权限
2.拒绝
3.无任何提示了

其他手机可以有一个自定义的弹框，再次拒绝还会提示跳转到设置页的弹框
有没有人遇到过

**Comment by yanzhenjie** [comment]
二次提示是指rationable的会掉吗？有一部分手机rationable的状态不准。
这种问题很常见，不是什么大问题，你可以在拒绝中提示用户，最好按照文档的教程来做。
