### ISSUE TITLE
相机权限判断有问题

### ISSUE THREAD

**Issue by lizhiwei92** [yanzhenjie/AndPermission#342]
相机权限判断有问题
机型：三星s8  android 7.0
跳转权限详情页查看，发现已勾选相机权限。
并且用ContextCompat去判断相机权限，返回结果是已有权限。

**Comment by yanzhenjie** [comment]
根据你的描述，没看出来是什么问题。

**Comment by lizhiwei92** [comment]
先回调了onGranted，后回调了onDenied

**Comment by yanzhenjie** [comment]
看一下文档的特别描述一章。

**Comment by lizhiwei92** [comment]
没找到，在哪里，有需要特别注意的？

**Comment by lizhiwei92** [comment]
ok，onGranted被try catch了，出现异常的话会回调onDenied。
感觉没有必要这么处理呀。。。
出问题了排查半天

**Comment by yanzhenjie** [comment]
这个原因在文档中有写，配合文档使用。

**Comment by lizhiwei92** [comment]
read me只有简单几句话，文档链接发一下？
