### ISSUE TITLE
service

### ISSUE THREAD

**Issue by xiansenxuan** [yanzhenjie/AndPermission#346]
在 Service 中使用 传递 this或者Application context
都会走 onGranted然后走onDenied

**Comment by yanzhenjie** [comment]
注意查看日志，另外看下中文文档的特别说明。

**Comment by xiansenxuan** [comment]
http://www.yanzhenjie.com/AndPermission/cn/
挂掉了

**Comment by xiansenxuan** [comment]
已解决
