### ISSUE TITLE
8.0和8.1的系统均无法获得权限（已在Nokia 7 和mate 9上复现）

### ISSUE THREAD

**Issue by phypy** [yanzhenjie/AndPermission#347]
大大您好：
使用rc12版本，发现在Nokia 7（android 8.1.0）和华为mate 9(android 8.0) 手机上复现。
申请的权限为 存储空间和拍照。
具体表现为申请权限的对话框中选择同意后 会弹出窗口提示 【相机 存储空间】 权限被拒绝，点确定后进入设置，发现权限都是正常开着的。

**Comment by yanzhenjie** [comment]
此时你试试读写SD卡和打开相机，看看会不会报权限异常。如果没有报异常，那可能是权限状态检查异常了。

**Comment by phypy** [comment]
太抱歉了大大，没有仔细研究就提上来。
这个问题已经解决问题，是由于文件的provider的原因。
