### ISSUE TITLE
有android.support.v4.app.Fragment中使用的例子吗？

### ISSUE THREAD

**Issue by muzili0712** [yanzhenjie/AndPermission#35]
我想问一下在`android.support.v4.app.Fragment`怎样使用？能不能写个例子？我用了报这个错误：
> E/AndPermission: Not found the callback method, do you forget @PermissionYes or @permissionNo for callback method ? Or you can use PermissionListener.

**Comment by yanzhenjie** [comment]
首先对你有个建议，以后提问的时候标题尽量减短概括，内容中描述问题，注意内容格式。  
fragment和activity中使用并无区别，只是注意回调的时候的方法，一个是注解的方法，一个是listener的方法，参考demo。

**Comment by muzili0712** [comment]
sorry  找到了解决的方法 只是在demo里面没有对于android.support.v4.app.Fragment 的例子 现在的demo只有 AppCompatActivity 这个的方法 调用时候容易混乱了
    public void getPermissions(Fragment fragment, final EventView view, final int code, String... permissions)
    {
        // 申请多个权限。
        AndPermission.with(fragment).requestCode(code).permission(permissions)
                .rationale(new RationaleListener()
                {
                    // rationale作用是：用户拒绝一次权限，再次申请时先征求用户同意，再打开授权对话框，避免用户勾选不再提示。
                    @Override
                    public void showRequestPermissionRationale(int requestCode, Rationale rationale)
                    {
                        // 这里的对话框可以自定义，只要调用rationale.resume()就可以继续申请。
                        view.onShowPermissionsDialog(code);
                    }
                }).send();
    }

之前一直是AndPermission.with()这里面传的都是AppCompatActivity   而在fragment中是要传Fragment的


最后  谢谢群主的及时解答
