### ISSUE TITLE
为什么onGranted方法会被调用两遍

### ISSUE THREAD

**Issue by futurelc** [yanzhenjie/AndPermission#352]
同时申请了Permission.READ_PHONE_STATE, Permission.WRITE_EXTERNAL_STORAGE两个权限，都同意后，为什么会掉用两次onGranted方法，这样影响了我后续准备做的逻辑。
 String permission[] = {Permission.READ_PHONE_STATE, Permission.WRITE_EXTERNAL_STORAGE};
        AndPermission.with(context)
                .runtime()
                .permission(permission)
                .rationale(new RuntimeRationale())
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                        Log.d("pe", "onGranted!!!!");
                    }
                })
                .onDenied(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                        Log.d("pe", "onDenied!!!!");
                    }
                }).start();

**Comment by yanzhenjie** [comment]
只会调用一遍，申请不要写在onResume中。

**Comment by futurelc** [comment]
> 只会调用一遍，申请不要写在onResume中。

very thanks for you

**Comment by Jameni** [comment]
> 只会调用一遍，申请不要写在onResume中。

谢谢！！！
