### ISSUE TITLE
手动关闭相机权限后，低版本手机判断不了是否有权限

### ISSUE THREAD

**Issue by xiemobiao** [yanzhenjie/AndPermission#356]
严大,我手动关闭相机权限后，执行不了onDenied这个方法,用这个方法AndPermission.hasPermissions(getActivity(),Permission.Group.CAMERA)判断是否有权限一直打印true，手机是三星的一款手机，版本是4.3

**Comment by yanzhenjie** [comment]
国产手机请严格按照中文文档来做，不要使用`AndPermission#hasPermissions(Context, ...)`方法。  
`Android4.3`不支持运行时权限，返回true是正确的。

**Comment by xiemobiao** [comment]
好的
