### ISSUE TITLE
检查相机权限耗时在400ms左右，读写权限只要30ms

### ISSUE THREAD

**Issue by dota2fans** [yanzhenjie/AndPermission#358]
09-28 09:47:33.241 11811-11811/com.datedu.pptAssistant I/hqq:  
    main, onAction(PermissionUtils.java:111)
    用时: 28
09-28 09:47:43.528 11811-11811/com.datedu.pptAssistant I/hqq:  
    main, onAction(PermissionUtils.java:111)
    用时: 407

**Comment by yanzhenjie** [comment]
有这个情况，你想说什么问题或者有什么可以帮到你的？

**Comment by dota2fans** [comment]
有什么办法可以缩小这个时间吗，打开相机有明显卡顿

**Comment by yanzhenjie** [comment]
暂时做不到了，目前已经优化到最少了，不然就兼容不了有些国产机了。
