### ISSUE TITLE
红米 MIUI10 8.8.9开发版 Android7.1.2，选择「不再询问」并拒绝，有BUG

### ISSUE THREAD

**Issue by ChenJia-X** [yanzhenjie/AndPermission#360]
从设置中回来后，在onComeback（）中再次发起权限申请，无法检测到获取了权限。AndPermission.hasAlwaysDeniedPermission（）会一直返回True

**Comment by yanzhenjie** [comment]
根据你的描述，这是正确的。

**Comment by ChenJia-X** [comment]
我之前描述不够具体，可能误导了您，我再补充一点
AndPermission.hasAlwaysDeniedPermission()是在onDenied()的回调中调用，也就是说，即使在设置中授予了权限，回来后（在onComeback（）中再次发起权限申请），仍旧无法检测到获取了权限

![image](https://user-images.githubusercontent.com/29827609/46240571-325d5900-c3dc-11e8-8143-d4a78ad7a5df.png)

**Comment by yanzhenjie** [comment]
你可以把没有的权限打印出来看看，比如说没有写入SD卡的权限，那么你做一个写入SD卡的操作看看是否能写入，如果能写入那就是AndPermisison检测错误，如果不能写入就是系统显示的状态错误，因为现在有很多这样的情况。

**Comment by yanzhenjie** [comment]
No response, close.
