### ISSUE TITLE
java.lang.AssertionError: This should not be the case

### ISSUE THREAD

**Issue by wanghailong0526** [yanzhenjie/AndPermission#365]
java.lang.AssertionError: This should not be the case.com.yanzhenjie.permission.PermissionActivity.onCreate(PermissionActivity.java:164)android.app.Activity.performCreate(Activity.java:6280)android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)android.app.ActivityThread.-wrap11(ActivityThread.java)android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)android.os.Handler.dispatchMessage(Handler.java:102)android.os.Looper.loop(Looper.java:148)android.app.ActivityThread.main(ActivityThread.java:5420)java.lang.reflect.Method.invoke(Native Method)com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)	1538453031662	5	1.0.5	77e6e58c973590b9	lge	Nexus 4	en	6.0.1	23	GP	768	1184

**Comment by yanzhenjie** [comment]
该`Activity`只允许AndPermission内部调用，是不会走到这里的，如果是外部调用是会报这个错。
