### ISSUE TITLE
授权之后，从设置权限管理中取消授权，仍然会显示授权并回调onGranted

### ISSUE THREAD

**Issue by zhxhcoder** [yanzhenjie/AndPermission#367]
授权之后，从设置权限管理中取消授权，仍然会显示授权并回调onGranted
以相机权限为例，测试手机小米6x，取消授权后错误回调onGranted # @yanzhenjie

**Comment by ysbing** [comment]
这个手机比较特殊？可否帮忙用我写的库测测这个问题，谢谢https://github.com/ysbing/YPermission

**Comment by ysbing** [comment]
> 授权之后，从设置权限管理中取消授权，仍然会显示授权并回调onGranted
> 以相机权限为例，测试手机小米6x，取消授权后错误回调onGranted # @yanzhenjie

这个手机比较特殊？可否帮忙用我写的库测测这个问题，谢谢https://github.com/ysbing/YPermission

**Comment by yanzhenjie** [comment]
@zhxhcoder 听说小米手机设置中的权限管理无用，需要调用App原生管理页面，或者开启MIUI优化才会起作用。

早一点的小米，调用App原生管理无用，小米自带管理有用，目前我也比较纠结，要做充分的测试方才可以。

**Comment by yizuochengchi** [comment]
的确 建议双重判断 然后跳转 @zhxhcoder

**Comment by yizuochengchi** [comment]
`                  @Override
                    public void onGranted(List<String> permissions) {
                        AtomicBoolean aBoolean = new AtomicBoolean(true);
                        for (int i = 0; i < permissions.size(); i++) {
                            if (!AndPermissionUtils.selfPermissionGranted(this, permissions.get(i))) {
                                aBoolean.set(false);
                            }
                        }
                        if (aBoolean.compareAndSet(true, false)) {
                            takePicture();
                        } else {
                           toast("需要开启拍照权限");
                            AndPermissionUtils.gotoPermissionManager(this);//跳转开启
                        }
                    }
`
