### ISSUE TITLE
反射异常

### ISSUE THREAD

**Issue by authordinary** [yanzhenjie/AndPermission#37]
System.err: java.lang.reflect.InvocationTargetException
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.yanzhenjie.permission.AndPermission.callbackAnnotation(AndPermission.java:344)
System.err:     at com.yanzhenjie.permission.AndPermission.onRequestPermissionsResult(AndPermission.java:284)
最后问题定位到
 AndPermission.onRequestPermissionsResult(this, requestCode, permissions, grantResults);

**Comment by yanzhenjie** [comment]
Use new version.
