### ISSUE TITLE
在一些国产手机上不执行申请权限这个方法

### ISSUE THREAD

**Issue by guzhaohui** [yanzhenjie/AndPermission#372]
360 1607-A01、魅蓝Note6、oppor9 tm、vivo Xplay5A 目前反馈的有这些，不执行权限申请的方法，打断点显示没往方法里走。不知道怎么回事，希望博主有时间的时候能够看一下。

**Comment by yanzhenjie** [comment]
不执行申请权限的方法指的是什么？

**Comment by Jameni** [comment]
现在手机系统基本都是定制的，现在的框架都只能尽量兼容更多手机，不管用什么框架，都很难百分百，所以博主，加油，支持你的框架。

**Comment by guzhaohui** [comment]
> 不执行申请权限的方法指的是什么？

就是没有权限的情况下，打开APP，在需要访问权限的页面没有反应，没有运行AndPermission的方法。不执行申请，也没有提示。

**Comment by yanzhenjie** [comment]
没执行AndPermission的方法，是指没有运行到执行AndPermission的代码的地方吗？如果执行了，至少会有一个回调， @guzhaohui 在上面列举的手机都有测试通过，初步判断是 @guzhaohui 的逻辑问题。
