### ISSUE TITLE
DoubleChecker 似乎需要改进

### ISSUE THREAD

**Issue by stonyz** [yanzhenjie/AndPermission#374]
问题： 我在 onResume请求Camera权限，并获取。然后开启摄像头。 切换app到后台，再切换到前台，故再次执行onResume检查权限；这时候因为Camera正在被当前应用使用，故CameraTester返回false。

这个地方是否可以做些改进？ 目前我也没有什么好的建议，。

**Comment by yanzhenjie** [comment]
`onStop()`时为什么不停止相机呢，是否有什么特殊需求？

**Comment by yanzhenjie** [comment]
这个只是逻辑问题，你改一下你的逻辑就可以兼容，例如判断这个功能正在运行就不用请求权限，例如`onStop()`时要释放相机等。
