### ISSUE TITLE
up主你好，好像有bug

### ISSUE THREAD

**Issue by jingzz1** [yanzhenjie/AndPermission#375]
同时申请两个权限组的权限，其中一个权限组同意授权，另一个权限组拒绝权限但没点击不再提示，这个时候如果调用AndPermission.hasAlwaysDeniedPermission（）判断这个被拒绝的权限是否选择不再提示，会返回true，
目前测试的手机：vivo y66(android6.0) ，vivo X21(android8.1)，华为P20 Pro(android8.1 )，华为P10(android 7.0)，努比亚z11 minis(android6.0) 都有这种问题

**Comment by jingzz1** [comment]
不过我调用系统方法 ActivityCompat.shouldShowRequestPermissionRationale(context,permission) ，结果却是正常的

**Comment by yanzhenjie** [comment]
1. `AndPermission.hasAlwaysDeniedPermission()`必须传入已经被拒绝的权限。
2. `ActivityCompat.shouldShowRequestPermissionRationale(context,permission) `可以传入已经拒绝的或者没有被拒绝的权限。

上方的1中，传入的权限默认是已经拒绝的，然后调用`shouldShowRequestPermissionRationale()`方法如果返回`false`，说明是一直拒绝的权限，返回`true`，说明不是已经拒绝并且已经拒绝过一次。

上方的2中，返回`false`时表示该权限可能是一直拒绝的或者已经同意的或者位请求过的，返回`true`时表示该权限被拒绝过至少一次并没有勾选不再提示。

在这个前提下，你再做一下测试，把结果反馈一下。

**Comment by jingzz1** [comment]
重新测试了一次，没发现问题，然后看我之前写的代码，发现我调用了两次onDenied，不知道是不是这个原因导致错误

**Comment by jingzz1** [comment]
重新测试了一次，没发现问题，然后我看之前写的，发现我调用了两次onDenied，不知道是不是这个原因导致的错误
