### ISSUE TITLE
有时候出现一只申请不到权限的问题

### ISSUE THREAD

**Issue by lxhtiamo** [yanzhenjie/AndPermission#377]
我的平板是安卓7.1.2 的,但是我的应用中 targetSdkVersion  22   ,是5.1的   用这个框架申请有时候 一直提示我相机没有权限,跳转查看权限已经自动开启了 然后重新关闭又开启相机权限还是提示没有.有时候又不提示相机权限问题..........很奇怪.......

**Comment by yanzhenjie** [comment]
targetSdkVersion就别用权限申请框架了呀，根据你的提供的信息，我也无法判断。
