### ISSUE TITLE
弹出授权框后，旋转屏幕，点击授权/拒绝按钮，报NullPointerException

### ISSUE THREAD

**Issue by xjunz** [yanzhenjie/AndPermission#378]
java.lang.NulPointerException: Attempt to invokevirtual method 'android.content.pm.PackageManager

android.content.Context.getPackageManager()' on a null object referenceat

com.yanzhenjie.permission.source.ContextSource.isShowRationalePermission(ContextSource. java:73)at

com.y anzhenjie.permission.AndPermiss ion.hasAlwaysDeniedPermiss on( AndPerrmission. java:152)at

com.yanzhenjie.permission.AndPermission.hasAlwaysDeniedPermiss ion(AndPermission. java: 144)

      at

com.example. ui.setup.fragment.ApplicationPermiss ionFragment$ 1.onAction( ApplicationPermiss ionFragment.java:76)

**Comment by yanzhenjie** [comment]
应该是你的代码报的错吧：
```java
ApplicationPermiss ionFragment.java:76
```
