### ISSUE TITLE
小米手机,系统都到10.0了，然而你的RuntimeSettingPage的判断还只到8.。

### ISSUE THREAD

**Issue by houwei14350** [yanzhenjie/AndPermission#379]
private static Intent xiaomiApi(Context context) {
        String version = getSystemProperty(MIUI_VERSION_NAME);
        if(TextUtils.isEmpty(version) || version.contains("7") || version.contains("8")) {
            Intent intent = new Intent("miui.intent.action.APP_PERM_EDITOR");
            intent.putExtra("extra_pkgname", context.getPackageName());
            return intent;
        }
        return defaultApi(context);
    }

**Comment by yanzhenjie** [comment]
有什么问题吗？

**Comment by yanzhenjie** [comment]
No reponsed, closed.
