### ISSUE TITLE
多个权限授权成功之后，然后手动的去关闭所申请的权限，下次进入app不会再次询问，而是默认拥有该权限

### ISSUE THREAD

**Issue by itgoyo** [yanzhenjie/AndPermission#38]
多个权限授权成功之后，然后手动的去关闭所申请的权限，下次进入app不会再次询问，而是默认拥有该权限@PermissionYes方法会回调，不是说有一个权限不成功就不走此方法么

**Comment by yanzhenjie** [comment]
是什么手机？Android系统版本是多少？
我推测，这个应该是国产机的权限管理bug，你可以参考这个issue：#31

**Comment by yanzhenjie** [comment]
No Response close.
