### ISSUE TITLE
项目介绍链接无法打开

### ISSUE THREAD

**Issue by shikechen** [yanzhenjie/AndPermission#380]
https://www.yanzhenjie.com/AndPermission
无法访问此网站 找不到 www.yanzhenjie.com 的服务器 IP 地址

http://yanzhenjie.github.io/AndPermission
无法访问此网站 网址为 http://yanzhenjie.github.io/AndPermission 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by yanzhenjie** [comment]
之前在备案，现在可以访问了。
