### ISSUE TITLE
Android 8.0以上overlay权限有bug

### ISSUE THREAD

**Issue by YoungBill** [yanzhenjie/AndPermission#381]
经测试发现,Android 8.0以上overlay权限有如下bug.
在授予overlay权限之后,第一次返回竟然还是回调onDenied

难道这个问题就没人发现吗?

调试代码发现,应该是dispatchCallback这个方法出了问题
根本原因在于,这是Android 0的系统bug,在stack上找到解决方案.
做了如下修改

```java
    private void dispatchCallback() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            if (tryDisplayDialog(mSource.getContext())) {
                callbackSucceed();
            } else {
                callbackFailed();
            }
        } else {
            if (mSource.canDrawOverlays() && tryDisplayDialog(mSource.getContext())) {
                callbackSucceed();
            } else {
                callbackFailed();
            }
        }
    }
```

我们手上有六七台手机,改了代码之后,就没有那个问题了,你看看是否在下个版本改改

**Comment by yanzhenjie** [comment]
有在Android上做测试，本来只需要`canDrawOverlays()`方法即可，因为部分手机确实存在**实际没权限但返回有权限**的错误情况，所以加了try做测试，如果真的存在 @YoungBill 描述的情况，AndPermission就可以舍弃系统的`canDrawOverlays()`方法了，回头我会做个验证并发布新版本，也等待其他人的回复。

**Comment by yanzhenjie** [comment]
之前测试时发现，需要开关 开关两次即可拿到准确的状态。
