### ISSUE TITLE
悬浮窗权限问题

### ISSUE THREAD

**Issue by zhoukai0203** [yanzhenjie/AndPermission#382]
android vivo手机8.1系统获取悬浮窗权限一直未true，其实没有设置悬浮窗权限

**Comment by yanzhenjie** [comment]
targetSdkVersion 是多少？另外可能真的可以显示悬浮窗，以实际结果为准，能跑通业务既没问题。

**Comment by zhoukai0203** [comment]
28最新的api，就是vivo问题多，其他机型可以，已经影响业务了

**Comment by yanzhenjie** [comment]
返回true后，导致不能显示悬浮穿还是？

**Comment by zhoukai0203** [comment]
框架认为已经获取到了悬浮窗权限，但是实际上手动去设置里面看，权限还是关闭的 vivo y85a机型

**Comment by yanzhenjie** [comment]
使用的SDK的api检查，而且加了悬浮窗显示测试，如果还获取不到失败状态，那这个手机真是没办法了，你可以自己做一些测试，把有效结果反馈一下，或者提交PR。

**Comment by zhoukai0203** [comment]
好的，对于vivo神机，我也是没有办法，神机太坑了
