### ISSUE TITLE
大神你好，我这关联远程库后编译不通过

### ISSUE THREAD

**Issue by jiangzehui** [yanzhenjie/AndPermission#383]
关联这个库后 implementation 'com.yanzhenjie:permission:2.0.0-rc12'
运行安装APP会报如下错误，不关联就没有任何问题。。咋办呀。。

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\0.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\1.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\2.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\3.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\4.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\5.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\6.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\7.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\8.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\9.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\10.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\11.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\12.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\13.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\14.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\15.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\16.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\17.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\18.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\19.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\20.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\21.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\22.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\23.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\24.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\25.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\26.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\27.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\28.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\29.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\30.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\31.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\32.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\33.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\34.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\35.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\36.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\37.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\38.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\39.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\40.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\41.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\42.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\43.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\44.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\45.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\46.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\47.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\48.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\49.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\50.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\51.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\52.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\53.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\54.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\55.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\56.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\57.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\58.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\59.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\60.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\61.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\62.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\63.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\64.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\65.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\66.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\67.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\68.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\69.jar, F:\AndroidWorkSpace\zhuineng_new218\app\build\intermediates\transforms\dexBuilder\debug\70.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s

**Comment by yanzhenjie** [comment]
具体原因看不出来，主要从这句话入手，你再查一下吧：
```
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
```

**Comment by jiangzehui** [comment]
通过./gradlew dependencies app:dependencies查了一下依赖关系
发现 您的库依赖了 com.android.support:support-fragment:27.1.1 
然后我把这个support排除掉后，问题解决。

debugImplementation ('com.yanzhenjie:permission:2.0.0-rc12') {
        exclude module: 'support-fragment'
 }
