### ISSUE TITLE
由于连续启动录音器会存在失败的情况，所以反复调用这里的录音权限判断会经常出现一次判断有录音权限紧接着又判断为无录音权限的情况

### ISSUE THREAD

**Issue by yychai** [yanzhenjie/AndPermission#385]

**Comment by cdye0000** [comment]
遇到了同样的问题，现象出现在360手机上，其他手机未发现问题

**Comment by yychai** [comment]
这个问题好多手机都会出现的，之前做录音相关的功能有出现这个问题

**Comment by lazh** [comment]
我这里再华为，小米的手机上也碰到了此问题，概率性出现

**Comment by lazh** [comment]
> 这个问题好多手机都会出现的，之前做录音相关的功能有出现这个问题

这个问题你现在是怎么处理的

**Comment by yychai** [comment]
没有怎么处理，这个是系统的一个问题，我现在用的是简单的权限判断，没有启动录音器来真正验证权限了
