### ISSUE TITLE
PermissionActivity 需要适配刘海屏

### ISSUE THREAD

**Issue by ezfantasy** [yanzhenjie/AndPermission#386]
compileSdkVersion 是28时，需要适配刘海屏的statusBar颜色为透明，否则申请权限弹出PermissionActivity 时 会把在上一面页面的状态栏颜色给覆盖调，造成给人闪一下的错觉。

**Comment by ezfantasy** [comment]
compileSdkVersion 是28，且app是跑在Android P版本机型上

**Comment by yanzhenjie** [comment]
刚发布的2.0.0正式版本已经解决了这个问题。
