### ISSUE TITLE
android8.0安装

### ISSUE THREAD

**Issue by newlai913** [yanzhenjie/AndPermission#389]
up是不是可以把安装的方法开放出来让我们自己处理呢

**Comment by yanzhenjie** [comment]
经过慎重的考虑，决定还是统一集成到一起，如果想自己处理的话，还是自己写一套吧，安装的这个逻辑也很简单，拆开后就不完整了。另外，目前的做法，拆开后对于使用之前版本的开发者存在兼容问题。
