### ISSUE TITLE
android.permission.MANAGE_DOCUMENTS判断，开始无效

### ISSUE THREAD

**Issue by tangnuo** [yanzhenjie/AndPermission#39]
AndPermission.hasPermission()对android.permission.MANAGE_DOCUMENTS权限判断，开启无效。

**Comment by yanzhenjie** [comment]
非运行时权限，具体请参考：[Android 6.0 运行时权限管理最佳实践](http://blog.csdn.net/yanzhenjie1003/article/details/52503533)
