### ISSUE TITLE
部分定制设备权限列表里没有READ_PHONE_STATE权限，导致申请权限出现问题

### ISSUE THREAD

**Issue by cosplay-wang** [yanzhenjie/AndPermission#392]
部分定制设备权限列表里没有READ_PHONE_STATE权限，导致申请权限出现问题
例如：读书郎平板，我之前在分支还是哪里看到过
 public static boolean checkPhoneState(Context context){
        TelephonyManager service = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
        //return !TextUtils.isEmpty(service.getDeviceId()) || !TextUtils.isEmpty(service.getSubscriberId());
        if (service.getPhoneType() == TelephonyManager.PHONE_TYPE_NONE) {
            return true;
        } else {
            return false;
            // return !TextUtils.isEmpty(service.getDeviceId())
            // || !TextUtils.isEmpty(service.getSubscriberId());
        }
    }

类似的判断，无法解决问题

**Comment by yanzhenjie** [comment]
看不懂问题。

**Comment by cosplay-wang** [comment]
大部分的统计  比如友盟 会要求READ_PHONE_STATE 权限。所以 我在打开app的时候 申请了这个权限。
但是部分定制平板，如 读书郎。  在应用的权限列表中没有  获取手机信息这一条。

**Comment by yanzhenjie** [comment]
说问题。

**Comment by cosplay-wang** [comment]
![image](https://user-images.githubusercontent.com/17606832/50394888-8f7a6800-079b-11e9-8024-ec808a3bd42d.png)
在中，点击恢复，进应用的权限详情页。里边没有这个权限。

**Comment by cosplay-wang** [comment]
整个系统都不会暴漏 read_phne_statu 这个，卡在申请权限这了

**Comment by yanzhenjie** [comment]
问题是在上述没有电话模块的设备上获取不到该权限吗？

**Comment by yanzhenjie** [comment]
使用的AndPermission哪个版本？

**Comment by cosplay-wang** [comment]
2.0.0-rc12

**Comment by yanzhenjie** [comment]
这可能是一个bug，我会尽快更新。

**Comment by cosplay-wang** [comment]
好的，有大致的解决思路么。我先简单判断处理一下。

**Comment by yanzhenjie** [comment]
```java
    public boolean supportPhone() throws Throwable {
        PackageManager packageManager = mContext.getPackageManager();
        if (!packageManager.hasSystemFeature(PackageManager.FEATURE_TELEPHONY)) return true;

        TelephonyManager telephonyManager = (TelephonyManager) mContext.getSystemService(Context.TELEPHONY_SERVICE);
        if(telephonyManager.getPhoneType() != TelephonyManager.PHONE_TYPE_NONE) return true;
        return !TextUtils.isEmpty(telephonyManager.getDeviceId())
                || !TextUtils.isEmpty(telephonyManager.getSubscriberId());
    }
```

**Comment by cosplay-wang** [comment]
好的，我会给出反馈结果的

**Comment by cosplay-wang** [comment]
hasSystemFeature 如果没有电话特性，return true？这块和下边的判断反了吧

**Comment by yanzhenjie** [comment]
我看了一下之前的代码是没有问题的，这个地方之前是和步步高的开发同学一起调试的，是没有问题的。

而我后面给你的代码：
```java
if(telephonyManager.getPhoneType() != TelephonyManager.PHONE_TYPE_NONE) return true;
```
这句是把原来正确的逻辑改错了，应该是：
```java
return telephonyManager.getPhoneType() == TelephonyManager.PHONE_TYPE_NONE
    || !TextUtils.isEmpty(telephonyManager.getDeviceId())
    || !TextUtils.isEmpty(telephonyManager.getSubscriberId());
```
