### ISSUE TITLE
第一次申请权限拒绝后的问题

### ISSUE THREAD

**Issue by hegaojian** [yanzhenjie/AndPermission#394]
场景如下：进入首页，第一次申请定位权限，用户不小心拒绝后，怎么触发rationale回调，做弹窗提示让用户再次获取一下，目前是直接进了onDenied方法中
我的代码如下：
  AndPermission.with(this)
                .runtime()
                .permission(Permission.Group.LOCATION)
                .rationale(new RuntimeRationale())
                .onGranted(permissions1 -> {
                    //同意权限了 开始定位
                    mLocationClient.start();
                })
                .onDenied(permissions12 -> {
                    //定位拒绝权限了
                }).start();

**Comment by yanzhenjie** [comment]
rationale的用法适用错误，你可以再认真看一下文档。

**Comment by hegaojian** [comment]
我仔细看您的demo,就是这么写的啊
这是demo上的代码：
/**
     * Request permissions.
     */
    private void requestPermission(String... permissions) {
        AndPermission.with(this)
                .runtime()
                .permission(permissions)
                .rationale(new RuntimeRationale())
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> permissions) {
                        toast(R.string.successfully);
                    }
                })
                .onDenied(new Action<List<String>>() {
                    @Override
                    public void onAction(@NonNull List<String> permissions) {
                        toast(R.string.failure);
                        if (AndPermission.hasAlwaysDeniedPermission(MainActivity.this, permissions)) {
                            showSettingDialog(MainActivity.this, permissions);
                        }
                    }
                })
                .start();
    }

**Comment by yanzhenjie** [comment]
用法适用错误，也就是说你理解错啦，还是看看文档吧。
