### ISSUE TITLE
某些国产手机，权限验证失败

### ISSUE THREAD

**Issue by yuchangliang** [yanzhenjie/AndPermission#395]
这个框架能判断6.0以下的手机嘛？我尝试用你的框架判断6.0以下的手机，某些国产手机(比如酷比，联想，魅族，金立，vivo ，华硕，青橙 等)，多集中在5.0系统中。判断READ_EXTERNAL_STORAGE 和 WRITE_EXTERNAL_STORAGE 失败，运行你的demo，toast提示failure（权限管理中已开启这些权限）。

**Comment by aileelucky** [comment]
这个问题还有，还蛮多机型的，系统主要是5.1.x
![tim 20190128113020](https://user-images.githubusercontent.com/8519658/51813209-1ddc8f00-22f0-11e9-9677-53704c7e7db3.png)

**Comment by brady2037** [comment]
使用5.1 Lollipop版本studio上的模拟器，READ_EXTERNAL_STORAGE权限总是验证失败，打了下断点，StorageReadTest下test()中，lastModified()方法结果总是为0导致的
![断电截图](https://cdn.jsdelivr.net/gh/brady2037/ImageHosting@master/uPic/WX20200117-174317@2x.png)
