### ISSUE TITLE
Unable to get provider com.yanzhenjie.permission.FileProvider

### ISSUE THREAD

**Issue by yuchangliang** [yanzhenjie/AndPermission#396]
我们在很多种手机运行，发现了如下错误：java.lang.RuntimeException: Unable to get provider com.yanzhenjie.permission.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.permission.FileProvider" on path: DexPathList[[zip file "/data/app/com.open.face2facestudent-1.apk",

**Comment by yanzhenjie** [comment]
#327
