### ISSUE TITLE
v4版本的库太高，下载库不方便

### ISSUE THREAD

**Issue by zhangzzqq** [yanzhenjie/AndPermission#4]
Error:(13, 13) Failed to resolve: com.android.support:support-v4:24.2.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/Administrator/Desktop/AndPermission-master/AndPermission-master/permission/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

下载这个v4库本地需要一个小时（已经在google 下载中加入的腾讯镜像，显示的每秒十几k，太慢了）

**Comment by yanzhenjie** [comment]
Google官网的sdk更新，秒秒钟。
