### ISSUE TITLE
Unable to get provider com.yanzhenjie.permission.FileProvider

### ISSUE THREAD

**Issue by Jelly0726** [yanzhenjie/AndPermission#400]
23974 | Error | AndroidRuntime | java.lang.RuntimeException: Unable to get provider com.yanzhenjie.permission.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.permission.FileProvider" on path: DexPathList[[zip file "/system/framework/org.simalliance.openmobileapi.jar", zip file "/data/app/com.shadow.seewashed-1.apk", zip file "/data/data/com.shadow.seewashed/code_cache/secondary-dexes/com.shadow.seewashed-1.apk.classes2.zip", zip file "/data/data/com.shadow.seewashed/code_cache/secondary-dexes/com.shadow.seewashed-1.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/com.shadow.seewashed-1, /vendor/lib, /system/lib]]

在

**Comment by Jelly0726** [comment]
在application中加入这个方法也不行  
 @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(base);
    }

**Comment by yanzhenjie** [comment]
#327
