### ISSUE TITLE
androidx.fragment.app.Fragment 问题 2.0.0最新版

### ISSUE THREAD

**Issue by chaozhiguang** [yanzhenjie/AndPermission#401]
你用的是 androidx.fragment.app.Fragment   我没用这个jar  引入 会报其他错误   楼主兼容性能不能做一下啊

**Comment by yanzhenjie** [comment]
添加AndroidX Library的fragment即可：
'androix.fragment:fragment:1.0.0'

如果不想使用AndroidX，稍后我会把含Support Library的版本推到Master分支。现在已经在Dev分支了，只是远程依赖还未通过审核，可以依赖源码使用。
