### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by niemj** [yanzhenjie/AndPermission#405]
有没有考虑将“提示用户在系统设置中授权”，放在BridgeActivity中调用，onActivityResult也在BridgeActivity，然后统一回调结果，这样不需要在每个用到的Activity/Fragment上调用？

**Comment by yanzhenjie** [comment]
之前就是这样做的，由于会发生回收造成无法回调的问题，2.0正式版取消了。但是目前我想到了另一个方案，下个版本会加上。

**Comment by yanzhenjie** [comment]
你好，跟你反馈一下这个issue的情况。

我想到的新方案我尝试了开发了之后，发现也是行不通的，所以这个目前没有办法，要想做到更加完善，只能用目前这个办法。

**Comment by niemj** [comment]
之前有看过这个https://github.com/mylhyl/AndroidAcp权限框架，尽管兼容性不太好，但小而精悍，真正的一句话搞定。你可以看下思路是否可行。

**Comment by yanzhenjie** [comment]
做法跟我之前废弃的做法的一样，这个做法已经验证过了，不可行。

**Comment by niemj** [comment]
有什么问题了？我用过一段时间感觉还行。。。

**Comment by yanzhenjie** [comment]
你觉得没问题你继续用那个就好了。
