### ISSUE TITLE
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.wmailn.blepen/com.yanzhenjie.permission.bridge.BridgeActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by ZhanRu** [yanzhenjie/AndPermission#413]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.wmailn.blepen/com.yanzhenjie.permission.bridge.BridgeActivity}; have you declared this activity in your AndroidManifest.xml?

同问题 https://github.com/yanzhenjie/AndPermission/issues/72

版本2.0.1
华为荣耀v10 Android9.0

**Comment by moonljt521** [comment]
您解决了么

**Comment by 465857721** [comment]
我也遇到这个问题了华为的

**Comment by yanzhenjie** [comment]
https://yanzhenjie.blog.csdn.net/article/details/51818269  
https://developer.android.com/studio/build/multidex
