### ISSUE TITLE
导入2.0.1报错

### ISSUE THREAD

**Issue by yeluowuhen52** [yanzhenjie/AndPermission#416]
![QQ截图20190314172023](https://user-images.githubusercontent.com/5179916/54345414-fb26ef80-467d-11e9-902e-43c791aebfb7.png)

**Comment by yanzhenjie** [comment]
[https://stackoverflow.com/questions/47589873/aapt2-error-check-logs-for-details](https://stackoverflow.com/questions/47589873/aapt2-error-check-logs-for-details)

**Comment by yeluowuhen52** [comment]
原因找到了，严大的框架compileSdkVersion 是28，我这边把项目compileSdkVersion 升级到28就不报错了！
