### ISSUE TITLE
OnePlus 5t 申请打电话权限，返回 “Successful”，可这时是没有权限的

### ISSUE THREAD

**Issue by xue12311** [yanzhenjie/AndPermission#419]
OnePlus 5t 申请打电话权限，第一次会弹出提示框，当用户拒绝后（没有选择不再提醒），下次再进去申请时就一直是返回 “Successful”，可是用户并没有打电话的权限

**Comment by yanzhenjie** [comment]
[http://yanzhenjie.com/AndPermission/cn/runtime/explain.html](http://yanzhenjie.com/AndPermission/cn/runtime/explain.html)
