### ISSUE TITLE
通知类短信权限

### ISSUE THREAD

**Issue by cyqluowang** [yanzhenjie/AndPermission#42]
这种类型的权限有办法知道有没有打开么？好像授权是没有方式的，只有设置界面小米，华为直接不能设置

**Comment by yanzhenjie** [comment]
短信是权限是运行时全线，你可以看看这篇文章，先要分清楚什么权限是运行时权限：[Android6.0 运行时全线最佳实践](http://blog.csdn.net/yanzhenjie1003/article/details/52503533)。

**Comment by smarxpan** [comment]
@yanzhenjie 并非如此，他问的是通知短信权限的申请，MIUI把短信分为了通知短信和普通短信，普通短信对应的就是一般短信权限的申请，而通知短信的权限无法申请（MIUI会默认拒绝该权限）。

**Comment by cyqluowang** [comment]
你可以试下小米华为哦

**Comment by yanzhenjie** [comment]
明白了，但是本项目只针对Android运行时权限，感谢大家的反馈，学习到了！
