### ISSUE TITLE
Android Q getDevicesId()返回的是空，导致hasPermission判断不正确

### ISSUE THREAD

**Issue by wangrunxiang** [yanzhenjie/AndPermission#425]

**Comment by yorling** [comment]
真巧，我也遇到了，还同一天？
Android Q 在已经打开“电话”权限的情况下，仍判断为未打开。
用谷歌亲儿子EasyPermissions判断是正常的

**Comment by wangrunxiang** [comment]
我已经提了pr了，看看作者要不要merge吧

**Comment by liaohuyu** [comment]
@wangrunxiang 有啥解决办法么  我也遇到了

**Comment by yanzhenjie** [comment]
We classify this issue into the adaptation problem of android10, please track #478 .
