### ISSUE TITLE
oppo r9s 申请权限 没响应

### ISSUE THREAD

**Issue by tielan** [yanzhenjie/AndPermission#43]

**Comment by yanzhenjie** [comment]
多谢反馈，不过你提供的线索不能判断具体问题，请提供一下信息。
1. Android系统版本多少？  
2. 项目targetSdkVersion是多少？  
3. 申请的是什么权限？  
4. 提供下更详细的其它相关描述，以供我为你更精准的分析原因。

**Comment by tielan** [comment]
1.Android 6.0
2. targetSdkVersion 25
3.Manifest.permission.RECORD_AUDIO

//调用方法
 AndPermission.with(SettingActivity.this)
                .requestCode(100)
                .permission(Manifest.permission.RECORD_AUDIO)
                .rationale(new RationaleListener() {
                    @Override
                    public void showRequestPermissionRationale(int requestCode, Rationale rationale) {
                        AndPermission.rationaleDialog(SettingActivity.this, rationale).show();
                    }
                })
                .send();
//调用这个方法 直接返回有权限 我在权限管理里面查看是 “询问”
AndPermission.hasPermission(this, Manifest.permission.RECORD_AUDIO)

**Comment by yanzhenjie** [comment]
很多国产手机返回的状态是错误的，也有可能是系统的Setting中的状态是错误的，如果返回有权限，那么你可以直接执行你的下一步代码试试，我猜是没有问题的。

**Comment by tielan** [comment]
执行 直接奔溃了

**Comment by yanzhenjie** [comment]
了解，我在这里给出了原生的事例代码，你使用这种原生的方法判断一下是否有权限，没有则提示用户去Setting中设置。
`AndPermission`提供了一一个`SettingDialog`可以直接调起App对应的设置页面，具体使用方法你可以看看README。

**Comment by qiaoyhh** [comment]
下载本项目运行，oppo r9s权限申请回调成功了，，但是在设置中权限设置还是禁止的

**Comment by tielan** [comment]
oppo 的权限 被封装了，调用api时系统自动申请的

**Comment by yanzhenjie** [comment]
oppo的锅，国产手机的运行时权限的锅太多了，我快背不动了。另外你们可以参考下这个issue下判断是否有权限：#31，另外如果没有权限可以使用`SettingDialog`来打开系统设置。
