### ISSUE TITLE
夜神模拟器和OPPOR9在使用RxJava下只走onDenied方法

### ISSUE THREAD

**Issue by zzw8421** [yanzhenjie/AndPermission#430]
在系统的设置界面看到该应用已经拥有相机权限 并且在app中可以打开相机  使用RxJava进行延时1秒后弹出相机发现每次相机权限都是授权失败

**Comment by YouthLee** [comment]
惊天大bug，一加5 使用 Retrofit 与 RxJava2 在网络请求回来后进行授权请求（不论什么权限，已经授权的也不行），一直返回永久拒绝！

**Comment by zzw8421** [comment]
是没在主线程内判断  所以显示拒绝     你在把Rxjava切回主线程

**Comment by YouthLee** [comment]
在AndPermission回调的逻辑出错了。。。会直接返回没有权限。这点不太友好
