### ISSUE TITLE
某些手机 比如三星note3 5.1系统 getDeviceId()返回null

### ISSUE THREAD

**Issue by wangrunxiang** [yanzhenjie/AndPermission#432]
![image](https://user-images.githubusercontent.com/10829860/55778012-4ba23900-5ad4-11e9-9886-ee28a5a4a77f.png)，大佬是不是要斟酌一下怎么修改

**Comment by wangrunxiang** [comment]
![image](https://user-images.githubusercontent.com/10829860/55786936-d2acdc80-5ae7-11e9-9ff1-3ccb3e667ab5.png)

**Comment by yanzhenjie** [comment]
#425
