### ISSUE TITLE
老板，内存泄漏了

### ISSUE THREAD

**Issue by NerdAnonymous** [yanzhenjie/AndPermission#436]
Instance of com.yanzhenjie.permission.bridge.RequestExecutor 就是这个线程造成的

**Comment by YouthLee** [comment]
我也遇到这个问题

**Comment by Vanish136** [comment]
我也遇到

**Comment by qsny** [comment]
我也遇到

**Comment by qsny** [comment]
求解决啊老板

**Comment by xiakehe** [comment]
求解决啊

**Comment by ShinyZeng** [comment]
RequestExecutor
```
    @Override
    public void onCallback() {
        synchronized (this) {
            mMessenger.unRegister();
            mRequest.getCallback().onCallback();
            // fix memory leak 
            mMessenger = null;
            mRequest = null;
            notify();
        }
    }
```
mMessage 和 mRequest 持有了Context ，后续没有权限请求之后没有置空导致的泄漏，这里置空解决。
老板看下这样解决行不行

**Comment by haonan1** [comment]
求解决

**Comment by mambahao** [comment]
+1

**Comment by Erichkko** [comment]
2.0.2版本大概什么时候Release呢

**Comment by xiakehe** [comment]
2.0.2版本大概什么时候Release呢

**Comment by Roben1016** [comment]
2.0.2版本大概什么时候Release

**Comment by BrightVan** [comment]
感觉差不多就可以发一版了，这个内存泄露老是出来。

**Comment by YuanTiger** [comment]
我也遇到了这个内存泄漏，请问v2.0.2的Release大概什么时候发布呢？
感谢大大的无私开源！

**Comment by sweet2o09** [comment]
mark一下,期待2.0.2版本严大神的开源库还是挺不错的

**Comment by yqyzxd** [comment]
2.0.3版本依然报出这个问题

**Comment by lujun525** [comment]
作者你好，我用的是2.0.1的support包，加了 mMessenger = null;mRequest = null;这两行代码，可是还是报内存泄露，啥原因啊

**Comment by lujun525** [comment]
> RequestExecutor
> 
> ```
>     @Override
>     public void onCallback() {
>         synchronized (this) {
>             mMessenger.unRegister();
>             mRequest.getCallback().onCallback();
>             // fix memory leak 
>             mMessenger = null;
>             mRequest = null;
>             notify();
>         }
>     }
> ```
> 
> mMessage 和 mRequest 持有了Context ，后续没有权限请求之后没有置空导致的泄漏，这里置空解决。
> 老板看下这样解决行不行

这样加了，我看还是会报呢

**Comment by lujun525** [comment]
我改了两处，一个onCallback处mMessenger = null; mRequest = null; 另一个 mMessenger = new Messenger(mRequest.getSource().getContext(), this);改成mMessenger = new Messenger(mRequest.getSource().getContext().getApplicationContext(), this); 现在是没有泄露了，试了下这两处少任何一处都会有内存泄露，不知道为啥要改第二处
