### ISSUE TITLE
[Bug]Activity重建以后无法再申请权限

### ISSUE THREAD

**Issue by tankjj** [yanzhenjie/AndPermission#438]
1. 在MainActivity中申请权限；
2. 在弹出系统的权限弹框的时候，旋转屏幕，这个时候MainActivity会重建
3. 点击拒绝权限按钮
这个时候，后面再申请权限，只会保存在RequestExecutor中的mQueue里面，RequestExecutor会一直处于waiting状态

**Comment by tankjj** [comment]
我删除了RequestExecutor里面的 wait()/notify()机制，并且删除了synchronized部分，暂时可以测试通过，但是带来的问题是MainActivity一旦重建了，onGrant就不会继续执行了，请问这个有什么好办法解决吗？感觉这是个大坑呀

**Comment by tankjj** [comment]
https://github.com/tbruyelle/RxPermissions/issues/69
另外一个框架RxPermissions的处理方法

**Comment by xie2000** [comment]
周问，有解决方法嘛？

**Comment by yanzhenjie** [comment]
在minifest中为MainActivity添加这个即可解决：
```xml
android:configChanges="orientation"
```
