### ISSUE TITLE
导入后报错

### ISSUE THREAD

**Issue by SwitchDestiny** [yanzhenjie/AndPermission#439]
No resource identifier found for attribute 'appComponentFactory' in package 'android'
Message{kind=ERROR, text=No resource identifier found for attribute 'appComponentFactory' in package 'android', sources=[E:\rnCommercial\AppClient55.4\android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:47], original message=, tool name=Optional.of(AAPT)}

![image](https://user-images.githubusercontent.com/25134250/56257761-f8496f80-60ff-11e9-8752-402ce8ec401c

严大这个改怎么解决啊

**Comment by yanzhenjie** [comment]
I can't help you with your local environment.
