### ISSUE TITLE
小米4 Android6.0.1定位权限问题

### ISSUE THREAD

**Issue by shenxuhui1993** [yanzhenjie/AndPermission#44]
在第一次申请定位权限时，我拒绝了定位权限，然后我去设置里手动开启定位权限，开启app也显示定位权限已经获得，但事实上是没办法定位。然后我在去手动关闭定位权限，重新开启app,可以跳出申请权限的对话框，这样就可以获得定位权限。

**Comment by yanzhenjie** [comment]
你说的这个问题应该和`AndPermissoin`无关了。  
但是你说的这个情况应该会出现，应该是小米的bug吧，建议把targetSdkVersion调为23以下，或者放弃这些手机。

**Comment by SomnusWu** [comment]
同样的问题， 红米Note4  MIUI8.2 稳定版，第一次弹出授权框 ，然后点击拒绝，然后到设置界面，点击打开对应的权限，然后回到app ，走的是成功回调方法，但是实际是不能成功的。比如定位 。 而且重启app   也会认为授权成功、  不知道是不是也就小米有这样的问题 .........  忧伤~

**Comment by yanzhenjie** [comment]
关于国产机的6.0运行时权限的bug，反馈的人实在太多了，我讲的舌头都磨破了。之前还兼容了一部分，现在问题越出越多，因为底层bug反馈的结果错误，我们应用层实在没有办法，系统Setting和我们检测的结果不符合，而且两个结果都是不准的。
在模拟器、Google亲儿子、摩托罗拉等等手机，也就是没改原生的底层权限的手机上都是完美无缺的，在这里只能做Ops判断，然后提醒用户去Setting中设置了。具体判断可以看这个issue：#31
