### ISSUE TITLE
华为手机权限全部打开了，但是无法使用相关功能

### ISSUE THREAD

**Issue by jiemachina** [yanzhenjie/AndPermission#441]
1. 本机运行一个老版本的 app;拒绝摄像头，电话权限
2. 升级到接入权限管理库的 app; 打开摄像头，电话权限
3. 提示摄像头和电话权限没有打开

**Comment by yanzhenjie** [comment]
需要手机系统品牌、品牌系统版本，Android系统版本，targetSdkVersion值，另外再加上你的描述。

如果是Android10，请跟踪 #478 ，其他问题请单独提issue。
