### ISSUE TITLE
Vivo x21跳转到系统权限设置页面，然而没有存储权限的打开设置

### ISSUE THREAD

**Issue by desaco1989** [yanzhenjie/AndPermission#442]
Vivo x21跳转到系统权限设置页面，然而没有存储权限的打开设置，麻烦看下

**Comment by ZysGit** [comment]
我也遇到了这个问题。查了一下在某些vivo手机上会跳转到“单项权限设置”页。这个页面没有存储权限的开关。

**Comment by liaohuyu** [comment]
解决了么

**Comment by ZysGit** [comment]
> 解决了么

`private static Intent vivoApi(Context context) {
        return defaultApi(context);
//        Intent intent = new Intent();
//        intent.putExtra("packagename", context.getPackageName());
//        //只有系统应用才可以跳转到这个页面
//        intent.setComponent(new ComponentName("com.android.packageinstaller", "com.android.packageinstaller.permission.ui.ManagePermissionsActivity"));
//        if (hasActivity(context, intent)) {
//            return intent;
//        }
//        //部分手机在此页面找不到存储权限
//        intent.setComponent(new ComponentName("com.vivo.permissionmanager", "com.vivo.permissionmanager.activity.SoftPermissionDetailActivity"));
//        if (hasActivity(context, intent)) {
//            return intent;
//        }
//        intent.setComponent(new ComponentName("com.iqoo.secure", "com.iqoo.secure.safeguard.SoftPermissionDetailActivity"));
//        return intent;
    }`
最后让他跳到默认页面了。-.--.--.-

**Comment by liaohuyu** [comment]
我看有的应用跳的是应用权限页面，而不是单项去权限设置，这个默认的只能挑到应用信息页面。

**Comment by ZysGit** [comment]
> 我看有的应用跳的是应用权限页面，而不是单项去权限设置，这个默认的只能挑到应用信息页面。
``` java 
//这个页面好像就是权限管理，我试了下居然需要一个系统级app的权限。最后没办法我就用默认的了，暂且让自己点进去。
intent.setComponent(new ComponentName("com.android.packageinstaller", "com.android.packageinstaller.permission.ui.ManagePermissionsActivity"));
```

**Comment by ZysGit** [comment]
> 我看有的应用跳的是应用权限页面，而不是单项去权限设置，这个默认的只能挑到应用信息页面。

你这边解决了也麻烦回复下我。

**Comment by liaohuyu** [comment]
难受  我也没辙了
