### ISSUE TITLE
小米Mix 8.0手机 权限获取问题

### ISSUE THREAD

**Issue by desaco1989** [yanzhenjie/AndPermission#443]
小米Mix 8.0手机，选择了“不再询问”+拒绝，然后跳转到 系统权限设置页，允许“读写手机存储”权限，然后回到手机App，仍提示没有“读写权限”

**Comment by qtly** [comment]
MIUI优化选项是打开的吗?我这边红米 note7,由于AS打包APK到红米 note7上装不上,关闭MIUI优化选项,也如你所说的出现这种问题,反复测试验证MIUI优化选项打开就没问题了,希望对你有帮助

**Comment by yanzhenjie** [comment]
如果系统是Android10，那么跟踪 #478，如果是 @qtly 说的问题，请按照他的描述进行测试。
