### ISSUE TITLE
已经授予权限但还是onDenied

### ISSUE THREAD

**Issue by iQuick** [yanzhenjie/AndPermission#445]
在手机上授予了“读写通话记录权限”，但是还是无法检测到，一直走 onDenied() 方法。不论是动态申请是授予，还是手动授予都一样。

![](http://ww1.sinaimg.cn/large/874a93b1gy1g348g4fi5qj20d10pp40m.jpg)

经调试发现，在测试插入的时候报了一个空指针错误。

![](http://ww1.sinaimg.cn/large/874a93b1gy1g348fqlbcuj20rj05cq3j.jpg)

机器：长虹 s18

**Comment by xionger0520** [comment]
@iQuick 我来帮作者回答一下吧  很有可能是你在权限申请成功后回调方法里面的代码报错被捕获了   因此会一直调onDenied  检查一下毁掉成功后的代码

**Comment by xionger0520** [comment]
@iQuick 我来帮作者回答一下吧 很有可能是你在权限申请成功后回调方法里面的代码报错被捕获了 因此会一直调onDenied 检查一下回调成功后的代码

**Comment by yanzhenjie** [comment]
@xionger0520 Thank you for your generosity.

@iQuick This is very helpful to you:  
[https://yanzhenjie.com/AndPermission/cn/runtime/explain.html](https://yanzhenjie.com/AndPermission/cn/runtime/explain.html)
