### ISSUE TITLE
has leaked IntentReceiver com.yanzhenjie.permission.bridge.Messenger  that was originally registered here. Are you missing a call to unregisterReceiver()?

### ISSUE THREAD

**Issue by l123456789jy** [yanzhenjie/AndPermission#446]
android 9

**Comment by zjkgsqj** [comment]
一加7，Android 9同样的问题

07-18 21:31:53.934 E/ActivityThread( 8118): Activity com.bankcomm.maidanba.activity.SplashActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.b@b319e34 that was originally registered here. Are you missing a call to unregisterReceiver()?
07-18 21:31:53.934 E/ActivityThread( 8118): android.app.IntentReceiverLeaked: Activity com.bankcomm.maidanba.activity.SplashActivity has leaked IntentReceiver com.yanzhenjie.permission.bridge.b@b319e34 that was originally registered here. Are you missing a call to unregisterReceiver()?
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1470)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1236)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1479)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1452)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1440)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:623)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at com.yanzhenjie.permission.bridge.b.a(Unknown Source:9)
07-18 21:31:53.934 E/ActivityThread( 8118): 	at com.yanzhenjie.permission.bridge.c.run(Unknown Source:30)

**Comment by sweet2o09** [comment]
请问RequestExecutor导致内存泄漏的问题目前是否已经有解决方案了?

**Comment by yanzhenjie** [comment]
#436

**Comment by wczhang3** [comment]
同问，有解决方案吗

**Comment by yqyzxd** [comment]
同问
