### ISSUE TITLE
v4 包下面的 Fragment 中无法使用

### ISSUE THREAD

**Issue by Erlangshen** [yanzhenjie/AndPermission#451]
我现在用的是
```
implementation 'com.yanzhenjie:permission:2.0.0'
```
```AndPermission.with(Fragment fragment)```传参报错，点进```with```方法可以看到
```
 public static ActivityOption with(Fragment fragment) {
        return new Boot(new XFragmentSource(fragment));
    }
public static ActivityOption with(android.app.Fragment fragment) {
        return new Boot(new FragmentSource(fragment));
    }
```
一个是 app 包下面的 Fragment，另一个是 androidx.fragment.app.Fragment 包下面的，没有 support.v4 包里面的 Fragment

**Comment by yanzhenjie** [comment]
At that time, the plan was to no longer support the support package, but there are still many students who have this need, so the version 2.0.1 was released.
