### ISSUE TITLE
Kotlin中报空指针错误

### ISSUE THREAD

**Issue by mazhiyong** [yanzhenjie/AndPermission#452]
![image](https://user-images.githubusercontent.com/30279528/60154546-3fe42a00-981a-11e9-95ce-d185e03005f3.png)
![image](https://user-images.githubusercontent.com/30279528/60154563-4c688280-981a-11e9-9cbe-348623369c56.png)
![image](https://user-images.githubusercontent.com/30279528/60154578-58ecdb00-981a-11e9-8fce-d3441449dc60.png)
麻烦在BridgeActivity的OnCreate()方法的参数前加个@Nullable 注解

**Comment by yanzhenjie** [comment]
I don't understand this problem. Can you explain it to me?
