### ISSUE TITLE
REQUEST_INSTALL_PACKAGES，在OPPO A9(安卓9.0)上无法获取

### ISSUE THREAD

**Issue by ZuoHailong** [yanzhenjie/AndPermission#456]
大佬，用的“安装未知来源Apk”的api，在OPPO A9上无法获取权限，manifest中注册报红，在低版本系统上安装是可以的，请问大佬，怎么回事？

**Comment by yanzhenjie** [comment]
build.gradle:  
```groovy
targetSdkVersion 28
```

manifest.xml:  
```xml
<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
```

java:  
```java
    File apkFile = ...;

    AndPermission.with(this)
        .install()
        .file(apkFile )
        .rationale(...)
        .start();
```

----

If you have any questions, please preview [the document](https://yanzhenjie.com/AndPermission). If you still can't solve it, please give it up.
