### ISSUE TITLE
一次性申请多个权限，拒绝其中一个没有调用rationale

### ISSUE THREAD

**Issue by zhangchaoxu** [yanzhenjie/AndPermission#46]
我一次性调用多个权限
`AndPermission.with(this)
                .requestCode(100)
                .permission(Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.READ_PHONE_STATE,
                        Manifest.permission.CAMERA)
                .rationale((requestCode, rationale) ->
                        // 此对话框可以自定义，调用rationale.resume()就可以继续申请。
                        AndPermission.rationaleDialog(SplashActivity.this, rationale).show()
                )
                .send();

@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        AndPermission.onRequestPermissionsResult(this, requestCode, permissions, grantResults);
    }

    @PermissionYes(100)
    private void getLocationYes(List<String> grantedPermissions) {
        checkAccountLogin();
    }

    // 失败回调的方法，用注解即可，里面的数字是请求时的requestCode。
    @PermissionNo(100)
    private void getLocationNo(List<String> deniedPermissions) {
        // 用户否勾选了不再提示并且拒绝了权限，那么提示用户到设置中授权。
        if (AndPermission.hasAlwaysDeniedPermission(this, deniedPermissions)) {
            // 第一种：用默认的提示语。
            AndPermission.defaultSettingDialog(this, 300).show();
        }
    }`

拒绝了其中某个权限，没有显示AndPermission.rationaleDialog，退出后重新进入有显示。

**Comment by yanzhenjie** [comment]
这个逻辑是正确的，你可能还没理解`rationale`，请看这篇文章：[Android6.0运行时权限管理最佳实践](http://blog.csdn.net/yanzhenjie1003/article/details/52503533)。

**Comment by zhangchaoxu** [comment]
从用户角度出发，如果这个被拒绝的权限是必须的。
那app应该提醒用户赋予权限，点确定再次显示申请权限窗口。

目前的情况是如果用户拒绝了权限以后，PermissionNo可以捕捉到不再提示，无法捕捉到类似这个拒绝了其中一个权限的情况

**Comment by yanzhenjie** [comment]
有几个注意的地方：  
1. 用户只要是拒绝了其中一个权限后，`AndPermission`会回调失败，因为`AndPermission`推荐使用权限才申请，所以认为申请一个失败那么接下来的操作就不能操作，并且会在onFailed中回调你所有申请失败的权限，这一点你上面说错了。  
2. `rationale`是用户拒绝过一次权限后，再次申请时授权框会多出一个`不再提示`的复选框，所以`rationale`先弹出是可以提前提示用户是否允许权限，是的话再申请，这样免得用户勾选`不再提示`导致其它操作也无法授权。
3. 就算用户勾选了`不再提示`（和部分国产机只要拒绝过一次就默认不再提示），`AndPermission`提供了一个`SettingDialog`的操作，可以打开系统`Setting`让用户给App授权。  
其它疑问，请你先看下上面那篇文章，理解`Android6.0运行时权限`的工作原理，`AndPermission`是按照这个原理来设计和工作的。

**Comment by zhangchaoxu** [comment]
got it, thanks
