### ISSUE TITLE
AddVoicemailTest can not right test ,becasuse uri permission denyied

### ISSUE THREAD

**Issue by xiaowei1992** [yanzhenjie/AndPermission#460]

**Comment by yanzhenjie** [comment]
Doesn't this just indicate that there is no permission?

**Comment by xiaowei1992** [comment]
i have already refused the phone permission and then reopen it by system ,but it still notice me that add_voicemail permission is refresed, this is the exception of AddVoicemailTest:
 Permission Denial: writing com.android.providers.contacts.VoicemailContentProvider uri content://com.android.voicemail/voicemail from pid=11648, uid=10565 requires com.android.voicemail.permission.ADD_VOICEMAIL, or grantUriPermission()




------------------ 原始邮件 ------------------
发件人: "Zhenjie Yan"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午4:30
收件人: "yanzhenjie/AndPermission"<AndPermission@noreply.github.com>; 
抄送: "vg"<869660910@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yanzhenjie/AndPermission] AddVoicemailTest can not right test,becasuse uri permission denyied (#460)




Doesn't this just indicate that there is no permission?

**Comment by yanzhenjie** [comment]
After you have given permission, you don't actually have this permission. This shows that the system does not allow you to have this permission, I also found this situation, this is not a problem with AndPermission.

**Comment by xiaowei1992** [comment]
ok, thank you ！




------------------ 原始邮件 ------------------
发件人: "Zhenjie Yan"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 下午4:51
收件人: "yanzhenjie/AndPermission"<AndPermission@noreply.github.com>; 
抄送: "vg"<869660910@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yanzhenjie/AndPermission] AddVoicemailTest can not right test,becasuse uri permission denyied (#460)




After you have given permission, you don't actually have this permission. This shows that the system does not allow you to have this permission, I also found this situation, this is not a problem with AndPermission.
