### ISSUE TITLE
Mi note3 Android 9 (MIUI10.9.7.4开发版) 设置里权限已经授予,代码了识别不到

### ISSUE THREAD

**Issue by ZHDelete** [yanzhenjie/AndPermission#461]
您好,我在Mi note3 Android 9 (MIUI10.9.7.4开发版) 设备上,多次拒绝并不再询问` Permission.READ_CONTACTS`后,去设置页面 授予了 读取联系人权限,然而回到代码中,还是无法获得`READ_CONTACTS`权限,

**Comment by rivenlee0** [comment]
这个问题我也是早就遇到了，无论是手动去设置，还是调用去设置页面的代码，再返回后，都无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。 请问你现在解决了吗？

**Comment by ZHDelete** [comment]
目前不知道如何解决,不过我的情况是只在Android Q 上才会有此情况,怀疑是最新的Android权限策略变更造成的.

**Comment by ZHDelete** [comment]
> 这个问题我也是早就遇到了，无论是手动去设置，还是调用去设置页面的代码，再返回后，都无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。 请问你现在解决了吗？

目前不知道如何解决,不过我的情况是只在Android Q 上才会有此情况,怀疑是最新的Android权限策略变更造成的.

**Comment by renjinlong** [comment]
同求AndroidQ 权限无法正常获取怎么办？

**Comment by rivenlee0** [comment]
android Q , 获取手机状态权限，已删除掉了，无法获取。
我遇到是 android 9的设置页面回调问题， 我看你之前也说的这个问题呀，现在怎么变成androidQ了。

**Comment by rivenlee0** [comment]
> > 这个问题我也是早就遇到了，无论是手动去设置，还是回用后，设无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。请问你现在解决了吗？
> 
> 目前不知道如何解决，不过我的情况是只在Android Q上才会有此情况，怀疑是最新的Android权限策略变更造成的。
android Q，获取手机状态权限，已删除掉了，无法获取。
我遇到是android 9的设置页面回调问题，我看你之前也说的这个问题呀，现在怎么变成androidQ了。

**Comment by rivenlee0** [comment]
> 同求AndroidQ权限无法正常获取怎么办？

android Q，获取手机状态权限，已删除掉了，无法获取。

**Comment by ZHDelete** [comment]
> > > 这个问题我也是早就遇到了，无论是手动去设置，还是回用后，设无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。请问你现在解决了吗？
> > 
> > 
> > 目前不知道如何解决，不过我的情况是只在Android Q上才会有此情况，怀疑是最新的Android权限策略变更造成的。
> > android Q，获取手机状态权限，已删除掉了，无法获取。
> > 我遇到是android 9的设置页面回调问题，我看你之前也说的这个问题呀，现在怎么变成androidQ了。

Android Q (API 28 android 版本 9) 
我只有3部Q的手机,目前在Mi note3 (MIUI 开发版 10.9.7.4) RedMi pro 6 (MIUI 稳定版 10.3.1.0) 发现了这个问题,
在华为荣耀Note 10上没发现这种情况,
所以我怀疑是MIUI的bug,
不知道你那里发现问题的手机型号是什么?

**Comment by rivenlee0** [comment]
> > > > 这个问题我也是早就遇到了，无论是手动去设置，还是回用后，设无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。请问你现在解决了吗？
> > > 
> > > 
> > > 目前不知道如何解决，不过我的情况是只在Android Q上才会有此情况，怀疑是最新的Android权限策略变更造成的。
> > > android Q，获取手机状态权限，已删除掉了，无法获取。
> > > 我遇到是android 9的设置页面回调问题，我看你之前也说的这个问题呀，现在怎么变成androidQ了。
> 
> Android Q (API 28 android 版本 9)
> 我只有3部Q的手机,目前在Mi note3 (MIUI 开发版 10.9.7.4) RedMi pro 6 (MIUI 稳定版 10.3.1.0) 发现了这个问题,
> 在华为荣耀Note 10上没发现这种情况,
> 所以我怀疑是MIUI的bug,
> 不知道你那里发现问题的手机型号是什么?

AndroidQ是 android 10， Android P才是android 9呀， 我这边也是MIUI系统， 华为系统是没问题的，所以之前也定位是MIUI的定制系统

**Comment by ZHDelete** [comment]
> > > > > 这个问题我也是早就遇到了，无论是手动去设置，还是回用后，设无法正确识别权限，通过测试，在不同的手机上和SDK VERSION上，只有部分可以。请问你现在解决了吗？
> > > > 
> > > > 
> > > > 目前不知道如何解决，不过我的情况是只在Android Q上才会有此情况，怀疑是最新的Android权限策略变更造成的。
> > > > android Q，获取手机状态权限，已删除掉了，无法获取。
> > > > 我遇到是android 9的设置页面回调问题，我看你之前也说的这个问题呀，现在怎么变成androidQ了。
> > 
> > 
> > Android Q (API 28 android 版本 9)
> > 我只有3部Q的手机,目前在Mi note3 (MIUI 开发版 10.9.7.4) RedMi pro 6 (MIUI 稳定版 10.3.1.0) 发现了这个问题,
> > 在华为荣耀Note 10上没发现这种情况,
> > 所以我怀疑是MIUI的bug,
> > 不知道你那里发现问题的手机型号是什么?
> 
> AndroidQ是 android 10， Android P才是android 9呀， 我这边也是MIUI系统， 华为系统是没问题的，所以之前也定位是MIUI的定制系统

呃,是的 Q 是 10 丢人了... 估计是MIUI的bug了,我用RxPermission 也是同样情况,用`ContextCompat.checkSelfPermission(MainActivity.this, Manifest.permission.READ_CONTACTS);`也是false

**Comment by rivenlee0** [comment]
是的呢， 所以这个UI系统适配我已经放弃了

**Comment by yanzhenjie** [comment]
I thought of a possible solution, give me some more time...

**Comment by rivenlee0** [comment]
> I thought of a possible solution, give me some more time...

Can u speak chinese? Big Yan

**Comment by yanzhenjie** [comment]
嘿嘿，可以的。但是我想说的是，这是一个英文项目，还配备了英文文档，而且在Issue栏明说了请使用英文交流。

这样一个项目，不能因为开发者是中国人，就...但是氛围已经被破坏了。虽然我有几个项目老外在用，但是老外看到这种Issues后也就慢慢放弃了，我觉得以后写了英文项目不能在国内宣传了。
:joy: :joy: :joy:

**Comment by rivenlee0** [comment]
> 嘿嘿，可以的。但是我想说的是，这是一个英文项目，还配备了英文文档，而且在Issue栏明说了请使用英文交流。
> 
> 这样一个项目，不能因为开发者是中国人，就...但是氛围已经被破坏了。虽然我有几个项目老外在用，但是老外看到这种Issues后也就慢慢放弃了，我觉得以后写了英文项目不能在国内宣传了。
> 😂 😂 😂

是这样的，严大，你刚才说的我看不懂呀，还得靠google翻译。 这个issue里是小米的适配问题，估计都是国内开发者才会遇到的问题，我就随便开玩笑，您别介意呀！~

**Comment by yanzhenjie** [comment]
木事木事，随意点 哈哈，以自己最舒服的方式来就行，低头不见抬头见的。 

:yum: :yum: :yum:

**Comment by ZHDelete** [comment]
shame... I started with Chinese first...
no more later...

**Comment by rivenlee0** [comment]
> I thought of a possible solution, give me some more time...

Hi, Big Yan, How's the research going？

**Comment by HanseyChan** [comment]
> I thought of a possible solution, give me some more time...

waiting you. my brother!

**Comment by yanzhenjie** [comment]
看了一下，小米的这个问题没有办法哦，看看是否**和MIUI优化开关**有关系。

说一下目前的处理方案，如果系统返回的状态是无权限，那么AndPermission会直接回调你无权限；如果系统返回的是有权限，那么AndPermission会做一个验证，也就是真的去执行一下操作，比如读取通讯录、调用摄像头等。

目前如果MIUI系统返回的是无权限，还真的没有办法了。
