### ISSUE TITLE
申请权限，不弹系统提示框

### ISSUE THREAD

**Issue by jeromyniu** [yanzhenjie/AndPermission#465]
**现象** -> 在A activity onCreate方法申请某权限，假如在用户还未来得及点击拒绝或允许时，需要跳转到B activity，如果此时在B activity 再申请权限就有概率出现不弹系统提示框的bug。
因为在A activity申请的权限没有被处理，RequestExecutor没有接收到回调，它的notify方法未被调到，就一直处于wait的状态。
当有新的request到来时，就只能一直在队列里等待被pending的那个request的结束。
更恶心的一点在于，即使从B返回了A 也看不到权限申请的弹框，把所有activity都干掉才能看到。不知道系统为啥这么设计...

**疑问** -> 用队列存储权限的request，并且一定是依次执行，这个设计是不是欠妥？
理想情况应该是，每次请求都应该是独立的，完全不依赖与其他请求是否成功才对吧。

**这样行不行** -> 每次请求都带上一个id，当BridgeActivity的onXXResult接收到系统回调时通过id找到callback，再把权限的结果回调给业务方。

**Comment by chentao7v** [comment]
我也遇到了这个问题，目前都是等用户处理完了权限请求再跳转。用户没有处理权限请求时是不会跳转的。

**Comment by jeromyniu** [comment]
> 我也遇到了这个问题，目前都是等用户处理完了权限请求再跳转。用户没有处理权限请求时是不会跳转的。

我把原代码改了一下，废弃了队列那部分逻辑

**Comment by WShaobin** [comment]
我也出现同样的问题，不知大佬更新了吗

**Comment by lgj860123** [comment]
我也遇到了同样的问题，有解决的吗，是怎么解决这样的情况的呢？

**Comment by yanzhenjie** [comment]
这么设计的原因是，系统中连续请求多个权限时，只允许存在一个请求，后面的请求会被视作无效：

假设1、2、3分别的代表某个权限，那么系统中：
`request1, request2, request3`而不是`request123`时，后面的2、3权限就不会有反应。

现在我将把它们改成线程池实现。
