### ISSUE TITLE
关于Nexus手机检查权限问题

### ISSUE THREAD

**Issue by Roben1016** [yanzhenjie/AndPermission#466]
在nexus 5  安卓系统6.0.1手机上判断相机权限时, 框架返回没有权限, 但是直接使用系统判断权限的方法ContextCompat.checkSelfPermission(this, Permission.CAMERA)返回的是有权限. 这个问题有点难.. 然后还有个问题就是内存泄漏的问题.
![微信图片_20190723194633](https://user-images.githubusercontent.com/15700182/61709806-9b0a2d80-ad82-11e9-9d46-9ebf9fac4835.jpg)

**Comment by yanzhenjie** [comment]
相机请跟踪 #459 ，内存泄漏跟踪 #436
