### ISSUE TITLE
在小米系列手机上开始请求到成功或失败回调耗时太久

### ISSUE THREAD

**Issue by blackCat-wlc** [yanzhenjie/AndPermission#468]
先感谢大佬提供这么好用的东西。
我是从1.1.2版本升级到2.0.1的。更新好以后发现请求整体感觉好卡，然后我计时算了下，发现从开始请求到回调耗时太久。大致如下：以CAMERA权限为例
红米Note3（5.0.2）：平均1400ms
红米5（8.1.0）： 重新打开后一直5000ms，多调用好多次后稳定400ms
小米Note3（8.1.0）：打开时不时5000ms，稳定后400ms

**Comment by Ximano** [comment]
> 先感谢大佬提供这么好用的东西。
> 我是从1.1.2版本升级到2.0.1的。更新好以后发现请求整体感觉好卡，然后我计时算了下，发现从开始请求到回调耗时太久。大致如下：以CAMERA权限为例
> 红米Note3（5.0.2）：平均1400ms
> 红米5（8.1.0）： 重新打开后一直5000ms，多调用好多次后稳定400ms
> 小米Note3（8.1.0）：打开时不时5000ms，稳定后400ms

不但是小米手机上，vivo和华为手机上，都会出现这种问题。暂时不知道问题出在哪？
但是作者的demo没有这种问题。老哥你解决这个问题了吗？？

**Comment by blackCat-wlc** [comment]
作者的demo上也有这情况，只是没这么严重(100～1000）。多次掉用延迟时间更长。应该是机制问题。我现在还是用低版本的。------------------ 原始邮件 ------------------
发件人: "Ximano"<notifications@github.com>
发送时间: 2019年9月6日(星期五) 晚上6:44
收件人: "yanzhenjie/AndPermission"<AndPermission@noreply.github.com>;
抄送: "blackCat-wlc"<w511634937@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yanzhenjie/AndPermission] 在小米系列手机上开始请求到成功或失败回调耗时太久 (#468)


 
先感谢大佬提供这么好用的东西。
 我是从1.1.2版本升级到2.0.1的。更新好以后发现请求整体感觉好卡，然后我计时算了下，发现从开始请求到回调耗时太久。大致如下：以CAMERA权限为例
 红米Note3（5.0.2）：平均1400ms
 红米5（8.1.0）： 重新打开后一直5000ms，多调用好多次后稳定400ms
 小米Note3（8.1.0）：打开时不时5000ms，稳定后400ms
  
不但是小米手机上，vivo和华为手机上，都会出现这种问题。暂时不知道问题出在哪？
 但是作者的demo没有这种问题。老哥你解决这个问题了吗？？
 
&mdash;

**Comment by Ximano** [comment]
> 先感谢大佬提供这么好用的东西。
> 我是从1.1.2版本升级到2.0.1的。更新好以后发现请求整体感觉好卡，然后我计时算了下，发现从开始请求到回调耗时太久。大致如下：以CAMERA权限为例
> 红米Note3（5.0.2）：平均1400ms
> 红米5（8.1.0）： 重新打开后一直5000ms，多调用好多次后稳定400ms
> 小米Note3（8.1.0）：打开时不时5000ms，稳定后400ms
老哥，我找到问题了，因为我的app里Application里初始化了FacebookSdk的统计库，注释掉就没有问题了，但是不知道是什么原因造成的。。我加你qq了，望通过！谢谢～
