### ISSUE TITLE
java 8 lambda 表达式  会与一些第三方的框架冲突，能不能换个写法？

### ISSUE THREAD

**Issue by flyjiang2014** [yanzhenjie/AndPermission#47]
jackOptions {
            enabled true
        }   

与 butterknife 框架冲突了，

**Comment by yanzhenjie** [comment]
你别用lambda就好了呀，我只是demo用了，源码又没限制。 butterknife可以用annotationProcessor依赖与jack共存。

**Comment by flyjiang2014** [comment]
好的
