### ISSUE TITLE
Android Q  READ_PHONE_STATE权限同意之后仍然走onDenied

### ISSUE THREAD

**Issue by haonan1** [yanzhenjie/AndPermission#470]
Android Q  READ_PHONE_STATE权限 用户同意之后但是一直走onDenied

**Comment by 1031900805** [comment]
+1

**Comment by haonan1** [comment]
vivo 5.1.1 HTC 6.0.1 READ_PHONE_STATE 也是这种情况，建议尽快修改

**Comment by IDBAI** [comment]
因为默认是使用了双检测模式，我们可以通过Hook的方式，设置为标准的检测模式就可以了：
Application类下，代码如下：
    @Override
    public void onCreate() {
hookAndPermissionChecker();
}

/****
     * 由于AndPermission库未适配Android Q，在权限检查时候，替换为标准方式以解决严格模式下面不兼容Android Q的问题
     * Android Q
     * fieldObj = class com.yanzhenjie.permission.checker.DoubleChecker
     * newFieldObj = class com.yanzhenjie.permission.checker.StandardChecker
     */
    private void hookAndPermissionChecker() {
        if (MobileUtils.INSTANCE.isAndroidQ()) {
            try {
                Class<?> andPermission = Class.forName("com.yanzhenjie.permission.AndPermission");
                Field permissionChecker = andPermission.getDeclaredField("PERMISSION_CHECKER");
                permissionChecker.setAccessible(true);
                Object fieldObj = permissionChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker fieldObj = " + fieldObj.getClass());

                permissionChecker.set(fieldObj, new StandardChecker());
                Object newFieldObj = permissionChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker newFieldObj = " + newFieldObj.getClass());

                Log.d(TAG, "hookAndPermissionChecker success!");
            } catch (Exception e) {
                e.printStackTrace();
                MLog.error(TAG, e);
            }
        }
    }

 //copy from Android Q sdk .
    fun isAndroidQ(): Boolean {
        return Build.VERSION.SDK_INT > 28 || (Build.VERSION.CODENAME.length == 1
            && Build.VERSION.CODENAME[0] >= 'Q'
            && Build.VERSION.CODENAME[0] <= 'Z')
    }

**Comment by IDBAI** [comment]
因为默认是使用了双检测模式，可以通过Hook的方式，设置为标准的检测模式来解决：
Application类下，代码如下：

     @override
    public void onCreate() {  
      hookAndPermissionChecker();  
    }
    
   
    /****
     * 由于AndPermission库未适配Android Q，在权限检查时候，替换为标准方式以解决严格模式下面不兼容Android Q的问题
     * Android Q
     * fieldObj = class com.yanzhenjie.permission.checker.DoubleChecker
     * newFieldObj = class com.yanzhenjie.permission.checker.StandardChecker
     */
    private void hookAndPermissionChecker() {
        if (MobileUtils.INSTANCE.isAndroidQ()) {
            try {
                Class<?> andPermission = Class.forName("com.yanzhenjie.permission.AndPermission");
                Field permissionChecker = andPermission.getDeclaredField("PERMISSION_CHECKER");
                permissionChecker.setAccessible(true);
                Object fieldObj = permissionChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker fieldObj = " + fieldObj.getClass());

                permissionChecker.set(fieldObj, new StandardChecker());
                Object newFieldObj = permissionChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker newFieldObj = " + newFieldObj.getClass());

                Log.d(TAG, "hookAndPermissionChecker success!");
            } catch (Exception e) {
                e.printStackTrace();
                MLog.error(TAG, e);
            }
        }
    }
  
  
    //copy from Android Q sdk .
    private boolean isAndroidQ() {
        return Build.VERSION.SDK_INT > 28 || 
            (Build.VERSION.CODENAME.length == 1
            && Build.VERSION.CODENAME[0] >= 'Q'
            && Build.VERSION.CODENAME[0] <= 'Z');
    }

**Comment by IDBAI** [comment]
暂时通过hook方式解决，不过还是希望作者尽早做适配了，毕竟现在应用市场要求应用需要尽快适配Android Q。

**Comment by 1031900805** [comment]
> 暂时通过钩方式解决，不过还是希望作者尽早做适应了，毕竟现在应用市场要求应用需要尽快适配Android Q.

我的在Android 9遇到的此问题也一样通用吗？

**Comment by IDBAI** [comment]
> > 暂时通过钩方式解决，不过还是希望作者尽早做适应了，毕竟现在应用市场要求应用需要尽快适配Android Q.
> 
> 我的在Android 9遇到的此问题也一样通用吗？

你试试看，或者看看他标准检测模式源码。

**Comment by marcoaros** [comment]
> 因为默认是使用了双检测模式，可以通过Hook的方式，设置为标准的检测模式来解决：
> Application类下，代码如下：
> 
> ```
>  @override
> public void onCreate() {  
>   hookAndPermissionChecker();  
> }
> 
> 
> /****
>  * 由于AndPermission库未适配Android Q，在权限检查时候，替换为标准方式以解决严格模式下面不兼容Android Q的问题
>  * Android Q
>  * fieldObj = class com.yanzhenjie.permission.checker.DoubleChecker
>  * newFieldObj = class com.yanzhenjie.permission.checker.StandardChecker
>  */
> private void hookAndPermissionChecker() {
>     if (MobileUtils.INSTANCE.isAndroidQ()) {
>         try {
>             Class<?> andPermission = Class.forName("com.yanzhenjie.permission.AndPermission");
>             Field permissionChecker = andPermission.getDeclaredField("PERMISSION_CHECKER");
>             permissionChecker.setAccessible(true);
>             Object fieldObj = permissionChecker.get(null);
>             Log.d(TAG, "hookAndPermissionChecker fieldObj = " + fieldObj.getClass());
> 
>             permissionChecker.set(fieldObj, new StandardChecker());
>             Object newFieldObj = permissionChecker.get(null);
>             Log.d(TAG, "hookAndPermissionChecker newFieldObj = " + newFieldObj.getClass());
> 
>             Log.d(TAG, "hookAndPermissionChecker success!");
>         } catch (Exception e) {
>             e.printStackTrace();
>             MLog.error(TAG, e);
>         }
>     }
> }
> 
> 
> //copy from Android Q sdk .
> private boolean isAndroidQ() {
>     return Build.VERSION.SDK_INT > 28 || 
>         (Build.VERSION.CODENAME.length == 1
>         && Build.VERSION.CODENAME[0] >= 'Q'
>         && Build.VERSION.CODENAME[0] <= 'Z');
> }
> ```

确实在AndroidQ上用StrictChecker会有问题，不知道为什么之前的版本需要用StrictChecker和StandardChecker一起判断，是有什么坑吗？我测试了一下只用StandardChecker在低版本上也没问题，我是基于'com.yanzhenjie.permission:x:2.0.1'做的测试。

**Comment by yanzhenjie** [comment]
#478
