### ISSUE TITLE
在AndroidQ上，用户先拒绝存储权限，然后跳转到setting开启存储权限，会到页面，在onActivityResult重新请求存储，会回调onDenied

### ISSUE THREAD

**Issue by IDBAI** [yanzhenjie/AndPermission#471]

**Comment by IDBAI** [comment]
在AndroidQ上，用户先拒绝存储权限，然后跳转到setting开启存储权限，会到页面，在onActivityResult重新请求存储，会回调onDenied，跟踪代码发现，在MRequest类，

    @Override
          public void onCallback() {
             new AsyncTask<Void, Void, List<String>>() {
                @Override
                protected List<String> doInBackground(Void... voids) {
                    return getDeniedPermissions(DOUBLE_CHECKER, mSource, mPermissions);
                }

            @Override
            protected void onPostExecute(List<String> deniedList) {
                if (deniedList.isEmpty()) {
                    callbackSucceed();
                } else {
                    callbackFailed(deniedList);
                }
            }
        }.execute();
    }
callback时候，重新使用了双检测模式去检测 
getDeniedPermissions(DOUBLE_CHECKER, mSource, mPermissions);

在针对：
case Permission.WRITE_EXTERNAL_STORAGE:
                    return checkWriteStorage();
这个代码，返回false，导致上述问题场景。

**Comment by IDBAI** [comment]
解决方案，仅供参考：

Application 的 oncreate方法，hook掉DOUBLE_CHECKER

            try {
                Class<?> mMRequest = Class.forName("com.yanzhenjie.permission.runtime.MRequest");
                Field doubleChecker = mMRequest.getDeclaredField("DOUBLE_CHECKER");
                doubleChecker.setAccessible(true);
                Object originChecker = doubleChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker MRequest originChecker = " + originChecker.getClass());
                doubleChecker.set(originChecker, new StandardChecker());
                Object newChecker = doubleChecker.get(null);
                Log.d(TAG, "hookAndPermissionChecker MRequest newChecker = " + newChecker.getClass());
                Log.d(TAG, "hookAndPermissionChecker MRequest success!");
            } catch (Exception e) {
                e.printStackTrace();
            }

希望作者能看到，及时升级版本兼容Android Q~

**Comment by HanseyChan** [comment]
我也是这情况。  OPPO Reno

**Comment by IDBAI** [comment]
跳转到setting时候把自己进程杀了。

**Comment by yanzhenjie** [comment]
#478
