### ISSUE TITLE
悬浮窗权限已经默认选中，返回后回调onDenied()

### ISSUE THREAD

**Issue by Deaful** [yanzhenjie/AndPermission#472]
你好，问一下，申请悬浮窗权限的时候，跳转到系统设置，默认已经选中了，我直接点返回，调用onDenied()，但是如果取消选中再手动选中后返回，调用onGranted()。我希望选中状态和onGranted()一一对应：如果默认选中，那么让它回调onGranted()，不知道该怎么处理。

**Comment by yanzhenjie** [comment]
This is a system problem, we have found it, but there is no way.

**Comment by Deaful** [comment]
> This is a system problem, we have found it, but there is no way.

Thanks~

**Comment by daixiansen** [comment]
> 你好，问一下，申请悬浮窗权限的时候，跳转到系统设置，默认已经选中了，我直接点返回，调用onDenied()，但是如果取消选中再手动选中后返回，调用onGranted()。我希望选中状态和onGranted()一一对应：如果默认选中，那么让它回调onGranted()，不知道该怎么处理。

默认选中了 ？ 默认打开的话，还会跳转过去吗 ？
