### ISSUE TITLE
魅族Flyme 7.3.0.0A报错

### ISSUE THREAD

**Issue by shenjiabing** [yanzhenjie/AndPermission#476]
使用的是compile 'com.yanzhenjie.permission:support:2.0.1'版本
魅族应用市场被拒绝，报错机型是魅族Flyme 7.3.0.0A，其他机型使用正常，可以帮忙看看吗？
![5](https://user-images.githubusercontent.com/45984638/64218922-1a4c5e80-cef6-11e9-9c91-c0cf1a243f4e.png)
我的代码：
![1](https://user-images.githubusercontent.com/45984638/64218936-22a49980-cef6-11e9-9aa1-3386ea93c5f5.png)
![2](https://user-images.githubusercontent.com/45984638/64218942-259f8a00-cef6-11e9-85d9-64f9a2c3ebaa.png)
![3](https://user-images.githubusercontent.com/45984638/64218944-2801e400-cef6-11e9-8592-3a876cd8b4a1.png)
![4](https://user-images.githubusercontent.com/45984638/64218948-29cba780-cef6-11e9-9b5f-c4ab007e83f9.png)

**Comment by niemj** [comment]
看报错应该是你的showsettingDialog传入的context所在的界面已经被销毁了，应该和权限申请没啥关系
