### ISSUE TITLE
红米note3 最后一个开发版miui10 8.11.22 拍照权限授权成功以后,仍弹出授权失败

### ISSUE THREAD

**Issue by lydlovexyz** [yanzhenjie/AndPermission#479]
如题

**Comment by lydlovexyz** [comment]
不止我的红米note3,联想手机上也是如此.

**Comment by lydlovexyz** [comment]
<img width="601" alt="微信截图_20190906164410" src="https://user-images.githubusercontent.com/19246347/64414237-9e087580-d0c5-11e9-9c8f-2fbd678fee49.png">

**Comment by yanzhenjie** [comment]
#459
