### ISSUE TITLE
Android3.0之后，AsyncTask 默认是单一线程，会导致响应特别慢

### ISSUE THREAD

**Issue by hustwyz** [yanzhenjie/AndPermission#481]
测试的时候发现有时授权了还是要等待半天才回响应，查看源码才发现AndPermission的代码里面使用了AsyncTask，Android 3.0之后AsyncTask的默认线程池是SerialExecutor了。有一些第三方SDK用到了AsyncTask，会导致AndPermission授权也会卡住很久。希望能修复这个问题。

**Comment by qingweiSun** [comment]
我也感觉到了。暂时换掉rxper了

**Comment by victorfan336** [comment]
大佬 @yanzhenjie 我用的2.0.3的版本，怎么还是会出现要好几秒才会弹出权限申请框呀？bug 没修复吗？
