### ISSUE TITLE
Caused by java.lang.IllegalArgumentExceptionReceiver not registered: 

### ISSUE THREAD

**Issue by jiayuliang1314** [yanzhenjie/AndPermission#484]
Caused by java.lang.IllegalArgumentExceptionReceiver not registered: com.yanzhenjie.permission.bridge.b@b4948d2 Raw Text
--
  | android.app.LoadedApk.forgetReceiverDispatcher + 1203 (LoadedApk.java:1203)
  | android.content.ContextWrapper.unregisterReceiver + 645 (ContextWrapper.java:645)
  | com.yanzhenjie.permission.bridge.b.b + 49 (Messenger.java:49)
  | com.yanzhenjie.permission.bridge.c.a + 96 (RequestExecutor.java:96)
  | com.yanzhenjie.permission.bridge.b.onReceive + 54 (Messenger.java:54)
  | android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_53034 + 1323 (LoadedApk.java:1323)
  | com.android.internal.os.ZygoteInit.main + 888 (ZygoteInit.java:888)

**Comment by yanzhenjie** [comment]
#436
