### ISSUE TITLE
android 10 权限可以做一下适配吗？

### ISSUE THREAD

**Issue by fadedHYC** [yanzhenjie/AndPermission#488]
android 10 权限可以做一下适配吗？

**Comment by yanzhenjie** [comment]
#478

**Comment by fadedHYC** [comment]
Now I want to ask for apk permissions “REQUEST_INSTALL_PACKAGES” and install apk when I get them.
What should I do?




------------------ 原始邮件 ------------------
发件人: "Zhenjie Yan"<notifications@github.com>;
发送时间: 2019年9月25日(星期三) 晚上8:52
收件人: "yanzhenjie/AndPermission"<AndPermission@noreply.github.com>;
抄送: "1339868776"<1339868776@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yanzhenjie/AndPermission] android 10 权限可以做一下适配吗？ (#488)




Closed #488.

**Comment by yanzhenjie** [comment]
https://yanzhenjie.com/AndPermission/install/
