### ISSUE TITLE
android 10 删除了READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by daleiyinsi** [yanzhenjie/AndPermission#489]
在android 10里面申请这两个权限一直返回失败，只能自己手动判断如果是android 10就不申请这两项权限

**Comment by coolBreezes** [comment]
@daleiyinsi ，不是的，android10 不允许直接通过/sdcard/根路径的方式 访问外部存储资源，AndPermssion默认采用严格权限检测的方式，会主动访问创建sd根目录，导致请求权限实际成功，但仍返回失败。 （并非android10删除了read和write权限）

@yanzhenjie  博主，这边建议能否对android10以上做判断，申请存储权限时，若 android api sdk >= 29 或者 android:requestLegacyExternalStorage="false" （即采用沙箱存储）时，不进行严格检测，只去申请权限，
或者，博主能否提供一个设置申请权限策略的接口（我看了下，当前好像只能采用严格检测额）

**Comment by yanzhenjie** [comment]
@coolBreezes  got it.

**Comment by yanzhenjie** [comment]
#478
