### ISSUE TITLE
拒绝一次权限，并勾选禁止。。。不再提示  ，手机设置还原为提示，再次点击还是弹出禁止dialog

### ISSUE THREAD

**Issue by Jusenr** [yanzhenjie/AndPermission#49]
调用：
` AndPermission.with(this)
                        .requestCode(PermissionsUtils.CAMERA_CODE)
                        .permission(Manifest.permission.CAMERA)
                        .callback(this)
                        .rationale(rationaleListener)
                        .start();`
自定义dialog：
`private RationaleListener rationaleListener = new RationaleListener() {
        @Override
        public void showRequestPermissionRationale(int requestCode, final Rationale rationale) {
            // 这里的对话框可以自定义，只要调用rationale.resume()就可以继续申请。
            mSelectDialog = new SelectDialog.Builder(HomeChildMoreActivity.this)
                    .setMessage("友情提示")
                    .setTitle("你已拒绝过定位权限，沒有定位定位权限无法为你推荐附近的妹子，你看着办！")
                    .setTitleColor(getResources().getColor(R.color.theme))
                    .setNegativeButton(getString(R.string.permission_button_item_refuse), new SelectDialog.OnNegativeClickListener() {
                        @Override
                        public void onClick(SelectDialog dialog, Button button) {
                            dialog.dismiss();
                            rationale.cancel();
                        }
                    })
                    .setPositiveButton(getString(R.string.permission_button_item_agree), new SelectDialog.OnPositiveClickListener() {
                        @Override
                        public void onClick(SelectDialog dialog, Button button) {
                            dialog.dismiss();
                            rationale.resume();
                        }
                    })
                    .build();

            mSelectDialog.show();
        }
    };`

1.第一次点击后，弹出系统权限弹窗dialog，然后勾选、拒绝，第二次进来显示这个弹窗 （正常）
2.打开手机权限管理设置所有权限为：“提示”，再次点击，为什莫还是弹出这个弹窗，不应该是系统的权限弹窗dialog吗？`hasAlwaysDeniedPermission（。。。）`

**Comment by yanzhenjie** [comment]
你的标题和第一个描述中的有些词汇我不是很理解，所以第二个描述中的还是弹出这个弹窗我也看不懂到底是哪个。

**Comment by yanzhenjie** [comment]
No response close.
