### ISSUE TITLE
开启混淆忽略文件怎么配置呀

### ISSUE THREAD

**Issue by Qiaoshi96** [yanzhenjie/AndPermission#490]
<img width="884" alt="图片" src="https://user-images.githubusercontent.com/29808617/65667245-ef2ada00-e071-11e9-92ac-0b482add52ac.png">
开起混淆了没这个这个quan x2库的忽略文件

**Comment by yanzhenjie** [comment]
Can be completely confused, if there is a problem, keep it all.
