### ISSUE TITLE
小米Note手机一直回调成功获取权限

### ISSUE THREAD

**Issue by atlearn** [yanzhenjie/AndPermission#5]
小米Note手机弹出权限申请框，无论点同意还是拒绝，都是回调成功获取权限，onFailed不会回调。

**Comment by yanzhenjie** [comment]
小米note是几点几的手机？

**Comment by atlearn** [comment]
系统是基于6.0的

**Comment by KingJames6** [comment]
我也遇到这个问题了。。

**Comment by bbqichang** [comment]
@atlearn 小米据我所知还没有推出6.0的系统

**Comment by atlearn** [comment]
@bbqichang 我也是醉了 MIUI基于6.0，小米基于7.0都出来了，你还没有推出6.0

**Comment by bbqichang** [comment]
@atlearn 好吧 我查了一下miui8红米是基于android5.0的，小米和米note是基于android6.0的 我的测试机是红米我以为所有的miui8都是android5.0呢

**Comment by yanzhenjie** [comment]
这个是小米底层的问题，我已经发了新版并做了兼容，你们可以看看新版。如果回调了成功并且执行代码没有报错，说明其实权限是有的。新版功能更加强大，兼容性很好，可以看看ReadMe，谢谢指导。
