### ISSUE TITLE
没有谈成对话框

### ISSUE THREAD

**Issue by wuconghui** [yanzhenjie/AndPermission#50]
作者您好，我的vivo手机在测试的时候直接进入权限申请成功或者失败的回调，没有弹出对话框让用户选择，请问一下这是什么问题呢？

**Comment by yanzhenjie** [comment]
系统版本是多少？api leve低于23不用申请。另外如果你的app申请过该权限，很可能不会再次申请直接回调，这个和国产机有关系。

**Comment by yanzhenjie** [comment]
那你用我demo跑一下看，另外请看下中文文档的国产机问题。

**Comment by wuconghui** [comment]
用您的demo在vivo手机上不行，还是直接进入成功回调里，在坚果手机上也不行，在华为手机上可以

**Comment by yanzhenjie** [comment]
根据文档提供的做法来吧，在成功和失败中都加权限判断，没有权限就提示用户去设置中开启权限。

**Comment by hanfeng1982** [comment]
解决了吗？我在模拟器上也是没有谈任何授权对话框，直接往下面走了。

**Comment by hanfeng1982** [comment]
我是新手。我的新建项目中没有maven.gradle。直接用Android studio 2.3.2打开组件的程序，直接看到Error:(1, 0) Your project path contains non-ASCII characters. This will most likely cause the build to fail on Windows. Please move your project to a different directory. See http://b.android.com/95744 for details. This warning can be disabled by adding the line 'android.overridePathCheck=true' to gradle.properties file in the project directory.
<a href="openFile:E:\Android教程\开源组件\AndPermission-master\permission\build.gradle">Open File</a>

**Comment by yanzhenjie** [comment]
@hanfeng1982 你的问题你单独发了issue，我在新的issue中回复你，这个无响应我就关闭了。
