### ISSUE TITLE
2.0.1版本申请写入联系人权限会新增一个PERMISSION的空白联系人

### ISSUE THREAD

**Issue by yan1990y** [yanzhenjie/AndPermission#501]
手机型号/品牌型号：android studio AVD 模拟器
品牌系统版本 google模拟器
Android系统版本 9.0
项目targetSdkVersion 28
申请的权限 Permission.WRITE_CONTACTS,Permission.WRITE_EXTERNAL_STORAGE,Permission.READ_CONTACTS
发生问题的场景和操作步骤
执行请求权限代码就会在联系人里面写入一个名字叫PERMISSION的联系人，电话号码为空
代码：在下面图片中，复制粘贴格式会乱
把这段代码注释掉就没问题了
经过测试，华为、小米等多个手机不同版本也有该问题

**Comment by yan1990y** [comment]
<img width="826" alt="屏幕快照 2019-10-10 17 50 37" src="https://user-images.githubusercontent.com/31801069/66558652-7efa7900-eb86-11e9-9a5b-a0b75c30f4e8.png">

**Comment by yanzhenjie** [comment]
感谢反馈，这是一个旧的Issue了，升级到最新版本即可解决。
