### ISSUE TITLE
androidstudio编译版本是28的，怎么引入AndPermission

### ISSUE THREAD

**Issue by shimiso** [yanzhenjie/AndPermission#510]
我看文档写了只支持androidX引入
It only supports androidx, add dependencies in your gradle
那编译版本是28的，怎么引入AndPermission？总不能为了引一个权限工具，把整个工程重构吧，况且其他三方依赖的sdk也都不全是支持androidX的

**Comment by yanzhenjie** [comment]
两个方案：
1. 如果该项目确实合适的话，参考 #497
2. 如果用起来不合适，不要用就好了

提问前先看下之前的Issue哈，就不要提重复的Issue了。

**Comment by shimiso** [comment]
dependencies {
    // For developers using AndroidX in their applications
    implementation 'pub.devrel:easypermissions:3.0.0'

    // For developers using the Android Support Library
    implementation 'pub.devrel:easypermissions:2.0.1'
}

决定用easypermissions，升级成本太高，androidX迟早要生，但绝对不是当下，各种大厂sdk都还未完全跟进，我们依赖又这么多

**Comment by shimiso** [comment]
感谢
