### ISSUE TITLE
android 10电话权限问题

### ISSUE THREAD

**Issue by KotlinLan** [yanzhenjie/AndPermission#512]
![image](https://user-images.githubusercontent.com/50512101/67144154-e0fd6180-f29d-11e9-90af-439a96432a6a.png)

看了一下2.0.3版本，这里就是直接返回true了吗？

**Comment by yanzhenjie** [comment]
是的，有什么不妥吗？

**Comment by yanzhenjie** [comment]
无响应，关闭。
