### ISSUE TITLE
Android 10 定位权限 一直请求

### ISSUE THREAD

**Issue by sange93** [yanzhenjie/AndPermission#513]
机器：Android studio 模拟器
系统：Android 10
库版本：AndPermission 2.0.3
AndPermission.with(mActivity).runtime().permission(arrayOf(Permission.ACCESS_FINE_LOCATION, Permission.ACCESS_COARSE_LOCATION))
定位权限 我只申请了这两个，点了 使用时获取位置，就一直弹“正在请求授权”进度弹窗。这是什么原因呢？

**Comment by yanzhenjie** [comment]
一直弹是不停重复【弹出又消失】吗？还是说每次请求必定会弹出？

**Comment by sange93** [comment]
是不停重复【弹出又消失】，死循环了，定位权限是这样，其他权限好像没事。

**Comment by sange93** [comment]
好吧  我刚看了下，  是高德地图  在模拟器中虽然获取了权限  但拿不到定位   导致了我代码循环走获取定位方法。  才会一直弹 权限进度弹窗。

不过 还有个问题，系统弹窗中我选择“保持仅在使用时访问”，日志走的是“权限拒绝”， 这个是为什么？
我的代码：`AndPermission.with(this).runtime().permission(Permission.Group.LOCATION)
                .onGranted {
                    Log.v("test","权限通过")
                }.onDenied {
                    Log.v("test","权限拒绝")
                }.start()`

**Comment by yanzhenjie** [comment]
你是否有申请这个权限：`ACCESS_BACKGROUND_LOCATION`？

**Comment by sange93** [comment]
有申请这个权限。但还是走的是“权限拒绝”。如果我选择“一直允许”，日志是走的“权限通过”。
我的AndroidManifest.xml注册了这三个权限：

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>

**Comment by sange93** [comment]
有申请这个权限。但还是走的是“权限拒绝”。如果我选择“一直允许”，日志是走的“权限通过”。
我的AndroidManifest.xml注册了这三个权限：
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>`

**Comment by yanzhenjie** [comment]
这是个问题，这个地方是我疏忽了，我新开了一个Issue来跟踪这个问题。后面请跟踪这个Issue：#518.

**Comment by sange93** [comment]
OK

**Comment by xyStephenZhou** [comment]
为啥仅在使用中允许就走失败的回调呢？？
