### ISSUE TITLE
APP在后台运行，去关闭权限导致APP被kill掉

### ISSUE THREAD

**Issue by xiaoshi316** [yanzhenjie/AndPermission#52]
当拒绝权限的时候，调用系统Setting去设置权限，选择应用关闭或者打开需要的权限，此时app会被kill掉。

**Comment by AndroidyxChen** [comment]
我也是碰到了这个问题，暂时还不知道怎么解决~

**Comment by yanzhenjie** [comment]
回来的时候会自动调用`onActivityResult()`的吧，如果有这种情况，建议直接引导用户去设置后自杀，然后让用户再打开使用，不给权限不让用，这样用户一般都会给。

**Comment by xiaoshi316** [comment]
目前是就是这么处理～




发自网易邮箱大师
在2017年05月25日 12:45，严振杰 写道：

回来的时候会自动调用onActivityResult()的吧，如果有这种情况，建议直接引导用户去设置后自杀，然后让用户再打开使用，不给权限不让用，这样用户一般都会给。

**Comment by AndroidyxChen** [comment]
真没想到博主会回复，真的非常感谢，这个问题我再来具体分析下，非常感谢


发自网易邮箱大师
在2017年05月25日 12:45，严振杰 写道：

回来的时候会自动调用onActivityResult()的吧，如果有这种情况，建议直接引导用户去设置后自杀，然后让用户再打开使用，不给权限不让用，这样用户一般都会给。
