### ISSUE TITLE
小米5s plus, 在Service中使用, 初次安装应用申请权限后没有回调

### ISSUE THREAD

**Issue by DaleSmith** [yanzhenjie/AndPermission#520]
手机型号：小米5s Plus
品牌系统版本：MIUI10.2.2.0 稳定版
Android系统版本： Android8.0.0
targetSdkVersion：27
权限：Permission.Group.CONTACTS
在Service中使用, 初次安装应用申请权限后onGranted()和onDenied()都没有回调,调用代码如下:
`AndPermission.with(context)
                .runtime()
                .permission(Permission.Group.CONTACTS)
                .onGranted(new Action<List<String>>() {
                    @Override
                    public void onAction(List<String> data) {
                        Log.d(TAG, "onAction: " + data.toString());
                    }
                }).onDenied(new Action<List<String>>() {
            @Override
            public void onAction(List<String> data) {
                Log.d(TAG, "onAction: " + data.toString());
            }
        }).start();`
经过测试,是miui优化导致的,关闭miui优化后可以收到回调.请问应该怎么解决?

**Comment by yanzhenjie** [comment]
可能是MIUI优化开启后导致调用的这个Service在打开其他App时被回收，导致callback被回收无法回调，暂时没办法，用户应该不会开启MIUI优化吧。
