### ISSUE TITLE
Huawei Mate30申请权限失败,一直提示无权限

### ISSUE THREAD

**Issue by chenxihoulang** [yanzhenjie/AndPermission#522]
华为 Mate30在申请权限的时候,一直提示无权限,我是在onStart方法中申请READ_PHONE_STATE和WRITE_EXTERNAL_STORAGE两个权限,提示用户进入设置页面,进去后开启了所有的权限,调试的时候还是提示无权限
![IMG_0195](https://user-images.githubusercontent.com/4724467/67820836-c923aa00-faf5-11e9-847d-d082c07386f1.JPG)

**Comment by yanzhenjie** [comment]
使用最新版本的AndPermission，不能在onStart请求权限。
