### ISSUE TITLE
授权了、提示权限被拒绝了

### ISSUE THREAD

**Issue by heroleon** [yanzhenjie/AndPermission#523]
华为荣耀 JAT-AL100 魅族6pro 给了存储权限  使用过程中提示 没有存储权限

**Comment by lic2050** [comment]
同样遇到，一加7 plus
授权时给了权限，但是一直回调的onDenied

**Comment by yc654084303** [comment]
同样问题小米9，miui系统11.0.2

**Comment by heroleon** [comment]
他这个如果代码异常也会一直拒绝Leon Dong-------- 原始邮件 --------发件人： yangcan <notifications@github.com>日期： 2019年11月6日周三 11:29收件人： yanzhenjie/AndPermission <AndPermission@noreply.github.com>抄送： leon <dclforever@163.com>, Author <author@noreply.github.com>主    题： Re: [yanzhenjie/AndPermission] 授权了、提示权限被拒绝了 (#523)同样问题小米9，miui系统11.0.2

**Comment by yanzhenjie** [comment]
@heroleon  新版本不会了
