### ISSUE TITLE
拒绝权限后，在当前界面切换到设置中去动态开启权限，再次回到app，app崩溃。。

### ISSUE THREAD

**Issue by AndroidyxChen** [yanzhenjie/AndPermission#53]
其实我用的是RxPermissions，但是现在碰到一个问题就是：小米4 Android6.0，在app中需要申请权限的界面，拒绝后，去设置中手动开启权限，再次回到app当前界面，app崩溃；在app中需要申请权限的界面，允许后，去设置中手动关闭权限，再次回到app当前界面，app崩溃；虽然我用的不是AndPermission，但是觉得应该是国产系统定制的原因，希望楼主能好心解答的，谢了~

**Comment by yanzhenjie** [comment]
崩溃的话具体看是什么异常造成的崩溃。

**Comment by yanzhenjie** [comment]
#52
