### ISSUE TITLE
部分华为 9.0 机型 crash: java.lang.IllegalArgumentException:Receiver not registered

### ISSUE THREAD

**Issue by lwj1994** [yanzhenjie/AndPermission#548]
手机型号：华为 
品牌系统版本: 未知
Android系统版本： Android 9
targetSdkVersion：29
权限：未知

`
java.lang.RuntimeException:Error receiving broadcast Intent { act=com.xiachufang.lazycook.andpermission.bridge.Thread-29 flg=0x2010 } in com.yanzhenjie.permission.bridge.Messenger@9137630
--
 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1546)
 ......
 java.lang.IllegalArgumentException:Receiver not registered: com.yanzhenjie.permission.bridge.Messenger@9137630
 android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1390)
 android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1737)
 android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
 com.yanzhenjie.permission.bridge.Messenger.unRegister(SourceFile:1)
 com.yanzhenjie.permission.bridge.RequestExecutor.onCallback(SourceFile:2)
 com.yanzhenjie.permission.bridge.Messenger.onReceive(SourceFile:1)
 android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1533)
 android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
 android.os.Handler.handleCallback(Handler.java:907)
 android.os.Handler.dispatchMessage(Handler.java:105)
 android.os.Looper.loop(Looper.java:216)
 android.app.ActivityThread.main(ActivityThread.java:7625)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

`

**Comment by imliujun** [comment]
为什么关闭了？我也遇到了这个问题

**Comment by lwj1994** [comment]
小问题 我自己改了下加了个 try catch 让它不蹦  https://github.com/lwj1994/AndPermission/tree/huawei-cras h@imliujun
