### ISSUE TITLE
坚果Pro 运行Demo 申请权限的问题

### ISSUE THREAD

**Issue by 16fangougou** [yanzhenjie/AndPermission#56]
![wechatimg2](https://cloud.githubusercontent.com/assets/17920617/26670850/e781938e-46e5-11e7-95ae-793eb7093f83.png)
![Uploading WechatIMG3.png…]()

点击任意的一个测试按钮, 都直接提示获取权限成功, 但是我去系统的权限管理界面查看权限, 却显示都为未huo获取, 而且, 我从系统权限管理里把权限关闭, 再点击申请权限, 还是提示获取成功. 望排查. 

坚果Pro 系统7.1.1

**Comment by yanzhenjie** [comment]
1. 坚果手机是存在权限问题的，你可以看看国产机权限问题的兼容方案：[国产手机适配方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案)  
2. 另外你可以使用原生代码测试看看，应该也存在这个问题：[Android 6.0 运行时权限管理最佳实践](http://blog.csdn.net/yanzhenjie1003/article/details/52503533)
