### ISSUE TITLE
正式版在设置里面打开权限，无法回调PermissionYes

### ISSUE THREAD

**Issue by liumingzhuo** [yanzhenjie/AndPermission#6]
当把权限设置成不再提醒时，在设置里面打开，但Debug版可以回调，但正式版没有回调，其中grantResults的值可以得到 为0

**Comment by liumingzhuo** [comment]
解决了！ 混淆的时候   注解的回调方法不能混淆

**Comment by yanzhenjie** [comment]
谢谢反馈，我在ReadMe中添加了混淆规则了。今天发布了新版，功能更强大完善，欢迎使用。
