### ISSUE TITLE
Android studio 调用rationale方法问题

### ISSUE THREAD

**Issue by githubzaibao** [yanzhenjie/AndPermission#60]
Android studio 中无法调用rationale方法设置RationaleListener，不懂为何，在源码中能看到该方法
Error:(152, 17) 错误: 找不到符号
符号:   方法 rationale(<匿名RationaleListener>)
位置: 接口 Request

**Comment by yanzhenjie** [comment]
rationale只支持activity和fragment。

**Comment by githubzaibao** [comment]
嗯，看到了，谢谢
