### ISSUE TITLE
小米3 6.0 申请定位权限是无允许定位弹窗，直接走了成功状态。其实还是询问状态

### ISSUE THREAD

**Issue by jiangkaiying** [yanzhenjie/AndPermission#64]

**Comment by yanzhenjie** [comment]
你参考这里试试：[国产机兼容方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案)，如果调用了成功你可以直接调用你的代码试试，应该是可以用的。
