### ISSUE TITLE
hasAlwaysDeniedPermission参数问题

### ISSUE THREAD

**Issue by hehuelet** [yanzhenjie/AndPermission#66]
通过context获取权限，但是在callback如果想用hasAlwaysDeniedPermission，参数只有activity和fragment
这种情况是不是就没法只用context了？
hasAlwaysDeniedPermission 参数可以支持context吗？

**Comment by yanzhenjie** [comment]
晚上回去加一下。

**Comment by yuyangalan** [comment]
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
总是报这个错误~

**Comment by gudd1991116** [comment]
我将APP的麦克风权限关闭掉了，然后再进入界面后在oncreate()方法中使用AndPermission.with(getApplicationContext())
                .permission(Manifest.permission.RECORD_AUDIO)
                .requestCode(100)
                .callback(mPermissionListener)
                .start();
在回调中打印了下结果，
private PermissionListener mPermissionListener = new PermissionListener() {
        @Override
        public void onSucceed(int requestCode, @NonNull List<String> list) {
            UtilToolkit.showToast("success");
        }

        @Override
        public void onFailed(int requestCode, @NonNull List<String> list) {
            UtilToolkit.showToast("fail");
        }
    };
然后居然提示：success，不是应该提示fail的吗？
