### ISSUE TITLE
在设置中关闭权限，但检测时权限却返回true

### ISSUE THREAD

**Issue by gudd1991116** [yanzhenjie/AndPermission#67]
我将APP的麦克风权限关闭掉了，然后再进入界面后在oncreate()方法中使用
`AndPermission.with(getApplicationContext())
.permission(Manifest.permission.RECORD_AUDIO)
.requestCode(100)
.callback(mPermissionListener)
.start();`
在回调中打印了下结果，
`private PermissionListener mPermissionListener = new PermissionListener() {
    @override
    public void onSucceed(int requestCode, @nonnull List list) {
        UtilToolkit.showToast("success");
    }
    @Override
    public void onFailed(int requestCode, @NonNull List<String> list) {
        UtilToolkit.showToast("fail");
    }
};`
然后居然提示：success，不是应该提示fail的吗？

**Comment by hanchanpo13** [comment]
什么系统？

**Comment by hanchanpo13** [comment]
@gudd1991116 什么手机？

**Comment by Reagon** [comment]
我的 OPPO R9 也是如此  禁止权限了   还是一直返回 true，用if(AndPermission.hasPermission（）判断了也还是返回true

**Comment by neosdong** [comment]
compileSdkVersion改成23或以上就可以了

**Comment by 1242128273wangpeng** [comment]
@neosdong 没卵用，我的 OPPO R9 也是如此 禁止权限了 还是一直返回 true，用if(AndPermission.hasPermission（）判断了也还是返回true ,系统版本 6.0.1

**Comment by yanzhenjie** [comment]
系统版本需要6.0及以上，targetversionsdk需要23及以上，才会有运行时权限这个问题。如果申请权限返回true，使用`AndPermission.hasPermission()`判断一次，如果返回true，直接调用执行的代码试试，应该可以直接运行的，最最最多再弹出系统自己定制的权限管理框。
