### ISSUE TITLE
华为荣耀7的权限申请的问题

### ISSUE THREAD

**Issue by originzyf** [yanzhenjie/AndPermission#7]
使用群主的下载管理 第一次安装在下载管理里面直接显示下载出错 并且报错权限不全 所以我就用了大神你的权限管理 可以弹出权限申请框 并且我也允许了 但是会显示权限申请失败  但是下载管理里面下载就可以成功了  所以我想问下 到底权限申请成功了没有  很疑惑

**Comment by yanzhenjie** [comment]
是不是你的提示语句写错了，你最好用demo测试下手机看看。

**Comment by zdd** [comment]
同样的问题，选择同意授权，但是还是调用了onFailed函数。

**Comment by yanzhenjie** [comment]
@originzyf @zdd 刚刚发了新版，在新版中兼容了国产手机的各种问题，如果有时间麻烦再指导一下，可以看一下ReadMe介绍，再运行下demo看。
