### ISSUE TITLE
可以增加对权限组的支持吗？

### ISSUE THREAD

**Issue by ayuhani** [yanzhenjie/AndPermission#70]
申请具体权限时是没问题的，比如：
`.permission(Manifest.permission.WRITE_EXTERNAL_STORAGE)`
可以正常弹出窗口，但是改成下面的权限组时：
`.permission(Manifest.permission_group.STORAGE)`
权限默认被拒绝授权。

**Comment by yanzhenjie** [comment]
系统不支持请求权限组，我下一步计划是AndPermission内部支持请求权限组。

**Comment by ayuhani** [comment]
好的，感谢严大

**Comment by yanzhenjie** [comment]
已经更新了，增加了权限组的申请，并兼容Android 8.0.
