### ISSUE TITLE
所有权限都勾选允许，仍然会调用失败回调

### ISSUE THREAD

**Issue by ayuhani** [yanzhenjie/AndPermission#71]
`.permission(Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.GET_ACCOUNTS,
                        Manifest.permission.READ_PHONE_STATE,
                        Manifest.permission.CALL_PHONE,
                        Manifest.permission.CAMERA,
                        Manifest.permission.ACCESS_FINE_LOCATION,
                        Manifest.permission.ACCESS_COARSE_LOCATION,
                        Manifest.permission.RECORD_AUDIO,
                        Manifest.permission.SEND_SMS)`
所有都选择允许，仍然调用失败的方法，进入设置之后发现所有的权限也都是开启状态。

**Comment by yanzhenjie** [comment]
如果是国产机出现的问题，请参考[国产机兼容方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#%E5%9B%BD%E4%BA%A7%E6%89%8B%E6%9C%BA%E9%80%82%E9%85%8D%E6%96%B9%E6%A1%88)。

**Comment by ayuhani** [comment]
多谢，确实是国产机问题

**Comment by lingxiaoming** [comment]
既然出现小米4x这种问题，为什么在弹框获取权限的地方检查权限不添加hasPermission的AppOps检查呢，望修复

**Comment by yanzhenjie** [comment]
正在准备新版本。
