### ISSUE TITLE
我需要实现类似新浪微博的权限提示框效果

### ISSUE THREAD

**Issue by m122469119** [yanzhenjie/AndPermission#73]
请把 private static String[] getDeniedPermissions(Context context, @NonNull String... permissions) {}改为公共方法..

**Comment by yanzhenjie** [comment]
请在申请权限之前弹框提示用户即可。

**Comment by m122469119** [comment]
其实我是想获取第一次启动App,未被用户授权的权限,再次进入App的时候,根据未被授权的权限去动态生成
自定义对话框里的权限列表..

**Comment by yanzhenjie** [comment]
那你是仅仅需要那一个方法，比较高度的自定义，目前还没有更新，你不妨从源码中把那个方法复制出来。
