### ISSUE TITLE
小米手机的相机权限问题

### ISSUE THREAD

**Issue by T-mans** [yanzhenjie/AndPermission#74]
复现步骤：
1，全新安装app
2，申请相机权限
3.点击拒绝相机权限
4.弹出AndPermission.defaultSettingDialog.show去设置界面打开相机权限
5.返回app界面
6.点击图标，使用AndPermission.hasPermission判断相机权限，返回仍然是false

我个人去设置中心看了下：小米有两个权限设置入口，通过“权限管理”进入显示相机权限是关闭的（称为A界面），通过“更多应用”-“选择安装的app”-“权限管理”进入显示相机权限是开启的（成为B界面）。后者也正是AndPermission点击设置所能打开的界面。

A界面是小米自己加的，B界面和原生系统是一致的。
所以，我判定：AndPermission.hasPermission返回了小米对于一款应用的真实权限，所以通过AndPermission.defaultSettingDialog.show打开去设置的界面打开权限是“无效的”。

所以：这个问题可以解决吗？
硬件：小米4。系统内核6.0.1。系统版本：MIUI8.5.2.0

**Comment by yanzhenjie** [comment]
这种情况下，建议用`hasPermission`判断没权限后直接提示用户去设置中授权后再使用。

**Comment by guiying712** [comment]
小米手机在“安全中心”还有一个管理手机APP权限的地方，如果不在“安全中心”这里给予APP权限，即使在设置中给了APP权限，那这个APP也不会有相应的权限。

**Comment by yanzhenjie** [comment]
> 刚刚发布了1.1.0，支持申请权限组，支持Android O（Android8.0）。
对上 @guiying712 说的问题用一个Dialog提示用户打开系统Setting授权，用户点击确定的时候打开Setting也可以。
