### ISSUE TITLE
调用start()报错

### ISSUE THREAD

**Issue by PanGuDaShen** [yanzhenjie/AndPermission#76]
代码：
**********************************************************************************************************
 AndPermission
                .with(this)
                .requestCode(REQUEST_CODE_PERMISSION_OTHER)
                .permission(Manifest.permission.WRITE_CALENDAR,Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.SEND_SMS,Manifest.permission.READ_SMS,
                        Manifest.permission.CALL_PHONE)
                .rationale(object :RationaleListener{
                    override fun showRequestPermissionRationale(requestCode: Int, rationale: Rationale?) {
                        // 这里的对话框可以自定义，只要调用rationale.resume()就可以继续申请。
//                        AndPermission.rationaleDialog(this@MainActivity, rationale).show()
                        AcpDialog.newAcpDialog(null)
                                .setOnAcpDialoglister(object : AcpDialog.OnAcpDialoglister{
                                    override fun onClick(str: String) {
                                        when(str){
                                            "NO" -> Toast.makeText(this@MainActivity,"$str",Toast.LENGTH_SHORT).show()
                                            "YES" -> Toast.makeText(this@MainActivity,"$str",Toast.LENGTH_SHORT).show()
                                        }
                                    }

                                })
                        Toast.makeText(this@MainActivity,"CCC",Toast.LENGTH_SHORT).show()
                    }
                })
                .callback(object : PermissionListener{
                    override fun onSucceed(requestCode: Int, grantPermissions: MutableList<String>) {
                        when(requestCode){
                            REQUEST_CODE_PERMISSION_OTHER -> {
                                Toast.makeText(this@MainActivity,"AAA",Toast.LENGTH_SHORT).show()
                            }
                        }
                    }

                    override fun onFailed(requestCode: Int, deniedPermissions: MutableList<String>) {
                        when (requestCode) {
                            REQUEST_CODE_PERMISSION_OTHER -> {
                                Toast.makeText(this@MainActivity, "BBB", Toast.LENGTH_SHORT).show()
                            }
                        }
                        // 用户否勾选了不再提示并且拒绝了权限，那么提示用户到设置中授权。
//                        if (AndPermission.hasAlwaysDeniedPermission(this@MainActivity, deniedPermissions)) {
//                            // 第一种：用默认的提示语。
//                            AndPermission.defaultSettingDialog(this@MainActivity, 300).show()
//                        }
                    }
                }).start()
***********************************************************************************************************
 android.content.ActivityNotFoundException: Unable to find explicit activity class {com.xxx.app.mian/com.yanzhenjie.permission.PermissionActivity}; have you declared this activity in your AndroidManifest.xml?
添加的依赖包，清单文件中找不到注册的PermissionActivity

**Comment by yanzhenjie** [comment]
是不是方法数超过了64k？[参考这篇文章](http://blog.csdn.net/yanzhenjie1003/article/details/51818269)。

**Comment by zhang110116** [comment]
依赖包的清单文件中添加PermissionActivity 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.yanzhenjie.permission">

    <application>
        <activity
            android:name=".PermissionActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:launchMode="standard"
            android:theme="@style/permission_PermissionActivity"
            android:windowSoftInputMode="stateHidden|stateAlwaysHidden"/>
    </application>

</manifest>
