### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by qiangxi** [yanzhenjie/AndPermission#77]
最好把library中的appcompat包依赖改成provided 方式的，compile方式的依赖是强依赖，如果开发者项目中的appcompat版本与library中appcompat的版本不一致，就会引入两个不同版本的appcompat包，而这样可能造成crash。所以android官方建议support版本都尽量保持一致。

**Comment by yanzhenjie** [comment]
可以使用exclude试试：
```
compile (group: 'com.yanzhenjie', name: 'permission', version: '1.1.0') {
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```
