### ISSUE TITLE
我使用1.0.8版本的代码没有问题，可以正常调用权限对话框。但是在测试了1.0.9和1.1.0以后，在有些项目中，会离奇的无法调用出权限对话框。

### ISSUE THREAD

**Issue by Virczz** [yanzhenjie/AndPermission#81]
这个问题，经过我测试了昨天下午加今早才测出来的。具体原因不清楚，猜测是新版本中，相关对话框的判断没有走。

**Comment by yanzhenjie** [comment]
代码贴一下。

**Comment by Virczz** [comment]
不好意思，前两天在忙东西，没注意看。
代码不好贴，不过我git了一个demo项目，确实存在这个问题。
[https://github.com/Virczz/HostApp](url)

**Comment by zhangls2014** [comment]
我也遇到这个问题了

在同样代码相同的情况下，刚集成的时候是可以调出权限对话框的，但是不知道什么时候开始不行了，虚拟机真机都不行，代码没有任何修改。
将版本从 1.1.0 改成 1.0.8 还真的就可以了

`AndPermission.with(this)
                .requestCode(100)
                .permission(Manifest.permission.READ_PHONE_STATE)
                .callback(permissionListener)
                .rationale(rationaleListener)
                .start();`

代码大概就是这样

**Comment by 742926441** [comment]
小米和红米好像都没弹出对话框

**Comment by KentFeng** [comment]
我的是锤子坚果和魅族note2，现象是第一次拒绝后，重进页面重新请求不会弹出不再提示的对话框，也不走Rationale回调了。不知道是什么原因

**Comment by yanzhenjie** [comment]
国产手机就这鸟样子。不过我在开发AndPermission新版了，到时候Api稍微改动下，可以完全兼容国产手机了。

**Comment by KentFeng** [comment]
好的，杰哥辛苦

**Comment by yanzhenjie** [comment]
AndPermission2.0已经发布了alpha版本了，马上会发布正式版，大家可以用alpha先试用一下，有问题请大家再提issue，感谢支持。
