### ISSUE TITLE
关于建议 一的疑问

### ISSUE THREAD

**Issue by Olaman** [yanzhenjie/AndPermission#83]
我按照您给的建议 "在回调的成功和失败方法中都加这段代码: "
 if(AndPermission.hasPermission()) {
    // TODO 执行拥有权限时的下一步。
} else {
    // 使用AndPermission提供的默认设置dialog，用户点击确定后会打开App的设置页面让用户授权。
    AndPermission.defaultSettingDialog(this, requestCode).show();
    
    // 建议：自定义这个Dialog，提示具体需要开启什么权限，自定义Dialog具体实现上面有示例代码。
}

在Redmi4X, 6.0.1系统上,
 1. 先拒绝权限
 2. 弹出对话框后去setting页面赋予所有权限; 
3.返回app, 会执行到onSucceed() 方法, 
 但是AndPermission.hasPermission() 判断为否. 

 在回调的成功方法中 不能做AndPermission.hasPermission()??

**Comment by qiangxi** [comment]
这是小米系列的问题,不管是Redmi4X,还是其他小米手机,很多都有这个问题,因为小米系列手机都有一个"安全中心" APP,这个"安全中心" 简直逆天,即便你在系统设置中赋予了权限,但是这个"安全中心" 没有赋予权限的话,基本都相当于没赋予权限,所以你会遇到那种情况,不信的话,你可以通过"安全中心"把权限都赋予了,你的 AndPermission.hasPermission()就为true了.

**Comment by yanzhenjie** [comment]
@qiangxi 同学说的是对的，建议直接提示去系统设置中进行授权。
