### ISSUE TITLE
为什么一定要是24的api levele这个一定要限定死吗？从23开始不行吗

### ISSUE THREAD

**Issue by mrchenmo** [yanzhenjie/AndPermission#86]

**Comment by mrchenmo** [comment]
库的 依赖版本能从23开始吗，我看您的库的版本是直接依赖的25，是为了适配8.0吗

**Comment by yanzhenjie** [comment]
高了还不好？这个并不会限制你使用哪个版本，你用graldle依赖即可。

**Comment by mrchenmo** [comment]
@yanzhenjie 高了和我项目冲突 value-24错误，导致我需要把compileSdkVersion调到24才可以。

**Comment by yanzhenjie** [comment]
这个确实不是AndPermission项目的问题，你前面描述的这个很正常也很常见。
你后面说的我看的不是很懂，大致知道是两个version不同起了冲突，以你目前能解决的方式解决即可。

**Comment by zjxuzhj** [comment]
compileSdkVersion调到24对你没有任何损失
