### ISSUE TITLE
提示跳转到设置界面后，回来onActivityForResult没有回调，也就没办法处理之后的逻辑

### ISSUE THREAD

**Issue by Dragon-Boat** [yanzhenjie/AndPermission#87]
miui系统，fragment中发起
# help wanted

**Comment by yanzhenjie** [comment]
如果是context调起的是，是没法回调的，除非是activity或者fragment。还有如果是activity或者fragment调起的，在小米上也不能保证一定会回调。建议直接提示用户去Setting授权。

**Comment by echolong** [comment]
可以在打开设置时候加个isOpenSetting=true，然后再onResume中判断是否打开了设置Settings.System.canWrite(mActivity)
