### ISSUE TITLE
the permission group has a mistake

### ISSUE THREAD

**Issue by KDisEDDY** [yanzhenjie/AndPermission#88]
I require the permission of READ_SMS
AndPermission.with(this)
                        .requestCode(REQUESTCODE_OPENSMS)
                        .permission(Permission.SMS)
                        .rationale(rationaleListener)
                        .callback(listener)
                        .start();

first I refused the permission , then next time I required again . the app post a rationale dialog , allowed the permission but the app refused again ,Here is my rationale Listener and PermissionListener code:

private PermissionListener listener = new PermissionListener() {
        @Override
        public void onSucceed(int requestCode, List<String> grantedPermissions) {
            // Successfully.
            if(requestCode == REQUESTCODE_OPENSMS) {
                Uri smsToUri = Uri.parse("smsto:");
                Intent intent = new Intent(Intent.ACTION_SENDTO, smsToUri);
                intent.putExtra("sms_body","ddddddddddd");
                startActivity(intent);
            }
        }

        @Override
        public void onFailed(int requestCode, List<String> deniedPermissions) {
            // Failure.
            if(requestCode == REQUESTCODE_OPENSMS) {
                Toast.makeText(PermissionActivity.this, "Permisstion denied", Toast.LENGTH_SHORT).show();
            }
        }
    };
private RationaleListener rationaleListener = (requestCode, rationale) -> AlertDialog.newBuilder(this)
            .setTitle("Tips")
            .setMessage("需要提供读取短信权限用于内容收集")
            .setPositiveButton("好的", (dialog, which) -> rationale.resume())
            .setNegativeButton("拒绝", (dialog, which) -> rationale.cancel()).show();

   I debug the AndPermission Code and I found that permission of READ_SMS has required but the group of the another permission hasn't .Is the mistake of permission group ?

**Comment by yanzhenjie** [comment]
If mobile phone is produced in China, you can see [国产手机适配方案](https://github.com/yanzhenjie/AndPermission/blob/master/README-CN.md#国产手机适配方案). If you do not need to request for permission groups, you can request for a few permissions only.

**Comment by KDisEDDY** [comment]
@yanzhenjie  Ok, I user the single permission instead of permission groups. Thanks
