### ISSUE TITLE
在项目里 未退出项目 直接在设置里更改权限，会退出 

### ISSUE THREAD

**Issue by yanchengdeng** [yanzhenjie/AndPermission#91]
增对这个问题 我有测试过 新浪微博 、美团的app 都会有这个异常退出。而且bug 日志也找不到，想问下 这是 6.0以上权限  的系统bug 吗

**Comment by yanzhenjie** [comment]
不是bug，本身就是这样子，但是有的国产手机上不会。

**Comment by yanchengdeng** [comment]
thx  ,I konw  !
