### ISSUE TITLE
use Fragment not Activity like Rxpermission

### ISSUE THREAD

**Issue by ytjojo** [yanzhenjie/AndPermission#96]
在沉浸式状态栏的界面申请会有黑色状态栏，如果用fragment就可以避免主题的问题。在我们app启动页申请权限的时候有明显的打开关闭activity痕迹

**Comment by CaptainJno** [comment]
我也出现同样的问题，截图见链接：
[http://upload-images.jianshu.io/upload_images/2615270-561cdc7b25c52b92.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](url)

**Comment by CaptainJno** [comment]
我的问题解决了：经过编码测试，发现，问题虽然是在使用AndPermission时出现，但是，原因在于沉静式界面和Toast有冲突，导致如上图的黑框。根本原因没细查。
解决办法：我的Splash不需要显示Toast, 去掉Toast就好了。

**Comment by yanzhenjie** [comment]
你们可以试试AndPermission2.0-alpha，我快要发布2.0的正式版了，对国产机做了很多优化和兼容。
