### ISSUE TITLE
华为荣耀V9 7.0ROM 授权后第二次依然是走失败回调

### ISSUE THREAD

**Issue by Townwang** [yanzhenjie/AndPermission#97]
授权后每次进来依然走的失败回调  而且hasPermission 一直为true   

拒绝权限 走失败回调 hasPermission为true
授权  走失败回调 hasPermission为true
这个咋整?

**Comment by cervy** [comment]
同问

**Comment by yanzhenjie** [comment]
那就在true下直接执行代码。
